### ISSUE TITLE
Last Updated fallback not working

### ISSUE THREAD

**Issue by trueberryless** [withastro/starlight#1043]
### What version of `starlight` are you using?

0.11.1

### What version of `astro` are you using?

3.3.4

### What package manager are you using?

pnpm

### What operating system are you using?

Windows

### What browser are you using?

Brave

### Describe the Bug

If I create a new page in the default Language, the lastUpdated Field works just fine. 

However, if I change the language and Starlight shows the fallback content, it doesn't use the lastUpdated Date from the fallback content but nothing, which is confusing...

### Link to Minimal Reproducible Example

https://starlight.astro.build/tr/guides/i18n/

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by trueberryless** [comment]
I would say it makes sense to try to achieve following behaviour because the edit link also points to the default file, discussed here: #981

Last Updated should always show the time, when the content which is shown was updated...

**Comment by delucis** [comment]
Thanks for the issue @trueberryless!

Yes, this feels spiritually like the same issue as #981. `getLastUpdated()` in [`utils/route-data.ts`](https://github.com/withastro/starlight/blob/f9f96c88c8963b0d1aed58169181bbc992a3e03d/packages/starlight/utils/route-data.ts#L69-L81) should take `isFallback` into account when creating the file path into account.
