### ISSUE TITLE
`...` showing up in the title of code block

### ISSUE THREAD

**Issue by kdheepak** [withastro/starlight#1158]
### What version of `starlight` are you using?

0.13.0

### What version of `astro` are you using?

3.2.3

### What package manager are you using?

npm

### What operating system are you using?

Mac

### What browser are you using?

Firefox

### Describe the Bug

I am not expecting `...` to show up as the title of a code block.

Here's the source code:

````markdown
## Run loop

Our application runs in a continuous loop, constantly checking for user input and updating the
state, which in turn updates the display on the next loop.

```rust
  // Main application loop
  loop {
    // draw UI based on state
    // ...
    // Update state based on user input
    // ...
    // Break from loop based on user input and/or state
  }
```

Every TUI with `ratatui` is bound to have (at least) one main application run loop like this.
````

https://github.com/ratatui-org/website/blob/28d94f28861b882c3855b33d2ba76d9d54f9d327/src/content/docs/tutorials/counter-app/single-function.md#L110-L126

And this is what it renders as:

<img width="750" alt="image" src="https://github.com/withastro/starlight/assets/1813121/983b2444-03b2-4109-86a9-d796a17bede5">

I've never used stackblitz before and I'm not able to get starlight to even render any of my changes there, so wasn't able to create a reproducible build

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-8w69sw-ubyxl7?file=src%2Fcontent%2Fdocs%2Findex.mdx

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by HiDeoo** [comment]
Thanks for your feedback.

I feels like this may be an issue with [Expressive Code](https://github.com/expressive-code/expressive-code) and the frame plugin feature to add a [frame title using comments](https://github.com/expressive-code/expressive-code/blob/main/packages/@expressive-code/plugin-frames/README.md#adding-titles-open-file-tab-or-terminal-window-title). Maybe the first comment in the file with a dot and not whitespace in the text is interpreted as frame title but I am not sure without looking at the code.

(ping @hippotastic )

There are two potential workarounds in the meantime:

- Hiding the frame:

  ````
  ```rust frame="none"
  // Main application loop
  loop {
    // draw UI based on state
    // ...
    // Update state based on user input
    // ...
    // Break from loop based on user input and/or state
  }
  ```
  ````

- Giving explicitely a frame title:

  ````
  ```rust title="main.rs"
  // Main application loop
  loop {
    // draw UI based on state
    // ...
    // Update state based on user input
    // ...
    // Break from loop based on user input and/or state
  }
  ```
  ````

Here is a [link](https://stackblitz.com/edit/github-dgpcjv?file=src%2Fcontent%2Fdocs%2Findex.mdx) to a repro and the 2 workarounds.

**Comment by kdheepak** [comment]
The workaround is good enough for us. Feel free to close this issue if you think it is not relevant for this repo!

**Comment by hippotastic** [comment]
Thank you for reporting this! I'll fix the issue upstream in Expressive Code and let you know here.

**Comment by delucis** [comment]
Thanks for the quick fix @hippotastic! Will close this issue as resolves upstream for now.
