### ISSUE TITLE
lastUpdated displays incorrect date

### ISSUE THREAD

**Issue by tmcw** [withastro/starlight#1166]
### What version of `starlight` are you using?

0.13.1

### What version of `astro` are you using?

3.6.3

### What package manager are you using?

npm

### What operating system are you using?

macOS

### What browser are you using?

Firefox

### Describe the Bug

I set `lastUpdated` in frontmatter to 2023-03-24:

![CleanShot 2023-11-29 at 13 40 48@2x](https://github.com/withastro/starlight/assets/32314/9d341bd0-073e-4123-8dd6-c9562ce1e3de)

And get March 23, 2024 as the output on the page:

![CleanShot 2023-11-29 at 13 40 23@2x](https://github.com/withastro/starlight/assets/32314/c7ac2444-66c1-4b84-bf97-69f8e7732d1a)

But the `<time>` element includes the correct date.

The underlying component uses `toLocaleDateString`:

https://github.com/withastro/starlight/blob/64d25c125c80375ff7b2cbf749f3c35d49b8bc98/packages/starlight/components/LastUpdated.astro#L14

Which [uses the user-agent's timezone](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleDateString). So I'm at -5 offset, so it'll always show the wrong day on my computer.

### Link to Minimal Reproducible Example

http://stackblitz.com/sorry-i-can-submit-a-pr-this-is-pretty-well-described-right

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by delucis** [comment]
Ah, good catch. Would love a PR to make this build time zone agnostic!

**Comment by tmcw** [comment]
Opened a PR: https://github.com/withastro/starlight/pull/1170
