### ISSUE TITLE
Installing from template is broken

### ISSUE THREAD

**Issue by jeanlucaslima** [withastro/starlight#1244]
### What version of `starlight` are you using?

0.14.0

### What version of `astro` are you using?

4.0.2

### What package manager are you using?

npm

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

The command `npm create astro@latest -- --template starlight` is not working. 

Steps to reproduce: 

1. Create a new project using starlight template as instructed on the [Getting Started tutorial](https://starlight.astro.build/getting-started/).
2. Go through the steps
3. Observe it fail 

Here's how it looks like: 
<img width="799" alt="image" src="https://github.com/withastro/starlight/assets/1311402/dc3101d0-6065-4ed4-a167-ce7c933aca75">

If you go to the directory created (successfully) and just run `npm install` it gives this error: 
<img width="742" alt="image" src="https://github.com/withastro/starlight/assets/1311402/1279b2cd-5e59-46c0-a549-ec58f519442b">

Here's the package.json file: 
```json
 {
  "name": "confraria.tech",
  "type": "module",
  "version": "0.0.1",
  "scripts": {
    "dev": "astro dev",
    "start": "astro dev",
    "build": "astro build",
    "preview": "astro preview",
    "astro": "astro"
  },
  "dependencies": {
    "@astrojs/starlight": "^0.14.0",
    "astro": "^4.0.1",
    "sharp": "^0.32.5"
  }
}
```

This is likely caused by the fact the template is trying to fetch the latest release. 

### Link to Minimal Reproducible Example

https://stackblitz.com/github/withastro/starlight/tree/main/examples/basics?file=README.md

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by delucis** [comment]
Just merged our release PR (#1240) so Starlight v0.15 with Astro 4 support should be released any second now to fix this! Thanks again for reporting and apologies for the roadbump.
