### ISSUE TITLE
Scroll bar on package manager tabs

### ISSUE THREAD

**Issue by Fryuni** [withastro/starlight#1253]
### What version of `starlight` are you using?

latest, happens on starlight itself

### What version of `astro` are you using?

latest, happens on starlight itself

### What package manager are you using?

pnpm

### What operating system are you using?

Linux

### What browser are you using?

Chrome

### Describe the Bug

How the package manager tabs look on my Chrome:
![image](https://github.com/withastro/starlight/assets/11063910/34b776f8-66a0-4537-8186-50604719ae98)

How it looks on Firefox:
![image](https://github.com/withastro/starlight/assets/11063910/6301b419-0213-4eac-b0be-2e2c40d21994)

I didn't test on other platforms (only have a Linux box at the moment).

Chris showed what it looks like in Arc on Discord and it doesn't happen there. Since Arc is Chromium based I assume this is not happening on Mac.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-qxeu6c?file=src%2Fcontent%2Fdocs%2Findex.mdx

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Fryuni** [comment]
Seems like this was fixed at some point. Great job everyone!

**Comment by delucis** [comment]
Heh, not sure it was fixed intentionally, but then scrollbars also weren’t intentional 😅 

Glad to hear it though — thanks for letting us know 🙌
