### ISSUE TITLE
Right-to-left style is not functioning correctly

### ISSUE THREAD

**Issue by Mrahmani71** [withastro/starlight#126]
### What version of `starlight` are you using?

0.0.18

### What version of `astro` are you using?

2.5.0

### What package manager are you using?

pnpm

### What operating system are you using?

Windows

### What browser are you using?

Brave

### Describe the Bug

Hello,

I wanted to use Starlight for a project to write text in the Farsi language (right to left). However, I have noticed that the right-to-left feature is not functioning correctly. Specifically, when I set the language to Farsi, the right-to-left style is only applied when there is another language present in the project. If Farsi is the sole language used, the right-to-left style is not applied.

Is it possible to set the default dir="rtl" in the Starlight configuration?

Thank you.
![1](https://github.com/withastro/starlight/assets/13013819/eb155e8c-846c-496a-908f-fa46ed50471a)
![2](https://github.com/withastro/starlight/assets/13013819/851f6e4a-3f3c-4cc3-b714-1f92d3a25d04)

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by delucis** [comment]
Thanks for the issue @Mrahmani71! Looks like a bug in how we handle the default locale. The config you have in the first screenshot should work. I’ll take a look!

**Comment by Mrahmani71** [comment]
Thank you, @delucis . Excuse me, I have a question: Is it possible to replace the default font with a custom font? This font has a more attractive appearance compared to the default font [Vazirmatn](https://github.com/rastikerdar/vazirmatn)

**Comment by delucis** [comment]
Found the bug: #129 will fix this when released.

Re: custom fonts — yes, this is possible. I still need to document it properly, but this is the general approach:

1. Add your font files to `public/`
2. Write a CSS file with the necessary `@font-face` rules to link to those and also set this variable:
   ```css
   :root {
     --sl-font: Vazirmatn;
   }
   ```
3. Add the CSS file to the [`customCss` array](https://starlight.astro.build/reference/configuration/#customcss) in `astro.config.mjs`

It looks like Vazirmatn is available from an npm package with a ready-made CSS file, so you can also use it a little more easily:

1. Install the package: `npm i vazirmatn` (or `pnpm`/`yarn` etc.)
2. Write the CSS file as above, e.g. `src/custom.css`:
   ```css
   :root {
     --sl-font: Vazirmatn;
   }
   ```
3. Add the Vazirmatn CSS and your custom CSS to `astro.config.mjs`:
   ```js
   starlight({
     // other config ...
     customCss: [
       'vazirmatn/Vazirmatn-font-face.css',
       '/src/custom.css',
     ],
   })
   ```
