### ISSUE TITLE
Left sidebar scroll bar problem

### ISSUE THREAD

**Issue by 2113ic** [withastro/starlight#1350]
### What version of `starlight` are you using?

latest

### What version of `astro` are you using?

latest

### What package manager are you using?

pnpm

### What operating system are you using?

Windows

### What browser are you using?

Chrome

### Describe the Bug

As described in the issue https://github.com/withastro/docs/issues/5771,
I've noticed that this issue hasn't been resolved yet. Here is a simple way to solve it: 
![image](https://github.com/withastro/starlight/assets/69682691/6b835c2e-d7b6-450b-85de-5723571b5701)
I'm not sure if this is the ideal solution for you.

### Link to Minimal Reproducible Example

n/a

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by delucis** [comment]
Thanks for the issue @2113ic — could you describe the issue in a bit more detail? I don’t think the CSS you suggest would address that issue in Astro docs (position resetting on navigation), but maybe something else?

**Comment by 2113ic** [comment]
> Thanks for the issue @2113ic — could you describe the issue in a bit more detail? I don’t think the CSS you suggest would address that issue in Astro docs (position resetting on navigation), but maybe something else?

I'm sorry, I misunderstood the original question. For the original issue, you might consider using the JavaScript API `scrollIntoView` to address it.
