### ISSUE TITLE
Pagefind not working with PNPM and Firebase Hosting

### ISSUE THREAD

**Issue by pavanpodila** [withastro/starlight#1406]
### What version of `starlight` are you using?

0.16.0

### What version of `astro` are you using?

4.2.1

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

`astro build` is failing to enable pagefind in production, when deployed on firebase hosting. The build is able to generate the search indexes but the Search component fails to recognize that it is deployed in production.

### Link to Minimal Reproducible Example

na

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by pavanpodila** [comment]
Looks like the `import.meta.env.DEV` is true even in `astro build`. Not sure if it is getting passed correctly on `astro build`. If search indexing is happening, I think it is getting set, just not being passed to the components ?

Search component check: https://github.com/withastro/starlight/blob/main/packages/starlight/components/Search.astro#L41

**Comment by delucis** [comment]
Thanks for the issue @pavanpodila!

Couple of questions:

1. If you run the build locally and preview (`npm run build && npm run preview`), does search work as expected?
2. Could you try logging `import.meta.env.DEV` somewhere in your code to see the value when building on Firebase? It shouldn’t be true when running `astro build`, but maybe there’s something special about the Firebase environment?

**Comment by pavanpodila** [comment]
Hi @delucis,
 After a bit more debugging I found that the problem was with the `firebase.json` configuration. It was using the `source` property instead of the `public` property, which was forcing it to build it in **development** mode. After switching to `public: "dist"`, it started working correctly. Looks like a bug in the firebase-tools cli.

**Comment by delucis** [comment]
Thanks for the update and happy to hear you’ve got it working 🙌
