### ISSUE TITLE
Astro devToolBar audit create a warning on code block

### ISSUE THREAD

**Issue by NicolasRenault** [withastro/starlight#1411]
### What version of `starlight` are you using?

0.16.0

### What version of `astro` are you using?

4.2.1

### What package manager are you using?

npm

### What operating system are you using?

Windows

### What browser are you using?

Chrome

### Describe the Bug

I'm currently building a site with Starlight and I have come across a slight issue. 

When using code block from markdown, the audit from the devToolBar gives me this warning: 

![image](https://github.com/withastro/starlight/assets/59968905/4ca336cf-f38a-409e-914c-ec1f6a337f55)

I don't know if it's intended this way.

Since the problem is in DEV only, I'm giving the [Github link](https://github.com/NicolasRenault/two-mi18n/tree/main/docs) as a Minimal Reproducible Example. Sorry if this is an issue.

### Link to Minimal Reproducible Example

https://github.com/NicolasRenault/two-mi18n/tree/main/docs

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by delucis** [comment]
Thanks for the issue! I think this is actually a false positive in the dev toolbar. Code samples are focusable (thanks to the `tabindex` attribute) so that keyboard users can focus and scroll them.

**Comment by delucis** [comment]
Actually, just chatted with the team and looks like it is a valid issue because the code snippets generate `tabindex` statically at build time, but we don’t have any dynamic code to remove those on non-scrollable code snippets (or add back when the window resizes etc.)

@OliverSpeir is going to look into fixing this upstream in https://github.com/expressive-code/expressive-code, which we use for code block rendering. Thanks again for raising it!

**Comment by delucis** [comment]
Created an issue to track this in the Expressive Code repo to track this and added some more context and research I collected there: https://github.com/expressive-code/expressive-code/issues/138

Will close this issue as this will need fixing upstream. Thanks again for bringing our attention to this @NicolasRenault 🙌

**Comment by NicolasRenault** [comment]
Wow you guys are quick ! 
Thanks you both.
