### ISSUE TITLE
Language Select incorrectly appends locale when switching index pages

### ISSUE THREAD

**Issue by kevinzunigacuellar** [withastro/starlight#1423]
### What version of `starlight` are you using?

0.17

### What version of `astro` are you using?

4.2.6

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

Using different locales (en,es) and setting my build to format `file`. My index page is located in `en.html` and `es.html` respectively. 

When switching from one language to the other using the select element, it incorrectly adds a locale in front of my route instead of replacing the route.

### Current behavior ❌ 

When going from `es` to `en`:

`es.html` -> `en/es.html`

When going from `en` to `es`:

`en.html` -> `es/en.html`

### Expected behavior ✅ 

`en.html` -> `es.html` and viceversa

### Link to Minimal Reproducible Example

https://github.com/kevinzunigacuellar/bug-language-pick

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by kevinzunigacuellar** [comment]
Happy to tackle this if we have no other takers. I will leave it open if anyone is interested.

**Comment by delucis** [comment]
Thanks @kevinzunigacuellar! I tried writing a few tests on the train earlier and the one thing I realised I'm not sure about with sites using `build.output: 'file'` is what they do for the homepage, like is it `example.com/index.html`? Or would they expect to special case that as `example.com/`? I'm honestly not sure what expectations are.

**Comment by kevinzunigacuellar** [comment]
I would think they would expect `example.com/index.html`. `example.com/` would probably redirect to `example.com/index.html`

**Comment by delucis** [comment]
I think we can definitely take that as our working hypothesis.

I'm still feeling like our use of `build.format` as also determining link format may not be what everyone wants, but I think it's ok for us to get this consistent at this point and think about that later when we hear from folks what they need.
