### ISSUE TITLE
Mobile header cannot accumulate long documentation name and it covers search button

### ISSUE THREAD

**Issue by patryk-smc** [withastro/starlight#1433]
### What version of `starlight` are you using?

0.17.0

### What version of `astro` are you using?

4.2.6

### What package manager are you using?

yarn

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

Mobile header cannot accumulate long documentation name and it covers search button
![Screenshot 2024-01-29 at 17 16 55@2x](https://github.com/withastro/starlight/assets/37963339/91940744-46ef-46fd-9b43-261bee025dad)

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-6behai?file=astro.config.mjs

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by delucis** [comment]
Thanks for the issue! I swear we fixed this once before to truncate the title if long enough. Should hopefully be a small CSS fix.
