### ISSUE TITLE
Table of Contents Glitch

### ISSUE THREAD

**Issue by SatanshuMishra** [withastro/starlight#1448]
### 📝 Issue Description

When selecting the "Content Collect Errors" section header, the page slides down to the section. However the highlight on the Table of Contents is not updated. Whichever section was previously highlighted, remains highlighted. This behaviour occurs when the browser window is maximized or in full screen mode and page is at normal zoom level. 

<img width="1607" alt="image" src="https://github.com/withastro/docs/assets/63601536/2f41325a-ff61-43ee-aced-9c3d0225bd34">

### 📋 On which page(s) it occurs

https://docs.astro.build/en/reference/error-reference/#content-collection-errors

### 🤔 Expected Behavior

When the browser window is maximized or in full screen mode and page is at normal zoom level, when the "Content Collect Errors" section header is selected, the page scrolls down to the section and the section header is highlighted in the Table of Contents.

### 👀 Current Behavior

Currently, while the page slides down to the section, the section header on the table of contents is not highlighted. This is probably because there isn't enough room at the bottom of the page for the heading to come into focus.

### 🖥️ Browser

Arc Version 1.26.0, Chrome Version 120.0.6099.234

### 📄 Additional Information

This problem is relevant for large window sizes and screen resolutions.

**Comment by delucis** [comment]
OK, I did some testing with the ever handy https://github.com/pomber/intersection-observer-debugger and I think simply increasing the height of our root margin box should solve this satisfactorily.

Currently this is is set to `1.5rem` to match the default margin for most elements:

https://github.com/withastro/starlight/blob/5d2a5a7da4b6d025da2b5e77323124600353cee5/packages/starlight/components/TableOfContents/starlight-toc.ts#L98-L99

Things are a bit fuzzier now: the maximum margin is for an `<h2>` at `1.5em * 2.1875rem` on large viewports, a.k.a. `52.5px`, but testing with a value of `53` here seems to work pretty well across different contexts 🤞
