### ISSUE TITLE
Both dark and light Starlight appears when JS disabled

### ISSUE THREAD

**Issue by jermanuts** [withastro/starlight#1470]
### What version of `starlight` are you using?

0.17.3

### What version of `astro` are you using?

4.2.1

### What package manager are you using?

pnpm

### What operating system are you using?

Windows

### What browser are you using?

Brave

### Describe the Bug

With JavaScript enabled:
![image](https://github.com/withastro/starlight/assets/109705802/d18feadb-3d50-4c49-a90d-4640ac3e0d00)
---
With JavaScript disabled:

![image](https://github.com/withastro/starlight/assets/109705802/2ffabd9e-4d64-4dd8-80a7-696f0e3ee183)

I couldn't reproduce it. Specific to starlight.astro.build

### Link to Minimal Reproducible Example

https://github.com/withastro/starlight

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by delucis** [comment]
Thanks for the issue @jermanuts! I know why this is happening — will make a quick PR.
