### ISSUE TITLE
Letters get auto-generated in front of Frontmatter when have closing HTML tag in Markdown.  

### ISSUE THREAD

**Issue by tforward** [withastro/starlight#1486]
### What version of `starlight` are you using?

0.17.2

### What version of `astro` are you using?

4.2.1

### What package manager are you using?

npm

### What operating system are you using?

Windows

### What browser are you using?

Chrome

### Describe the Bug

In the following .md file:
```markdown

---
title: Letters get auto-generated in front of Frontmatter when have Markdown and HTML. 
---

## Intro to error
> <code>log()</code>
```

Adding a tag after </code> starting with closing tag for example a br tag. Causes the first letter of tag to auto-generate at the top for the frontmatter like this:

```markdown
b---
title: Letters get auto-generated in front of Frontmatter when have Markdown and HTML. 
---

## Intro to error
> <code>log()</code> </br>
```

And throws this error:
```
InvalidContentEntryFrontmatterError
Content entry frontmatter does not match schema.
docs → guides/getting-started.md frontmatter does not match collection schema.
title: Required
```
If delete the "b" it works as expected. I suspect it may have something to due with how tags are being auto-closed?

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-wsxppx?file=README.md

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by HiDeoo** [comment]
Thanks for your report.

Just to clarify as I'm not sure I totally understand the issue, the invalid syntax with the `b---` is the result of an automatic addition in your text editor/IDE, or something else?

**Comment by tforward** [comment]
Thank you, yes was an vscode extension causing this.

**Comment by tforward** [comment]
closed

**Comment by HiDeoo** [comment]
Glad you got it figured out, thanks for taking the time to follow up.
