### ISSUE TITLE
Select options are not centrally aligned

### ISSUE THREAD

**Issue by jermanuts** [withastro/starlight#1552]
### What version of `starlight` are you using?

0.19.1

### What version of `astro` are you using?

4.4.4

### What package manager are you using?

pnpm

### What operating system are you using?

Windows

### What browser are you using?

Brave

### Describe the Bug

This is how they look

![image](https://github.com/withastro/starlight/assets/109705802/45429142-9bfa-4674-80af-8c39ecf0ff4c)

They should look like that

![image](https://github.com/withastro/starlight/assets/109705802/747fb5f9-e41f-4ea4-9d58-14966952e5fb)
---

Same with the language selection box

![image](https://github.com/withastro/starlight/assets/109705802/565c5bcb-7448-4f18-bb16-f7d5e4d83fe1)
![image](https://github.com/withastro/starlight/assets/109705802/3c6b6d39-c4c5-491b-abb0-c0677331c989)

### Link to Minimal Reproducible Example

https://github.com/withastro/starlight

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by at-the-vr** [comment]
this feels like a subjective opinion and less of a bug (both look fine to me). Could you share a concrete proof in form of a reference from MDN or a trusted article that your suggestions are applicable?

**Comment by rgilsimoes** [comment]
I would agree with a little bit more margin to the left side of the label icon.
That's used by Material UI for example:
https://m2.material.io/components/menus#exposed-dropdown-menu

Here's my take on the subject:
![image](https://github.com/withastro/starlight/assets/20357414/31919b91-712c-4585-a3dc-d1e74971de43)
![image](https://github.com/withastro/starlight/assets/20357414/1406f62a-af9f-4ff0-ac4c-d2896a4c3882)
![image](https://github.com/withastro/starlight/assets/20357414/673c57e0-d674-4a81-954b-36e83a917fe1)

Let me know if this ok and I can submit it.

**Comment by delucis** [comment]
@rgilsimoes are you still up for submitting a PR? If your changes keep the current unfocused styles and only move the outline slightly, that seems great to me!

**Comment by rgilsimoes** [comment]
> @rgilsimoes are you still up for submitting a PR? If your changes keep the current unfocused styles and only move the outline slightly, that seems great to me!

Will do, got it stashed!
