### ISSUE TITLE
.sl-markdown-content adds unnecessary margin

### ISSUE THREAD

**Issue by zkmark** [withastro/starlight#1681]
### What version of `starlight` are you using?

0.21.2

### What version of `astro` are you using?

4.3.5

### What package manager are you using?

npm

### What operating system are you using?

Windows

### What browser are you using?

Chrome

### Describe the Bug

Unnecessary margin is being added to all elements I want to document except the first element

```
.sl-markdown-content :not(a, strong, em, del, span, input, code) + :not(a, strong, em, del, span, input, code, :where(.not-content *)){
      margin-top: 1rem;
}
```

Try to fix it by changing the margin to 0, but now classes like tailwind's mt-4 don't work

```
.sl-markdown-content :not(a, strong, em, del, span, input, code) + :not(a, strong, em, del, span, input, code, :where(.not-content *) ){
   margin-top: 0;
}
```

![margins astro](https://github.com/withastro/starlight/assets/10190162/3e7aed74-d3bd-4181-a34b-ddcf13faffd0)

### Link to Minimal Reproducible Example

https://stackblitz.com/github/withastro/starlight/tree/main/examples/basics?file=src%2Fcontent%2Fdocs%2Fcomponents%2Fbuttons.mdx

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by HiDeoo** [comment]
Thanks for your report.

Starlight applies default styling to all content, for example the margin you mentioned. If these styles conflict with your content’s appearance, you can use the [`not-content`](https://starlight.astro.build/guides/components/#compatibility-with-starlights-styles) class on your content to disable these styles.

For example, with the following code:

```md
<div class="buttons">
  <button>Button 1</button>
  <button>Button 2</button>
  <button>Button 3</button>
  <button>Button 4</button>
</div>
```

The following content is rendered with the top margin clearly visible:

<img width="672" alt="SCR-20240327-pyit" src="https://github.com/withastro/starlight/assets/494699/ece71e5b-07cf-4298-9679-717603fd4ce5">

Updating the code to the following will remove the margin:

```md
<div class="buttons not-content">
  <button>Button 1</button>
  <button>Button 2</button>
  <button>Button 3</button>
  <button>Button 4</button>
</div>
```

<img width="668" alt="SCR-20240327-pykr" src="https://github.com/withastro/starlight/assets/494699/65a3b136-0804-49d5-827a-220979b9f53c">

**Comment by delucis** [comment]
Thank you for the issue @zkmark! We intentionally apply those margins to space elements inside page content. We try to apply this in a way that is resilient to different kinds of content, but inevitably there are some cases where the margins don’t make sense.

As @HiDeoo shared, the `not-content` class is designed exactly for this situation.

**Comment by usrme** [comment]
I'm running into the same issue, but with Markdown codeblocks. I upgraded from 0.11.1 to 0.23.1, which at the time didn't rely on Expressive Code. Here's an image of what it looks like:

![Screenshot 2024-05-27 at 09 24 46](https://github.com/withastro/starlight/assets/5902545/671e220a-f480-4a5b-81da-7e2ff5cdb3ef)

The exact same CSS rule is being triggered for each of the lines in the code. Disabling line numbers has no effect.

**Comment by HiDeoo** [comment]
> I'm running into the same issue, but with Markdown codeblocks. I upgraded from 0.11.1 to 0.23.1, which at the time didn't rely on Expressive Code. Here's an image of what it looks like:
> 

Do you happen to have `astro-expressive-code` in your `astro.config.mjs` file `integrations` list? If so, you should be able to remove it entirely as Expressive Code is now part of Starlight and have the issue fixed.

**Comment by usrme** [comment]
Right you are and removing that fixed it, but if I still want to configure Expressive Code for the Astro website that I have under the same `astro.config.mjs`? Removing that broke styling on my main page. If it's of any help, then my site is [here](https://github.com/usrme/website).

**Comment by reynaldichernando** [comment]
I'm having the same issue as @usrme , i have a main website, and a documentation website on a subpath with starlight.
having astro-expressive-code installed messes up styling in starlight, while having it uninstalled, removed existing styling in my main website
is there a way to make it work for both?

**Comment by reynaldichernando** [comment]
Actually nevermind folks, turns out I was able to make `astro-expressive-code` works for both normal Astro site and the Starlight subpath.

For the future readers, simply uninstall your `astro-expressive-code`, and move the `expressiveCode` config from root, to Starlight.

This way the style applies to both the Astro and Starlight site.

This might not be the "proper" solution, but it works.

```
export default defineConfig({
  ...
  integrations: [
    ...
    starlight({
      title: "Starlight Page",
      ...
      expressiveCode: {
        themes: ["dark-plus"]
      }
    }),
  ],
});

```
