### ISSUE TITLE
How can we integrate kroki,mermaid diagrams in starlight

### ISSUE THREAD

**Issue by AjayKuruvath** [withastro/starlight#1682]
### What version of `starlight` are you using?

0.21.2

### What version of `astro` are you using?

4.5.9

### What package manager are you using?

pnpm

### What operating system are you using?

Linux

### What browser are you using?

Chrome

### Describe the Bug

How can we integrate `kroki,mermaid diagrams` in starlight.

We have tried by adding some packages, but it is not working and gets displayed as plain text.

### Link to Minimal Reproducible Example

.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by HiDeoo** [comment]
Thanks for your report.

Mermaid support is something that has been discussed in this specific [discussion](https://github.com/withastro/starlight/discussions/1259#discussioncomment-8515492) with various opinions, alternatives and suggestions.

I'd like to also specific highlight this [post](https://github.com/withastro/starlight/discussions/1259#discussioncomment-8515492) from the same discussion which is a step-by-step guide on how to integrate Mermaid diagrams in Starlight using [`rehype-mermaid`](https://github.com/withastro/starlight/discussions/1259#discussioncomment-8515492).

Considering the above, I'm closing this issue and if you have any further questions or need help, feel free to ask in this discussion or even join the `#starlight` channel in the [Astro Discord](https://astro.build/chat/).
