### ISSUE TITLE
Local Typescript files are not working

### ISSUE THREAD

**Issue by jorenbroekema** [withastro/starlight#1704]
### What version of `starlight` are you using?

0.21.2

### What version of `astro` are you using?

4.5.10

### What package manager are you using?

npm

### What operating system are you using?

Linux Ubuntu 20 LTS

### What browser are you using?

Chrome

### Describe the Bug

It is not possible to include Typescript files into the head of starlight projects.

I've tried quite a few methods:

```js
{
  integrations: [
    starlight({
      head: [
        {
          tag: 'script',
          content: `import '/src/load-playground.ts';`,
        },
      ],
    })
  ]
}
```

The above complains about not allowing to use import statements because it's not a module, however in the astro docs https://docs.astro.build/en/guides/client-side-scripts/#script-processing it clearly says that imports to local files should be working regardless of the missing type="module"

I also tried:
```js
{
  integrations: [
    starlight({
      head: [
        {
          tag: 'script',
          attrs: {
            type: 'module',
            src: '/src/load-playground.ts',
          },
        },
      ],
    })
  ]
}
```
Which is working locally when running `astro dev`, but the script isn't processed/bundled at all when running `astro build` and `astro preview`, so when deploying my site, it's not working.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-gw67mn?file=astro.config.mjs,src%2Fload-playground.ts

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Fryuni** [comment]
Hey @jorenbroekema! Thanks for the report.

The script processing done by Astro applies only to `<script>` tags present directly in the source code of a `.astro` file. Those scripts are extracted statically to be processed.

Scripts added programmatically, like the case of Starlight generating the script tags based on a configuration object, are all rendered inline with no post-processing. The same as if they had the `is:inline` directive.

You can see [here](https://docs.astro.build/en/reference/directives-reference/#isinline) in the Astro Docs for the `is:inline` in the caution block that it is implied when _any_ attribute other than `src` is used. That includes the `set:html` used by Starlight to create the element dynamically.

---

Considering that, this should probably be highlighted in the docs for the [`head`](https://starlight.astro.build/reference/configuration/#head) in Starlight's own docs.

**Comment by jorenbroekema** [comment]
Hey, that makes sense, wasn't sure how the script was added, thanks for telling me it's using `set:html`, now it makes sense why the script processing doesn't apply to it.

I guess using [component overrides](https://starlight.astro.build/guides/overriding-components/) is a good workaround, in `components/Head.astro`:

```astro
---
import type { Props } from '@astrojs/starlight/props';
import Default from '@astrojs/starlight/components/Header.astro';
---

<!-- Re-use the default Head component as-is. -->
<Default {...Astro.props}><slot /></Default>
<!-- Import my custom script. -->
<script src="../path/to/script.ts"></script>
```

I can't really think of a way that would be more intuitive than that, so feel free to label this bug report as a documentation improvement!

**Comment by delucis** [comment]
Thank you for the issue @jorenbroekema! As @Fryuni mentioned, this is working as expected. Would be happy to look at a PR clarifying this in the docs if anyone has an idea how to improve those.
