### ISSUE TITLE
Tables in Asides

### ISSUE THREAD

**Issue by torn4dom4n** [withastro/starlight#1725]
### What version of `starlight` are you using?

v0.21.4

### What version of `astro` are you using?

4.5.16

### What package manager are you using?

bun

### What operating system are you using?

Windows

### What browser are you using?

Edge

### Describe the Bug

The background of table is not harmonious when I add it to an aside component.

light mode:
![image](https://github.com/withastro/starlight/assets/27698189/14eb825e-89f7-444d-a194-9eef2cd8d1ee)

dark mode:
![image](https://github.com/withastro/starlight/assets/27698189/afa683c0-919c-4f25-b46d-4c6dfa505013)

The source code:

```md
:::note

|     | Low       | Medium     | High       |
| --- | --------- | ---------- | ---------- |
| AFI | 25-30 cm  | 30.1-35 cm | > 35 cm    |
| SDP | 8-11.9 cm | 12-15.9 cm | &ge; 16 cm |

:::
```

### Link to Minimal Reproducible Example

none

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by delucis** [comment]
Thanks for the issue @torn4dom4n! I agree this is not ideal styling. It might be possible to override some colours for tables inside asides. Would be curious to see anyone’s ideas for how best to solve this!

**Comment by SnowDingo** [comment]
Dear @torn4dom4n.

I am currently working on making PR that resolves this issue and here is what it currently looks like in my local environment.
Are there any changes to the styling you want to make? If not, I will submit my code as a PR so it can be added to the Starlight package.

<img width="481" alt="スクリーンショット 2024-04-15 21 29 24" src="https://github.com/withastro/starlight/assets/101443426/11f60d32-dfce-4cc6-bc8d-4b06feeec59a">
<img width="398" alt="スクリーンショット 2024-04-15 21 33 30" src="https://github.com/withastro/starlight/assets/101443426/c536e2c0-0afe-43e6-81a7-408eb3c3147e">


Thank you

Snowdingo

**Comment by SnowDingo** [comment]
@torn4dom4n, thank you for your suggestion on the styling of the table.
Would it be possible for you to expand more on the background between the rows of parts?
I got a bit confused about what you wanted to say.

Thank you
@SnowDingo

**Comment by SnowDingo** [comment]
Dear, @torn4dom4n.
Sorry for replying late. I figured out how to change the background colors of tables like the GitHub table.
What do you think about this new version?

Thank you

Best Regards,
Snowdingo

<img width="785" alt="スクリーンショット 2024-04-26 14 54 38" src="https://github.com/withastro/starlight/assets/101443426/2e75f32f-8d78-428a-a3b3-0930553eaaf5">

**Comment by SnowDingo** [comment]
Dear @torn4dom4n.

Thank you for your suggestion about the coloring of the table.
I changed the colors so that it has less contrast with each other.
It is not the official Starlight color pallet so it doesn't look good on both light & dark themes.
What do you think about this?


<img width="742" alt="スクリーンショット 2024-04-27 10 08 45" src="https://github.com/withastro/starlight/assets/101443426/482d40a0-7184-4c3b-a8e1-1702089bc0c4">

<img width="637" alt="スクリーンショット 2024-04-27 10 14 50" src="https://github.com/withastro/starlight/assets/101443426/6eee8cb0-83d3-4fab-b39b-8468ae0f4a50">


Sincerely,
Snowdingo.

**Comment by SnowDingo** [comment]
Dear @torn4dom4n.

Thank you for your suggestion.
I adjusted the alpha property so it looks better in dark mode.
What do you think of the new coloring of tables in the aside element?

<img width="966" alt="スクリーンショット 2024-04-28 8 02 25" src="https://github.com/withastro/starlight/assets/101443426/d3bf4b5d-2e29-405f-9b0f-efd5ef36452f">
<img width="392" alt="スクリーンショット 2024-04-28 8 04 12" src="https://github.com/withastro/starlight/assets/101443426/44ea3107-2946-4284-80b7-a1d310c6aa66">

Best regards,
SnowDingo

**Comment by SnowDingo** [comment]
@torn4dom4n 

Before I create a PR that resolves this issue, would you mind reviewing the rest of the coloring for the other types of Aside elements?

<img width="412" alt="スクリーンショット 2024-04-29 17 20 37" src="https://github.com/withastro/starlight/assets/101443426/454b9260-89d9-4705-8903-34cf2323ae44">

<img width="415" alt="スクリーンショット 2024-04-29 17 20 48" src="https://github.com/withastro/starlight/assets/101443426/b25df039-14cd-4591-b8b5-1f38648c47d6">

<img width="445" alt="スクリーンショット 2024-04-29 17 21 11" src="https://github.com/withastro/starlight/assets/101443426/69af7ed1-d220-47cc-871a-91a3d69f0b94">

<img width="423" alt="スクリーンショット 2024-04-29 17 21 22" src="https://github.com/withastro/starlight/assets/101443426/982c8081-b804-4346-ac32-b2ec9892f1fa">

<img width="436" alt="スクリーンショット 2024-04-29 17 21 54" src="https://github.com/withastro/starlight/assets/101443426/ce3e21bf-160e-45f8-8823-39b28d2d34e4">

<img width="449" alt="スクリーンショット 2024-04-29 17 22 17" src="https://github.com/withastro/starlight/assets/101443426/bd081819-e1a8-40b9-83d5-5b3a53955063">


Best Regards,
Snowdingo

**Comment by SnowDingo** [comment]
Dear @torn4dom4n.
I created a PR that resolves this issue.

https://github.com/withastro/starlight/pull/1796

Thank you for contributing to Astro Starlight!

Sincerely,
Snowdingo
