### ISSUE TITLE
Order of Generated Headings are Invalid

### ISSUE THREAD

**Issue by flowforfrank** [withastro/starlight#1749]
### What version of `starlight` are you using?

0.21.5

### What version of `astro` are you using?

4.3.5

### What package manager are you using?

npm

### What operating system are you using?

Windows

### What browser are you using?

Chrome

### Describe the Bug

The generated heading elements in the documentation page are not in sequentially descending order which can negatively affect technical SEO. This is also verifiable on the official page of Starlight:

![headings](https://github.com/withastro/starlight/assets/7797154/26a7b93e-061a-4525-942c-f7552e138f3d)

In the DOM, the `aside` element comes before the main pane, which means the `h2` will proceed to the `h1`. Structurally the `aside` should be after the `main-pane` element which also fixes the order of headings.

![order](https://github.com/withastro/starlight/assets/7797154/9a33aa86-a2d4-4ecc-ac59-6fbe6792eda5)

For a semantically correct document, the headings should follow a sequentially descending order, where headings levels are not skipped, eg. an `h1` is always followed by an `h2`, and not an `h3`.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-starlight-ygxksj

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by delucis** [comment]
Hi @flowforfrank! This is not strictly speaking true when using other semantic elements on the page. Generally the recommendation is for a single `<h1>` on the page, and for headings _within_ a semantic element (like `<main>`, `<aside>` etc.) to follow the sequentially descending order you described. This is the shape Starlight follows and the `<h2>` for the table of contents outside of `<main>` is valid and should not call any issues as far as I am aware.
