### ISSUE TITLE
Tables may cause horizontal overflow

### ISSUE THREAD

**Issue by rviscomi** [withastro/starlight#176]
### What version of `starlight` are you using?

0.1.2

### What version of `astro` are you using?

2.5.0

### What package manager are you using?

npm

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

Wide tables create horizontal overflow where the entire body is widened, causing content like the search/nav buttons to be rendered out of the viewport.

For example, https://har.fyi/reference/tables/pages/ with mobile emulation:

<img width="408" alt="image" src="https://github.com/withastro/starlight/assets/1120896/1a5b34ba-5da9-4cbd-a14a-ad857a3f65bb">

<img width="407" alt="image" src="https://github.com/withastro/starlight/assets/1120896/fe841756-ba8b-4557-9418-c10a61e6329f">

The offending table is under the [Schema](https://har.fyi/reference/tables/pages/#schema) heading.

FWIW I've also seen this affect the desktop layout for a really wide table (not used in prod anymore)

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by delucis** [comment]
Ah, good catch — didn’t test with any larger tables.

A PR fixing this would be definitely welcome. The minimal table styles we currently apply are here:

https://github.com/withastro/starlight/blob/3b3fc437ee4d04d7dde3135576a02d2d347cd80a/packages/starlight/components/MarkdownContent.astro#L97-L107
