### ISSUE TITLE
Badge styles break when refreshing with sidebar entry active

### ISSUE THREAD

**Issue by kevin8181** [withastro/starlight#1764]
### What version of `starlight` are you using?

0.21.5

### What version of `astro` are you using?

4.3.5

### What package manager are you using?

npm

### What operating system are you using?

Linux

### What browser are you using?

Firefox and chromium

### Describe the Bug

- using tailwind set up according to the docs
- Create a page that displays a badge in the sidebar
- Go to the page
- Refresh
- The badge style is broken
- Navigate to a different page without a badge
- Refresh
- The badge styling is fixed

live demo https://starlight-lovat.vercel.app/

### Link to Minimal Reproducible Example

https://github.com/tgoHQ/knowledgebase

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by HiDeoo** [comment]
Thanks for your report. I think in this case there are multiple issues. 

First, in your steps, you mention styles being broken in step 5 after a refresh. I think the style are actually broken after the step 3:

<img width="266" alt="SCR-20240418-jtbi" src="https://github.com/withastro/starlight/assets/494699/a058beb8-9f00-4951-a115-fc273912f464">

The badge style is not updated and it should be to match Starlight default behavior when navigating to a page with a badge and get an outlined style:

<img width="274" alt="SCR-20240418-jtmk" src="https://github.com/withastro/starlight/assets/494699/ce4e539b-3793-4409-865c-e8c201f1b7be">

This first issue seems to be related to view transitions and the usage of `astro-vtbot` so maybe an issue should be opened in the Bag of Tricks repository.
Commenting out the component override using `astro-vtbot` in the Astro configuration seems to fix this issue and navigation to a page with a badge will correctly display the outlined style.

<img width="266" alt="image" src="https://github.com/withastro/starlight/assets/494699/3bd7b136-d3cc-48b1-bcd5-1e0e4edfac66">

However, I think there is a second issue with the outlined badge style with Tailwind as we can see in the 2 previous screenshots. The badge outline with Tailwind is way thicker than the default Starlight one.

The issue in this case seems to be that we internally use the `.outline` CSS class to apply the outline style to the badge. However, this class is also [used in Tailwind](https://tailwindcss.com/docs/outline-style) to apply `outline-style: solid;`.

Without this extra style, the style looks closer to the default Starlight one:

<img width="263" alt="image" src="https://github.com/withastro/starlight/assets/494699/a7bec6e2-ee93-4a3d-bb00-27aa31cf4690">

**Comment by martrapp** [comment]
Hi @kevin8181, I'm sorry that `astro-vtbot` is the source of trouble here! 
Thank you very much, @HiDeoo, for the initial analyzes and opening an issue.
I will look into that now!

**Comment by HiDeoo** [comment]
> I'm sorry that `astro-vtbot` is the source of trouble here!

To clarify, I think this issue also spotted a Starlight issue too so definitely not just a potential `astro-vtbot` issue. Thanks a lot for jumping in to help! 🙌

**Comment by martrapp** [comment]
Haha, I didn't take it that way either! I'm happy when we can help fix bugs. And it's even more motivating when you know that people are using the things you make, so I don't want to keep you waiting too long ;-)

**Comment by martrapp** [comment]
Here is my preliminary analysis:
I assumed, Starlight's styling of active sidebar entries solely depends on `aria-current="page"`.
This is not true. As HiDeoo already wrote, badges on the current page get an `outline` class instead of the variant class (.note, .danger, ...).

The Starlight support of `astro-vtbot` currently only handles `aria-current="page"`, but it doesn't a) replace the variant class with the `outline` class when navigating to a page with a badge. And it 
b) doesn't replace `.outline` with whatever variant got lost when `.outline` was set ;-) when navigating away from the page.

The fix for the bag would be to just do a) and b). But if Starlight changes the content class due to the overlap with tailwind, it would be good to know what the future Starlight solution looks like.

**Comment by martrapp** [comment]
Of course, I would also be happy if Starlight would not set the `.outline` class at all, keep the variant class on all entries and overrides the current page badge like this:
```
<style is:global>
  [aria-current="page"] .sl-badge {
    --sl-color-bg-badge: transparent;
    --sl-color-border-badge: currentColor;
    color: inherit;
}
</style>
```
But I understand if there are concerns, as `<Badge>` as the inner component now makes assumptions about its use in the sidebar.

**Comment by martrapp** [comment]
@hippotastic can't someone ;-) add Expressive Code to GitHub, PLEASE!

**Comment by martrapp** [comment]
> Of course, I would also be happy if Starlight would not set the `.outline` class at all, keep the variant class on all entries and overrides the current page badge styling

If you want to go that route, I offer to do a PR for it.

**Comment by HiDeoo** [comment]
> Edited: After having a second look I would say it would fit very well to the other `aria-current='page'` styling in `SidebarSublist.astro`, there even without `is:global`

This could indeed be a solution to use a selector like `[aria-current='page'] :global(.sl-badge)` but we would first need to confirm that #1530 does not expose the `outline` variant. I edited the description of #1765 to mention your idea as an alternative solution until we decide which one to go with. :thumbsup:

**Comment by martrapp** [comment]
Saw that, thank you! Love #1530, @kevinzunigacuellar already did all the work. That PR would reestablish my earlier assumption that sidebar current entry styling only depends on `aria-current='page'` 😀

**Comment by HiDeoo** [comment]
I found a thread mentioning that the `outline` variant is meant to be internal and not exposed even with the `<Badges>` component so I closed #1765 and #1530 will indeed be the proper fix to both issues 🎉

**Comment by HiDeoo** [comment]
Starlight version [`0.24.0`](<https://github.com/withastro/starlight/releases/tag/%40astrojs%2Fstarlight%400.24.0>) just got released today and includes #1530.

If I'm not mistaken this issue should now be resolved? Not sure there is even anything extra to do on the `astro-vtbot` side, right? cc @martrapp

**Comment by martrapp** [comment]
Hi @HiDeoo!
I closed https://github.com/martrapp/astro-vtbot/issues/77 as the badges in deed work now as expected, see https://events-3bg.pages.dev/jotter/history-of-changes/. Updating to the current starlight version was the only change required.

**Comment by delucis** [comment]
Lovely stuff! Will close this issue then. Feel free to reopen or post a new issue if you spot anything we need to address 🙌
