### ISSUE TITLE
pagefind: disable indexing for file trees and codeblocks

### ISSUE THREAD

**Issue by kevinzunigacuellar** [withastro/starlight#181]
### What version of `starlight` are you using?

0.1.2

### What version of `astro` are you using?

2.5.0

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

When searching for file names or codeblocks the text show in the excerpt is not very clear.

|  File Tree | Codeblocks  |
|---|---|
| <img width="653" alt="image" src="https://github.com/withastro/starlight/assets/46791833/8f412020-09f0-4e49-b7df-e4d5c486e122">  |  <img width="650" alt="image" src="https://github.com/withastro/starlight/assets/46791833/66b09cfa-162e-4502-bc51-4dbc2da5b3ad"> |

Maybe it would be a good idea to ignore it? 

Side note: Inline code works perfectly 💜

### Participation

- [x] I am willing to submit a pull request for this issue.

**Comment by delucis** [comment]
Great point! Thanks @kevinzunigacuellar.

Funnily enough Algolia recommends not indexing code samples by default for their DocSearch too. This would be doable by injecting some attributes Pagefind uses into tags to be ignored.

But maybe there are ways to improve the preview snippets instead as well. 🤔

**Comment by kevinzunigacuellar** [comment]
I think ignoring might be the best bet here because usually users when searching for code specific stuff they would like to locate the reference section instead of another section that happens to use it that same code keyword.

**Comment by delucis** [comment]
Thanks again for this Kevin! I think we landed on only disabling indexing for file trees for now — code blocks can sometimes be useful and we even explicitly _enabled_ indexing for code blocks on the Astro docs site previously. I think we can close this now that we merged #187.
