### ISSUE TITLE
Sidebar group arrow not turning in subgroups

### ISSUE THREAD

**Issue by nikcio** [withastro/starlight#182]
### What version of `starlight` are you using?

0.1.2

### What version of `astro` are you using?

2.5.0

### What package manager are you using?

pnpm

### What operating system are you using?

Windows

### What browser are you using?

Chrome, Firefox

### Describe the Bug

When you add a subgroup to the sidebar the arrow will not turn when clicked like the normal groups:

`astro.config.js` example:

```js
// https://astro.build/config
export default defineConfig({
  integrations: [
    starlight({
      title: 'My title',
      sidebar: [
        {
          label: 'Fundamentals',
          items: [
            { label: 'Getting started', link: 'v4/fundamentals/getting-started/' },
            {
              label: 'Querying',
              items: [
                { label: 'Content', link: 'v4/fundamentals/querying/content/' },
              ]
            },
          ]
        },
      ],
    }),
  ],
});
```

Open "Fundamentals":
![image](https://github.com/withastro/starlight/assets/24605285/2673fccf-9281-45c7-80f5-4b1437c2ad82)

Closed "Fundamentals":
![image](https://github.com/withastro/starlight/assets/24605285/c181c5db-aab4-487a-a33f-6e03dce81eb7)

☝️ This is expected.

Closed "Querying"
![image](https://github.com/withastro/starlight/assets/24605285/29a625ff-e740-458c-8aa1-01730788048b)

☝️ This is not expected. (The arrow is still pointing down.)

---

Also, I'm not sure this is considered a bug but to me, it's quite difficult to differentiate when a group is a sub-group or its own group. See this example:
![image](https://github.com/withastro/starlight/assets/24605285/b2bd5069-64f8-4322-956c-d75a6a7e47a0)

The red is its own group and the blue is a sub-group. There's no difference in the boldness of the title and the empty space for the next group. (Or at least so little that it's hard to notice.)

For reference here's a site using GitBook where I've done the same exercise ([Source](https://docs.umbraco.com/umbraco-cms/)):
![image](https://github.com/withastro/starlight/assets/24605285/1653977b-caf8-472f-8a76-30f7d723235e)

Let me know if that makes sense and if I should move this to its separate issue 😄 

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by delucis** [comment]
Thanks for the report @nikcio! I can already see the fix for the arrow not responding correctly — that should be quick.

And yes, we’ll look at adding some indentation on sub groups to make those clearer. 👍
