### ISSUE TITLE
[regression] Custom translation not working when using a single non-root locale on MacOS

### ISSUE THREAD

**Issue by Fryuni** [withastro/starlight#1849]
### What version of `starlight` are you using?

main

### What version of `astro` are you using?

4.8.2

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### What browser are you using?

N/A

### Describe the Bug

Custom translations are not being applied when using a single non-root locale on MacOS. Calls to `useTranslation` result in the default translations being used.

### Link to Minimal Reproducible Example

https://github.com/withastro/starlight/blob/0e4d04eaade69d6e5e35b1cec3d94063ee0c27ca/packages/starlight/__tests__/i18n-non-root-single-locale/translations.test.ts#L11-L23

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Fryuni** [comment]
I can send a PR, just don't have time to investigate this in the near future. If someone else wants to do it before me, be my guest :)

**Comment by delucis** [comment]
Coming back to this @Fryuni, did you say you also tested on other operating systems? And this is macOS-specific?

I’m not sure I follow how the test you linked to reproduces this — it’s passing for me? Or are you saying the test is wrong?

**Comment by Fryuni** [comment]
Tried to run again and it is no longer breaking. Went back to what I was doing in another branch and it failed there. Switching to main again continues to fail, so it seems just pnpm is getting confused with the install from both branches.

Cleaning the repo before installing dependencies makes it work.

Sorry guys, false alarm. Weird that it only happens on Mac tho

**Comment by delucis** [comment]
Oh, cool! Well, thanks for checking again.

Fingers crossed this macghOSt doesn’t come back 👻
