### ISSUE TITLE
Summary's marker have not be hidden

### ISSUE THREAD

**Issue by subframe7536** [withastro/starlight#1865]
### What version of `starlight` are you using?

latest

### What version of `astro` are you using?

latest

### What package manager are you using?

pnpm

### What operating system are you using?

Windows

### What browser are you using?

Chrome

### Describe the Bug

![image](https://github.com/withastro/starlight/assets/78338239/0999e914-9e6b-4bb7-9ca2-f074c96a76b6)

Using `summary::marker` with `display: none` to hide is ineffective. Should use with `list-style: none` in `summary`

### Link to Minimal Reproducible Example

https://stackblitz.com/github/withastro/starlight/tree/main/examples/basics

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by HiDeoo** [comment]
Thanks for your report.

Indeed, `<details>` and `<summary>` elements are not styled at all at the moment but this should be fixed by #1735.

**Comment by subframe7536** [comment]
Sure, I add a comment in your PR

**Comment by HiDeoo** [comment]
Just tried using Chrome on a Windows machine and I cannot repro the issue using your [repro link](stackblitz.com/github/withastro/starlight/tree/main/examples/basics), the [Starlight documentation](https://starlight.astro.build/getting-started/) or the [preview page](https://starlight-git-fork-hideoo-hd-style-details-astrodotbuild.vercel.app/reference/details/) from the linked PR.

In the screenshot you provided, is this from a local reproduction? Is this the Starlight online documentation? Is this a sidebar issue only?

Regarding the [comment](https://github.com/withastro/starlight/pull/1735/files#r1601047829) you left, do you have any source or reference for such change?

**Comment by subframe7536** [comment]
repro: ![recording](https://github.com/withastro/starlight/assets/78338239/e067afb7-04fa-40cd-aacb-0a77c6cf72ad)

**Comment by subframe7536** [comment]
fix: ![recording](https://github.com/withastro/starlight/assets/78338239/fe1bc8d9-4eef-4464-804f-9d66048ecdd5)

**Comment by subframe7536** [comment]
reference: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details#customizing_the_disclosure_widget

**Comment by HiDeoo** [comment]
Could you have any extension (maybe something related to styles, as I see you may be getting a custom font) that could add such a style to the element. Would you be able to test in a private window maybe with no extension enabled?

For example, I personally do not get that inline style on the summary elements in the Starlight documentation.

<img width="388" alt="image" src="https://github.com/withastro/starlight/assets/494699/5903d650-8c61-4719-8d0f-e56e9cb25a94">
<img width="107" alt="image" src="https://github.com/withastro/starlight/assets/494699/6963a502-39e9-41fc-8dc0-aa2c77572659">

**Comment by subframe7536** [comment]
You are right. There is a global CSS injected by one of userscript in violent monkey, which is reference from tailwind css reset. Disable that and everything works
