### ISSUE TITLE
Step component items all render as `0`

### ISSUE THREAD

**Issue by polarathene** [withastro/starlight#1953]
### What version of `starlight` are you using?

4.9.2

### What version of `astro` are you using?

0.23.3

### What package manager are you using?

N/A

### What operating system are you using?

Windows

### What browser are you using?

Chrome

### Describe the Bug

While [viewing the docs](https://starlight.astro.build/guides/components/#steps), I noticed the step component isn't rendering correctly:

> ![image](https://github.com/withastro/starlight/assets/5098581/c0d59926-cd1f-497c-ba3a-4cbe32e8b35d)

---

I've not tried to reproduce this, but it is apparent elsewhere in the official docs linked when that component is used.

### Link to Minimal Reproducible Example

https://github.com/withastro/starlight/blob/4c040329bdee2caf1bd6a49d9be5d143231b8e83/docs/src/content/docs/guides/components.mdx?plain=1#L383-L397

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by HiDeoo** [comment]
Thanks for your report 🙌 

This is an issue due to a [change](https://github.com/withastro/starlight/pull/1948) that I recently submitted. I have opened a [PR](https://github.com/withastro/starlight/pull/1955) to revert the change until a better solution is found.

**Comment by delucis** [comment]
Thanks for reporting! Should be fixed in v0.23.4
