### ISSUE TITLE
Last chapter on certain pages in the Table of Contents (TOC) won't be highlighted on a maximized window at 1920x1080

### ISSUE THREAD

**Issue by some1chan** [withastro/starlight#1954]
### What version of `starlight` are you using?

0.23.1 (not latest!)

### What version of `astro` are you using?

4.8.6 (not latest!)

### What package manager are you using?

pnpm

### What operating system are you using?

Windows

### What browser are you using?

Firefox

### Describe the Bug

When scrolling to the bottom of the page on a maximized window, the last chapter will never be highlighted.

To reproduce:

1. Go to the link below on a maximized window (I'm using a 1080p monitor, which likely matters).
2. Scroll down the page

From here, the "Developer Focused" text not being the accent blue, and staying the default gray. However, the previous "Easy to use" header above it is highlighted.

This can be mitigated by having the last chapter have more content (ex. https://docs.astro.build/en/guides/client-side-scripts/), but this isn't a realistic solution.

Note: although the `starlight` and `astro` versions aren't updated in [withastro/docs](https://github.com/withastro/docs), I've been able to reproduce this by customizing `starlight-toc.ts` from the main branch into my own codebase. My codebase doesn't use `starlight` otherwise, and would otherwise be the latest version of Astro, if that matters.

### Link to Minimal Reproducible Example

https://docs.astro.build/en/concepts/why-astro/

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by delucis** [comment]
Thanks for the issue @some1chan! It might be a bit counter-intuitive, but this is actually working as expected. The sidebar highlights the heading for the section currently in the upper part of the viewport and does this consistently wherever you scroll to. This has the drawback that short sections towards the bottom of the page may never be highlighted, but in our exploration still had the most reliable and predictable UX for all other cases.
