### ISSUE TITLE
Failed to get locale informations

### ISSUE THREAD

**Issue by torn4dom4n** [withastro/starlight#1961]
### What version of `starlight` are you using?

0.24.0

### What version of `astro` are you using?

4.9.3

### What package manager are you using?

bun

### What operating system are you using?

Windows

### What browser are you using?

Chrome

### Describe the Bug

I get this bug after updating Starlight to v0.24.0

```shell
1:58:17 AM [vite] Error when evaluating SSR module /node_modules/@astrojs/starlight/utils/i18n.ts:
|- AstroUserError: Failed to get locale informations for the 'en' locale.
    at new AstroUserError (C:\Users\Windows\Documents\GitHub\AREA44\playastro\node_modules\astro\dist\core\errors\errors.js:96:9)
    at getLocaleInfo (:99:47)
    at <anonymous> (:5:48)
    at processTicksAndRejections (:12:39)

1:58:17 AM [vite] Error when evaluating SSR module /node_modules/@astrojs/starlight/integrations/shared/localeToLang.ts: failed to import "/node_modules/@astrojs/starlight/utils/i18n.ts"
|- AstroUserError: Failed to get locale informations for the 'en' locale.
    at new AstroUserError (C:\Users\Windows\Documents\GitHub\AREA44\playastro\node_modules\astro\dist\core\errors\errors.js:96:9)
    at getLocaleInfo (:99:47)
    at <anonymous> (:5:48)
    at processTicksAndRejections (:12:39)

1:58:17 AM [vite] Error when evaluating SSR module /node_modules/@astrojs/starlight/integrations/expressive-code/translations.ts: failed to import "/node_modules/@astrojs/starlight/integrations/shared/localeToLang.ts"
|- AstroUserError: Failed to get locale informations for the 'en' locale.
    at new AstroUserError (C:\Users\Windows\Documents\GitHub\AREA44\playastro\node_modules\astro\dist\core\errors\errors.js:96:9)
    at getLocaleInfo (:99:47)
    at <anonymous> (:5:48)
    at processTicksAndRejections (:12:39)

1:58:17 AM [vite] Error when evaluating SSR module /node_modules/@astrojs/starlight/integrations/expressive-code/index.ts: failed to import "/node_modules/@astrojs/starlight/integrations/expressive-code/translations.ts"
|- AstroUserError: Failed to get locale informations for the 'en' locale.
    at new AstroUserError (C:\Users\Windows\Documents\GitHub\AREA44\playastro\node_modules\astro\dist\core\errors\errors.js:96:9)
    at getLocaleInfo (:99:47)
    at <anonymous> (:5:48)
    at processTicksAndRejections (:12:39)

1:58:17 AM [vite] Error when evaluating SSR module /node_modules/@astrojs/starlight/index.ts: failed to import "/node_modules/@astrojs/starlight/integrations/expressive-code/index.ts"
|- AstroUserError: Failed to get locale informations for the 'en' locale.
    at new AstroUserError (C:\Users\Windows\Documents\GitHub\AREA44\playastro\node_modules\astro\dist\core\errors\errors.js:96:9)
    at getLocaleInfo (:99:47)
    at <anonymous> (:5:48)
    at processTicksAndRejections (:12:39)

1:58:17 AM [vite] Error when evaluating SSR module C:\Users\Windows\Documents\GitHub\AREA44\playastro\astro.config.ts: failed to import "/node_modules/@astrojs/starlight/index.ts"
|- AstroUserError: Failed to get locale informations for the 'en' locale.
    at new AstroUserError (C:\Users\Windows\Documents\GitHub\AREA44\playastro\node_modules\astro\dist\core\errors\errors.js:96:9)
    at getLocaleInfo (:99:47)
    at <anonymous> (:5:48)
    at processTicksAndRejections (:12:39)

[astro] Unable to load your Astro config

[AstroUserError] Failed to get locale informations for the 'en' locale.
  Hint:
    Make sure to provide a valid BCP-47 tags (e.g. en, ar, or zh-CN).
  Stack trace:
    at new AstroUserError (C:\Users\Windows\Documents\GitHub\AREA44\playastro\node_modules\astro\dist\core\errors\errors.js:96:9)
    at <anonymous> (:5:48)
error: script "dev" exited with code 1
```

### Link to Minimal Reproducible Example

https://github.com/AREA44/playastro/tree/bump-starlight

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by HiDeoo** [comment]
Thanks for your report.

Just tested to run the dev and prod version of the linked repo/branch with no issues on my end. I also tried on Windows and got the same result.

Would you be able to specify your Node.js version? You should be able to get that by running `bun run astro info`.

**Comment by HiDeoo** [comment]
Additional thought: could it be related to Bun or Bun version? I used `bun run dev` and `bun run build` to test your project and [`getTextInfo()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Locale/getTextInfo) was something added to Node.js in version 18 so maybe it's something related to that? What's strange is that it worked for me (I have bun 1.1.10 installed).

**Comment by HiDeoo** [comment]
I finally managed to reproduce the issue, looks like there is a [`--bun`](https://bun.sh/docs/cli/run#bun) flag to prevent Bun from respecting script shebangs and force it to run with Bun instead of Node.js.

When using that flag, I can reproduce the issue. Is this your use case?

If yes, as it's a Bun related issue (I'm assuming some parts of the `Intl` API are not supported on their end), I think the best call would be to [open an Issue on GitHub with Bun directly](https://github.com/oven-sh/bun/issues/new/choose) and in the meantime avoid using that flag until that API is available in Bun.

**Comment by Jarred-Sumner** [comment]
@HiDeoo the `textInfo` property in `Intl.Locale` is deprecated and only V8 implements it:

From https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Locale/getTextInfo:
> Note: In some versions of some browsers, this method was implemented as an accessor property called textInfo. However, because it returns a new object on each access, it is now implemented as a method to prevent the situation of locale.textInfo === locale.textInfo returning false. Check the [browser compatibility table](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Locale/getTextInfo#browser_compatibility) for details.

**Comment by HiDeoo** [comment]
> @HiDeoo the `textInfo` property in `Intl.Locale` is deprecated and only V8 implements it:

Thanks a lot for reminding me of this, super appreciated! I totally forgot about this after a while after working on the feature. Sorry for my mistake, I just opened #1987 which should fix this issue. Thanks again.

**Comment by delucis** [comment]
Fixed and released in Starlight v0.24.1 :rocket:

Thank you to everyone reporting and helping to fix!

**Comment by aleclarson** [comment]
Same error with `starlight@0.25.3` and `astro@4.13.1` on Stackblitz.

https://stackblitz.com/edit/github-w4rkes?file=package.json,astro.config.mjs&on=stackblitz

**Comment by delucis** [comment]
Thanks for the report @aleclarson, I can confirm I’m also seeing that. [Firefox doesn’t support the `getTextInfo()` API](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Locale/getTextInfo#browser_compatibility) we’re using, but in theory [our code](https://github.com/withastro/starlight/blob/4f120490e914fb308e909b97890a11bb95ae964c/packages/starlight/utils/i18n.ts#L155-L188) should handle this case 🤔

**Comment by HiDeoo** [comment]
> but in theory [our code](https://github.com/withastro/starlight/blob/4f120490e914fb308e909b97890a11bb95ae964c/packages/starlight/utils/i18n.ts#L155-L188) should handle this case 🤔

@delucis If you move the definition of `wellKnownRTL` 2 line up, above the one for `BuiltInDefaultLocale`, does it fix the error for you?

**Comment by delucis** [comment]
Let me try, it’s definitely this line that errors:
https://github.com/withastro/starlight/blob/4f120490e914fb308e909b97890a11bb95ae964c/packages/starlight/utils/i18n.ts#L187

**Comment by delucis** [comment]
> @delucis If you move the definition of `wellKnownRTL` 2 line up, above the one for `BuiltInDefaultLocale`, does it fix the error for you?

Ohhhhhhh. Yes! Makes sense. I’d totally missed that that was calling `getLocaleInfo()` before the well-known locales were defined.

**Comment by delucis** [comment]
PR to fix this: https://github.com/withastro/starlight/pull/2167
