### ISSUE TITLE
Conflicting sidebar options are silently ignored

### ISSUE THREAD

**Issue by Fryuni** [withastro/starlight#2019]
### What version of `starlight` are you using?

0.24.2

### What version of `astro` are you using?

v4.10.2

### What package manager are you using?

pnpm (indifferent for this)

### What operating system are you using?

MacOS (indifferent for this)

### What browser are you using?

Chrome (indifferent for this)

### Describe the Bug

The sidebar allows for either a link or a list of child items, not both. But if both are provided, the user is not informed that this is a problem, and the child items are simply ignored.

```ts
{
	label: 'Parent',
	link: '/parent',
	items: [
		{
			label: 'Child',
			link: '/parent/child',
		},
	],
}
```

The items won't show up on the sidebar, which might lead the user to try to find a problem within the items option.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-f4x149?file=astro.config.mjs

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by delucis** [comment]
Ah, interesting! I would have expected Zod validation to fail in this case, but maybe that requires us to use the `.strict()` option?

**Comment by delucis** [comment]
Spun up a PR for this: #2031 

Might want to discuss that and if this is strictly speaking an “issue” we want to fix, or if the fix has other impacts.
