### ISSUE TITLE
`<Steps>` Numbers out of order

### ISSUE THREAD

**Issue by OliverSpeir** [withastro/starlight#2032]
In Chrome 126 there was a change to CSS counters that has changed the way the `<Steps>` component renders.

There are a number of options for how to handle this. This issue is meant to serve as tracking of this. 

Here is the [minimal reproduction](https://codepen.io/delucis/details/wvbyGVJ) of the issue on codepen

This bug can be seen [here](https://starlight.astro.build/guides/css-and-tailwind/#add-tailwind-to-an-existing-project)
## Resources

**Here are the relevant Chromium issues/commits:**
- [Bug report of 126](https://issues.chromium.org/issues/346974104)
- [Original issue that proposed the changes to Chromium](https://issues.chromium.org/issues/40638899)
  - @delucis 's [comment on the original issue](https://issues.chromium.org/issues/40638899#comment44)
- [Merged commit to chromium attempting to fix](https://chromium-review.googlesource.com/c/chromium/src/+/5630408) 

**Here is history of how starlight attempted to handle this so far:**
- [ Attempt 1 ](https://github.com/withastro/starlight/pull/1948) which was [reverted](https://github.com/withastro/starlight/pull/1955) due to creating other problems

## Some relevant comments open for discussion:

> And we might also look at some temporary mitigation, annoying though that is — in theory we could dive into rehype or something to hard code the markers instead of using ::before and CSS counters, but obviously would love to avoid that if possible. - @delucis 

## Next steps:

1. Test fixes in Canary chromium 
2. Identify when next stable version (with the fix) will be released 
3. Decide if starlight should take action at all 
```[tasklist]
### Tasks
```

**Comment by delucis** [comment]
Thanks so much for compiling this @OliverSpeir! Super helpful 💖

**Comment by HiDeoo** [comment]
A few updates:

- Tested in latest Canary, the issue is still present.
- Created #2041 as a new attempt to fix the issue.

A demo is available [here](https://starlight-git-fork-hideoo-hd-fix-steps-cou-e30f99-astrodotbuild.vercel.app/guides/steps/) if some people want to help testing the numbering in various browsers.
