### ISSUE TITLE
When deploying to Cloudflare Pages, it was found that when the website is displayed on the mobile end, the width of the menu buttons will be modified to 100%, but the computer end will display normally

### ISSUE THREAD

**Issue by hanjiezhou** [withastro/starlight#2045]
### What version of `starlight` are you using?

0.24.3

### What version of `astro` are you using?

4.10.3

### What package manager are you using?

npm

### What operating system are you using?

linux

### What browser are you using?

chrome

### Describe the Bug

When deploying to Cloudflare Pages, it was found that when the website is displayed on the mobile end, the width of the menu buttons will be modified to 100%, but the computer end will display normally.
Mobile end error display:![image](https://github.com/withastro/starlight/assets/101302973/d71a325c-3a46-4985-ab78-e2994f803c6e)
Mobile end normlly display:
![image](https://github.com/withastro/starlight/assets/101302973/1c4ca6cf-1c8e-404a-8c65-f237ecd41c4e)
May I ask how to modify it？

### Link to Minimal Reproducible Example

https://491b1f2b.sijin-license.pages.dev/guide/#get-started

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by delucis** [comment]
Hi @hanjiezhou — thanks for the issue.

Could you share the source code for your example? There is no CSS in Starlight which sets the `button { width: 100% }`, so I’m guessing it’s something that either you are adding or is somehow being injected by something on Cloudflare Pages?

**Comment by hanjiezhou** [comment]
Thank you for your answer. I already know where the error went.
