### ISSUE TITLE
use <Steps> error 

### ISSUE THREAD

**Issue by huifer** [withastro/starlight#2057]
### What version of `starlight` are you using?

^0.24.4

### What version of `astro` are you using?

^4.10.2

### What package manager are you using?

pnpm

### What operating system are you using?

mac

### What browser are you using?

chrome

### Describe the Bug

package.json

```
{
  "name": "helpless-heliosphere",
  "type": "module",
  "version": "0.0.1",
  "scripts": {
    "dev": "astro dev",
    "start": "astro dev",
    "build": "astro check && astro build",
    "preview": "astro preview",
    "astro": "astro"
  },
  "dependencies": {
    "@astrojs/starlight": "^0.24.4",
    "astro": "^4.10.2",
    "sharp": "^0.32.5",
    "@astrojs/check": "^0.7.0",
    "typescript": "^5.5.2"
  }
}
```

mdx content :  https://github.com/withastro/starlight/blob/main/docs/src/content/docs/zh-cn/guides/overriding-components.mdx

![image](https://github.com/withastro/starlight/assets/26766909/8c61364e-28cf-40fe-ab54-a415f8694a18)

### Link to Minimal Reproducible Example

https://github.com/huifer/zen-huifer

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by HiDeoo** [comment]
> Oh no ，After copying with IDEA, there was a format change, and once it changed, it could not be recognized and processed properly。

Thanks for the clarification, I was just about to post that I could not replicate the issue.

Indeed, the `<Steps>` component is based on Markdown ordered lists and the content should follow the rule for [adding elements in list](https://www.markdownguide.org/basic-syntax/#adding-elements-in-lists). 
In this case, if your IDE is the one reformatting the content in an invalid format not matching a single ordered list, maybe  its configuration can be tweaked or maybe the specific feature can be disabled in your IDE?

**Comment by huifer** [comment]
> > Oh no ，After copying with IDEA, there was a format change, and once it changed, it could not be recognized and processed properly。
> 
> Thanks for the clarification, I was just about to post that I could not replicate the issue.
> 
> Indeed, the `<Steps>` component is based on Markdown ordered lists and the content should follow the rule for [adding elements in list](https://www.markdownguide.org/basic-syntax/#adding-elements-in-lists). In this case, if your IDE is the one reformatting the content in an invalid format not matching a single ordered list, maybe its configuration can be tweaked or maybe the specific feature can be disabled in your IDE?

Can you tell me how to close it in IDEA

**Comment by delucis** [comment]
Maybe this post will help? https://stackoverflow.com/questions/30045874/how-to-disable-intellij-auto-change-my-code-format

Sounds like this is not a Starlight issue, so will close this. Thanks @huifer 🙌
