### ISSUE TITLE
sitemap no handler 

### ISSUE THREAD

**Issue by huifer** [withastro/starlight#2061]
### What version of `starlight` are you using?

^0.24.4

### What version of `astro` are you using?

^4.10.2

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### What browser are you using?

Chrome 

### Describe the Bug

https://zen-huifer.pages.dev/sitemap-index.xml

no sitemap-index.xml 

![image](https://github.com/withastro/starlight/assets/26766909/f5538e9f-2e32-4bc5-9cf1-89a569e6b669)

### Link to Minimal Reproducible Example

https://github.com/huifer/zen-huifer/blob/cf/astro.config.mjs

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by huifer** [comment]
![image](https://github.com/withastro/starlight/assets/26766909/121ffaee-51b5-48de-b037-c139a27e5623)

**Comment by delucis** [comment]
Hi @huifer! I’m not sure I understand the issue. When loading <https://zen-huifer.pages.dev/sitemap-index.xml>, I see the sitemap index as expected.

**Comment by huifer** [comment]
May I ask if this can be included on Google

**Comment by delucis** [comment]
It should work, yes! For example, https://docs.astro.build/ is built with Starlight and we successfully submitted the sitemap to Google.

**Comment by huifer** [comment]
![image](https://github.com/withastro/starlight/assets/26766909/f75a58bc-2a9d-4aea-bbc7-d31f6ace5d26)
   @delucis

**Comment by delucis** [comment]
It doesn’t appear to be a Starlight issue as far as I can tell:

1. The sitemap is generated correctly.
2. The sitemap is available at https://zen-huifer.pages.dev/sitemap-index.xml as expected.
3. Google reports that the index was processed successfully.

The error seems to be related to crawling your site. It might be that Cloudflare is blocking the Google bot crawling your site?

Given this is not a Starlight-specific problem, I will close this issue. Feel free to keep chatting here if it’s helpful, but it might also be good to look to see if there’s advice about indexing Cloudflare-hosted sites online.

**Comment by huifer** [comment]
@delucis   Starlight roboots.txt Can the problem be solved

**Comment by delucis** [comment]
@huifer Starlight doesn’t add a `robots.txt` itself, but you can do this yourself easily:

1. Create `public/robots.txt` inside your project

2. Add the following content:

   ```
   User-agent: *
   Allow: /

   Sitemap: https://zen-huifer.pages.dev/sitemap-index.xml
   ```
