### ISSUE TITLE
No table of contents generated when importing MDX

### ISSUE THREAD

**Issue by andrii-bodnar** [withastro/starlight#2078]
### What version of `starlight` are you using?

0.24.5

### What version of `astro` are you using?

4.11.3

### What package manager are you using?

npm

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

Hello!

I have some common parts in the documentation that I import into other documents. For example:

```mdx
import Test from '../../common/test.mdx'

Guides lead a user through a specific task they want to accomplish, often with a sequence of steps.
Writing a good guide requires thinking about what your users are trying to do.

<Test/>
```

The imported content renders fine, but the Table of Contents does not contain headings from the imported document.

Please refer to the MRE below (the _Example Guide_ page) to see it in action.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-ibdnst?file=src%2Fcontent%2Fdocs%2Fguides%2Fexample.mdx

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by delucis** [comment]
Thanks for the issue @andrii-bodnar!

Unfortunately this is a limitation of how Astro generates its `headings` list, which Starlight depends upon.

See #561 for more details.

**Comment by andrii-bodnar** [comment]
@delucis thank you!

**Comment by theoephraim** [comment]
Ah this one is really a bummer :(

I would have thought imported astro component titles wouldnt show up, but at least imported mdx files might.

Being able to DRY things up with reusable chunks would really be helpful!

I will try to dig in a bit and see if there are any sneaky workarounds.
