### ISSUE TITLE
[CSS Bug] Square root of KaTeX are invisible in starlight

### ISSUE THREAD

**Issue by widcardw** [withastro/starlight#2103]
### What version of `starlight` are you using?

0.24.4

### What version of `astro` are you using?

4.11.3

### What package manager are you using?

pnpm

### What operating system are you using?

Mac, Windows, Android

### What browser are you using?

Chrome, Safari

### Describe the Bug

https://github.com/withastro/starlight/blob/d1e4a9e41e17744a553035f1d10c4363243d50a2/packages/starlight/style/markdown.css#L44-L48

The square root of KaTeX uses svg. However, with the style `height: auto`, the square root will be invisible. It is not the problem of js. It's only about the css. In dev mode, all of these sqrts are shown, but in production mode, the problem will occur.

![image](https://github.com/withastro/starlight/assets/55699713/2c0140ac-41e6-4c4d-b7e2-7e94f675c0f7)

![image](https://github.com/withastro/starlight/assets/55699713/f421039f-4dcf-48d4-9da5-866eb8ebba55)

As a result, please think of any method that exclude the sqrt svg from the selected classes, may be the example below. Thanks.

```css
.sl-markdown-content :is(.katex svg):not(:where(.not-content *)) {
    height: inherit;
}
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-p8hdnk?file=src%2Fcontent%2Fdocs%2Findex.mdx

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by HiDeoo** [comment]
Thanks for your feeback :raised_hands:

By running your reproduction, I'm not able to see the issue you're facing. Here are the results I get in both light and dark theme using the dev and prod builds:

<img width="1602" alt="repro" src="https://github.com/withastro/starlight/assets/494699/1968ea50-291f-4e73-8829-320d81036a92">

Usually, KaTeX and MathJax involves a bit of custom CSS to be totally compatible with Starlight default styles. For example, this [guide](https://stackblitz.com/edit/github-xwtnqf?file=src%2Fcontent%2Fdocs%2Findex.md) show how to fix MathJax styling using some [custom CSS](https://starlight.astro.build/guides/css-and-tailwind/#custom-css-styles). If encountering issues with KaTeX, you might need to use a similar approach.

**Comment by widcardw** [comment]
Thanks for your quick response. I have made some changes on the custom css. In the reproduction, I have also added a `fix.css` to fix this problem.

```css
.sl-markdown-content :is(.katex svg):not(:where(.not-content *)) {
    height: inherit;
}
```

It works fine in production mode.

However, there may be some more users coming across this problem, so this issue may inform these users about the solution.
