### ISSUE TITLE
__dirname is not defined in ES module scope

### ISSUE THREAD

**Issue by torn4dom4n** [withastro/starlight#2106]
### What version of `starlight` are you using?

0.25.0

### What version of `astro` are you using?

4.11.5

### What package manager are you using?

pnpm

### What operating system are you using?

Windows

### What browser are you using?

Edge

### Describe the Bug

To reproduce the issue, follow these steps:

1. Clone the repository from the following link: https://github.com/MedPocket/18-months/commit/0f55f1e414a27d2a5cb747dfdf188fd98547f2ce.
2. Execute `pnpm build`. This will result in the error:
```
01:58:44 ▶ @astrojs/starlight/404.astro
01:58:44   └─ /404.html (+2.46s)
__dirname is not defined in ES module scope
  Stack trace:
    at file:///C:/Users/Windows/Documents/GitHub/MedPocket/18-months/dist/chunks/1720292275524/_...route_.mjs:580:66
    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
    at async generatePage (file:///C:/Users/Windows/Documents/GitHub/MedPocket/18-months/node_modules/.pnpm/astro@4.11.5_typescript@5.5.3/node_modules/astro/dist/core/build/generate.js:157:22)
    at async staticBuild (file:///C:/Users/Windows/Documents/GitHub/MedPocket/18-months/node_modules/.pnpm/astro@4.11.5_typescript@5.5.3/node_modules/astro/dist/core/build/static-build.js:105:7)
    at async AstroBuilder.run (file:///C:/Users/Windows/Documents/GitHub/MedPocket/18-months/node_modules/.pnpm/astro@4.11.5_typescript@5.5.3/node_modules/astro/dist/core/build/index.js:164:7)
 ELIFECYCLE  Command failed with exit code 1.
```

This is [my ci on GitHub Actions](https://github.com/MedPocket/18-months/actions/runs/9821454658/job/27117146175).

### Link to Minimal Reproducible Example

https://github.com/MedPocket/18-months/commit/0f55f1e414a27d2a5cb747dfdf188fd98547f2ce

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by HiDeoo** [comment]
Thanks for the report.

The issue you're hitting seems to be this [one](https://github.com/delucis/astro-og-canvas/issues/54) from `astro-og-canvas`. As [mentioned](https://github.com/delucis/astro-og-canvas/tree/latest/packages/astro-og-canvas) in the README, when using `pnpm`, users will also need to install `canvaskit-wasm` as a direct dependency:

```
pnpm add canvaskit-wasm
```

**Comment by delucis** [comment]
Ah yeah that’s always an unhelpful error. I wonder if we can do something better in `astro-og-canvas` 🤔 I guess it’s not so simple to detect pnpm usage and throw a more helpful error before that gets hit.

**Comment by HiDeoo** [comment]
> Ah yeah that’s always an unhelpful error. I wonder if we can do something better in `astro-og-canvas` 🤔 I guess it’s not so simple to detect pnpm usage and throw a more helpful error before that gets hit.

Good question, maybe moving away from the top-level exported promise `CanvasKitPromise` and refactoring to a function awaiting the canvas-kit `init` in a try-catch block which rethrow any error but also emit a pnpm hint/warning if the error message is this exact one? And I guess this would still allow for a single instance but only thinkin' out loud here without having tested it :thinking:

**Comment by delucis** [comment]
Released a new version of `astro-og-canvas` with an attempt at a more helpful error in this circumstance. I’m pretty confident this is the same issue, so will close this one as it’s not strictly speaking related to Starlight. Happy to reopen if more information comes to light @torn4dom4n!
