### ISSUE TITLE
favicon icons don't need `rel="shortcut icon"` - can just be `rel="icon"`

### ISSUE THREAD

**Issue by coliff** [withastro/starlight#2112]
### What version of `starlight` are you using?

0.25.0

### What version of `astro` are you using?

4.11.5

### What package manager are you using?

npm

### What operating system are you using?

Windows

### What browser are you using?

Edge

### Describe the Bug

![image](https://github.com/withastro/starlight/assets/1212885/a7cf93a6-146e-465d-8d52-edb18fedaf93)

No need for `rel="shortcut icon"`, should be just `rel="icon"`.

`shortcut` is not, and never has been, a valid link relation. Read this [amazing article](https://mathiasbynens.be/notes/rel-shortcut-icon) by Mathias Bynens from ten years ago that explains why we never needed shortcuts and why rel="icon" is just fine.

(from: https://evilmartians.com/chronicles/how-to-favicon-in-2021-six-files-that-fit-most-needs)

### Link to Minimal Reproducible Example

n/a

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by delucis** [comment]
Thanks for the issue @coliff! I’m not sure this rises to the level of a bug if nothing is breaking?

The HTML spec [was updated](https://html.spec.whatwg.org/multipage/links.html#rel-icon:~:text=the%20icon%20keyword%20may%20be%20preceded%20by%20the%20keyword%20%22shortcut%22.) since that initial article was written to say:
> For historical reasons, the [`icon`](https://html.spec.whatwg.org/multipage/links.html#rel-icon) keyword may be preceded by the keyword "`shortcut`". If the "`shortcut`" keyword is present, the [`rel`](https://html.spec.whatwg.org/multipage/links.html#attr-hyperlink-rel) attribute's entire value must be an [ASCII case-insensitive](https://infra.spec.whatwg.org/#ascii-case-insensitive) match for the string "`shortcut icon`" (with a single U+0020 SPACE character between the tokens and no other [ASCII whitespace](https://infra.spec.whatwg.org/#ascii-whitespace)).

Would welcome a PR cleaning this up though if you’re interested 🙌
