### ISSUE TITLE
Does not work with yarn

### ISSUE THREAD

**Issue by CodeAndWeb** [withastro/starlight#2115]
### What version of `starlight` are you using?

0.25.0

### What version of `astro` are you using?

4.11.5

### What package manager are you using?

yarn

### What operating system are you using?

Mac, Arm

### What browser are you using?

Chrome

## Clean install fails with yarn

yarn 4.3.1

~~~
yarn create astro --template starlight
~~~

With defaults (Typescript, Strict, Install dependencies, Init git) fails with

>   ▲  error Error
>       ▲  error Dependencies failed to install, please run yarn install to install them manually after setup.

~~~
yarn install
~~~

>➤ YN0000: · Yarn 4.3.1
>➤ YN0000: ┌ Resolution step
>➤ YN0001: │ Error: volar-service-css@volar-2.4 isn't supported by any available resolver

## Before using the clean project...

I was able to create the project but building it failed when using page find.
This issue seems now have gone.
But the basic problem was the same: It works with npm but not with yarn.

## Switching to npm works
~~~
rm yarn.lock
npm install
~~~

### Link to Minimal Reproducible Example

see above - just run yarn create astro.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
This should be fixed in the last version of `@astrojs/check`. Sorry for the inconvenience. I ultimately think this is a bug in Yarn 4, as previous versions of Yarn were able to install it just fine, and so does npm and pnpm.

I would suggest not using Yarn

**Comment by delucis** [comment]
Thanks for investigating and fixing @Princesseuh!
