### ISSUE TITLE
Can't create a new project using the template

### ISSUE THREAD

**Issue by igorskyflyer** [withastro/starlight#2127]
### What version of `starlight` are you using?

0.25.1

### What version of `astro` are you using?

4.10.2

### What package manager are you using?

npm

### What operating system are you using?

Windows

### What browser are you using?

Chrome

### Describe the Bug

I cannot create a new project using the command provided in the official [Starlight documentation](https://starlight.astro.build/getting-started/), i.e.:

`npm create astro@latest -- --template starlight`

<br>

Here's a screenshot, same thing happens in the Windows Terminal and the integrated terminal in VS Code.

<div align="center">
	<img src="https://github.com/user-attachments/assets/be74b8d6-ab66-41a9-b93c-731f0cf5ff5b" alt="Astro Starlight install">
</div>

<br>
<br>

For some reason the `starlight` value of the template parameter is detected as the project's root and running the command will install *plain* Astro, without Starlight.

### Link to Minimal Reproducible Example

https://github.com/igorskyflyer/igorskyflyer.me

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by lorenzolewis** [comment]
I wonder if this issue is related when using PowerShell: https://github.com/npm/cli/issues/3136

It seems like the "workaround" is to use 3 sets of dashes, I.e.: `npm create astro@latest -- -- --template starlight`

**Comment by HiDeoo** [comment]
Thanks for your report.

Like Lorenzo, I would indeed also assume a similar issue as [this one](https://github.com/withastro/astro/issues/9256) but as commented, not a lot can be done on the Astro side.

It looks like `npm create astro@latest --- --template starlight` could also be a valid workaround.

I'll wait for a confirmation before closing the issue to make sure it's indeed properly identified 👍

**Comment by igorskyflyer** [comment]
> I wonder if this issue is related when using PowerShell: [npm/cli#3136](https://github.com/npm/cli/issues/3136)
> 
> It seems like the "workaround" is to use 3 sets of dashes, I.e.: `npm create astro@latest -- -- --template starlight`

<br>

> [!TIP]
> **That actually works!** 🎉
>

<br>

Muchisimas gracias, that fixed it, though I do remember installing Starlight in another project like 6-7 months ago and it worked, not sure when the bug was introduced in npm/Windows.

**Comment by HiDeoo** [comment]
Thanks for confirming that the workaround works and Lorenzo for figuring it out :raised_hands:
