### ISSUE TITLE
Unable to build in devcontainer 

### ISSUE THREAD

**Issue by QuentinLCS** [withastro/starlight#2132]
### What version of `starlight` are you using?

0.25.1

### What version of `astro` are you using?

4.11.5

### What package manager are you using?

pnpm ( seems to be the same with npm )

### What operating system are you using?

Mac

### What browser are you using?

Any

### Describe the Bug

When I run astro ( `pnpm run dev` ) in my devcontainer, the build freezes without throwing any error. 

Note : It works as soon as I remove starlight from the dependencies. 

Here are the logs in verbose : 
[log.txt](https://github.com/user-attachments/files/16202916/log.txt)

### Link to Minimal Reproducible Example

https://github.com/QuentinLCS/astro-starlight

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by HiDeoo** [comment]
Thanks for the report.

From my early investigation, it looks like the issue appears as soon as the `astro-expressive-code` integration (which is used by Starlight) is added.

> Note : It works as soon as I remove starlight from the dependencies.

Would you be able to confirm this by commenting out entirely Starlight from your `astro.config.mjs` file, installing `astro-expressive-code` (`pnpm astro add astro-expressive-code`) and see if you're also observing the same issue?

If yes, this may be an issue to report in the Expressive Code repository.

**Comment by QuentinLCS** [comment]
> From my early investigation, it looks like the issue appears as soon as the astro-expressive-code integration (which is used by Starlight) is [added](https://github.com/withastro/starlight/blob/c5f1a8dd483485d626c568c7bd68423926c28ece/packages/starlight/index.ts#L81-L86).

Confirmed

**Comment by delucis** [comment]
Thanks again for digging into that @QuentinLCS! Will close this in favour of https://github.com/expressive-code/expressive-code/issues/224
