### ISSUE TITLE
Starlight Astro Github Pages docs url not working

### ISSUE THREAD

**Issue by windmillcode0** [withastro/starlight#2164]
### What version of `starlight` are you using?

0.25.3

### What version of `astro` are you using?

4.10.2

### What package manager are you using?

npm

### What operating system are you using?

Windows

### What browser are you using?

Chrome

### Describe the Bug

I followed the docs for github pages https://docs.astro.build/en/guides/deploy/github/#configure-astro-for-github-pages
and for github pages I have set the serve directory to docs as welll ensure the build assets came from the docs folder
github is able to find index html but index.html cant retrieve anything else.

Here is the link to the github repo of the issue
https://github.com/windmillcode0/starlight_astro_gh_pages_doesnt_work

This cant been in a stackblitz because this is a deploy issue

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-gdjr4r?file=astro.config.mjs

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by delucis** [comment]
Thanks for the issue @windmillcode0!

Can I ask how and when you are building the contents of the `docs/` directory? It looks like it was built without `site` and `base` set, so might need rebuilding?

I just tried deploying with the [recommended GitHub Actions approach](https://docs.astro.build/en/guides/deploy/github/#configure-a-github-action) shown in the Astro Docs and it worked as expected ([repo](https://github.com/withastro/starlight-gh-pages-test), [deployment](https://astro.js.org/starlight-gh-pages-test/)).

**Comment by delucis** [comment]
Based on [this Discord post](https://discord.com/channels/830184174198718474/1070481941863878697/1270000111812083752) sounds like this is resolved 🙌
