### ISSUE TITLE
Relative links not work normal

### ISSUE THREAD

**Issue by Arhell** [withastro/starlight#2214]
### What version of `starlight` are you using?

0.25.4

### What version of `astro` are you using?

4.13.3

### What package manager are you using?

npm 

### What operating system are you using?

windows

### What browser are you using?

chrome

### Describe the Bug

example https://github.com/testomatio/docs/blob/docs/src/content/docs/reference/reporter/pipes.md#built-in-pipes links work 
But on site not https://docs.testomat.io/reference/reporter/pipes/#custom-pipe

There is no way to correct the path since the content is taken from another repository.

### Link to Minimal Reproducible Example

https://docs.testomat.io/reference/reporter/pipes/#custom-pipe

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Arhell** [comment]
I looked in your repository and it doesn't understand .md files either.
Example https://github.com/withastro/starlight/blob/main/docs/src/content/docs/getting-started.mdx
**manual setup instructions**

But on site work https://starlight.astro.build/getting-started/

**Comment by delucis** [comment]
Hi @Arhell! Thanks for the issue.

Starlight doesn’t transform links at all, so the exact way you author them is how they are also built in the published site. For example, here’s the HTML of one of your links from the page you shared:

```html
<a href="./pipes/testomatio.md">Testomat.io</a>
```

But the built page will not include the `.md` extension, so you get a 404.

Additionally, in HTML, the behaviour of relative links depends on the current URL.

If the current URL is `/reference/reporter/pipes`, then the relative link above resolves to `/reference/reporter/pipes/testomatio.md`.

But if the current URL is `/reference/reporter/pipes/` **with** a trailing slash, then the relative link above resolves to `/reference/reporter/pipes/pipes/testomatio.md`.

If it is important for you to keep the `.md` links in your Markdown, you could use something like https://github.com/rjanjic/remark-link-rewrite to transform these to the correct output when building.

**Comment by lorenzolewis** [comment]
Including the link to a utility that may help with this for future reference that I posted in Discord. But again, haven't tried it myself and over time I've preferred using absolute-style links as they're a lot easier to understand later for me when coming back later.

https://github.com/withastro/astro/issues/5680#issuecomment-1535211867

**Comment by Arhell** [comment]
> Including the link to a utility that may help with this for future reference that I posted in Discord. But again, haven't tried it myself and over time I've preferred using absolute-style links as they're a lot easier to understand later for me when coming back later.
> 
> [withastro/astro#5680 (comment)](https://github.com/withastro/astro/issues/5680#issuecomment-1535211867)

Thank you, in principle I agree, but I would like the site to have correct links and in the repository, so that both would open without a 404 error, as for me it is more convenient for a person
