### ISSUE TITLE
Links within docs do not take locale into account

### ISSUE THREAD

**Issue by afonsojramos** [withastro/starlight#229]
### Describe the Bug

Maybe this is not a bug _per se_, however I do feel like it is a design flaw as it is.
Links provided within MDX generated pages do not take into account the selected locale, and I feel like this would be logical.

~Another bug that is somewhat related is the fact that going to the `/` goes to a 404, instead of going to the default locale.~
This one has now been fixed.

**Comment by delucis** [comment]
Thanks for the issue @afonsojramos and for your patience!

I think this is a tricky one. In general Starlight treats links _as authored_. The only exception is for links it manages (i.e. sidebar and next/previous page links will always respect locale).

I’m not sure we’d be able to design a behaviour that makes sense for all users, so I’ll close this issue for now, but I’m happy to keep discussing here if you have ideas for the exact behaviour you’d expect to see.
