### ISSUE TITLE
Trying to run the project on my system

### ISSUE THREAD

**Issue by uyiekpen** [withastro/starlight#239]
### What version of `starlight` are you using?

2.5.0

### What version of `astro` are you using?

2.5.0

### What package manager are you using?

npm

### What operating system are you using?

Windows

### What browser are you using?

Chrome

### Describe the Bug

ript, failed in 9m 31.2s
.../node_modules/puppeteer install$ node install.js
└─ Failed in 9m 31.2s at C:\Users\USER\Desktop\personal project\starlight\node_modules\.pnpm\puppeteer@9.1.1\node_modules\puppeteer

i was trying to run pnpm i

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by delucis** [comment]
Thanks for reporting @uyiekpen! Just checked with one of our maintainers who has a Windows computer and they said they remembered seeing something similar, but running `pnpm i` again fixed it for them, so maybe try that as a first step. If that doesn’t work, let me know — perhaps sharing a bit more of the error log.

Were you looking to contribute something specific or did you want to build a website with Starlight?

**Comment by uyiekpen** [comment]
i was looking to contribute something

**Comment by uyiekpen** [comment]
.../node_modules/puppeteer install$ node install.js
│ ERROR: Failed to set up Chromium r869685! Set "PUPPETEER_SKIP_DOWNL…
│ Error: read ECONNRESET
│     at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:…
│   errno: -4077,
│   code: 'ECONNRESET',
│   syscall: 'read'
│ }
└─ Failed in 1m 41.5s at C:\Users\USER\Desktop\personal project\starlight\node_modules\.pnpm\puppeteer@9.1.1\node_modules\puppeteer
 ELIFECYCLE  Command failed with exit code 1.

this is the error i am having

**Comment by delucis** [comment]
Thanks for sharing. It looks like during dependency installation, Puppeteer fails to download Chromium correctly.

Puppeteer is only needed for running our accessibility test, which we do in a GitHub Action, so is not essential for local development (unless you wanted to run the accessibility test locally but let’s skip that for now).

To unblock your work, I’d suggest the following:

```sh
cd docs
pnpm un pa11y-ci
pnpm i
```

This will remove [`pa11y-ci`](https://github.com/pa11y/pa11y-ci) (the tool that’s pulling in Puppeteer) as a dependency and then hopefully you can successfully install all the other dependencies. Avoid committing the updated `package.json` and `pnpm-lock.yaml` files while you work and we should be OK hopefully 🤞 

I’ll also take a look if there’s something we can do to help avoid forcing people through that big download just to get started.

**Comment by delucis** [comment]
Oh, and one other option might be to try using something like [Gitpod](https://www.gitpod.io/)! Because they’re installing dependencies on their servers and you’re just editing in the browser, sometimes they can help in these situations. We have a [short guide to setting up the repo with Gitpod](https://github.com/withastro/starlight/blob/main/CONTRIBUTING.md#developing-using-gitpod) too. @sarah11918 who is the Astro Docs Lead contributes like this very often, so let us know if you feel like trying that and run into anything!

**Comment by uyiekpen** [comment]
ohh.. thanks for the respond..i have fixed it and it running in my local machine

**Comment by delucis** [comment]
Hi @uyiekpen — just tidying up issues, and I think this one is resolved so I will close it. Don’t hesitate to post further if you have questions though!
