### ISSUE TITLE
Additional styles added to MDX Components

### ISSUE THREAD

**Issue by evan-dunkel** [withastro/starlight#241]
### What version of `starlight` are you using?
0.2.0

### What version of `astro` are you using?
2.6.6

### What package manager are you using?
npm

### What operating system are you using?
Mac

### What browser are you using?
Safari, Chrome

### Describe the Bug

**Expected:** When using components in MDX CSS is sandboxed to the component. Alternatively, providing an opt-out class for the `.content` class, for example, `.not-content` could allow components to be exempt from the MDX margin processing.

**Actual:** Components and their contents have a "margin-top: 1.5em" rule added.

**How to reproduce:**
Add a component of any type to an MDX file, include at least one div. Upon rendering and processing, an unexpected margin-top rule is added. This can cause components to break visual styles.

———

Issue also referenced by @marcjulian in https://github.com/withastro/starlight/issues/88#issuecomment-1562461482

———

Edit: Font sizes are also affected (e.x. an `<h2>` element). There are likely other styles impacted by the markdown processing.

**Comment by delucis** [comment]
Thanks for the issue @evan-dunkel! I think the `.not-content` class idea is probably the way to go here — taking a look at how we implement this now.

**Comment by delucis** [comment]
Added a proposed solution in #313 — feel free to leave feedback if you have any.

**Comment by marcjulian** [comment]
Thanks, thats what I was looking for the Tailwind CSS integration too.
