### ISSUE TITLE
Lists are unstyled in default installation

### ISSUE THREAD

**Issue by LunaticMuch** [withastro/starlight#2424]
### What version of `starlight` are you using?

0.28.2

### What version of `astro` are you using?

4.15.9

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### What browser are you using?

Safari

### Describe the Bug

Using the default starlight installation, without tailwind plugin, the lists are completely unstyled

### Link to Minimal Reproducible Example

working...

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by HiDeoo** [comment]
Thanks for your feedback.

Would you be able to provide a small reproduction of the issue, e.g. on StackBlitz? I did not manage to reproduce such behavior so far, e.g. in the [Starlight documentation](https://starlight.astro.build/getting-started/#next-steps) or in a brand new [project](https://stackblitz.com/edit/github-o1se8d?file=src%2Fcontent%2Fdocs%2Findex.mdx).

Here is a preview of what I'm currently seeing in Safari for the Stackblitz example I linked above:

<img width="799" alt="image" src="https://github.com/user-attachments/assets/f51854b7-7cba-4a69-9b35-4571433000b0">

**Comment by delucis** [comment]
Closing this as we can’t reproduce currently. Happy to take a look if you can share a link to a site with this issue or a repo/StackBlitz showing it!
