### ISSUE TITLE
Vulnerability found in cookies package

### ISSUE THREAD

**Issue by sreejithkalarikkal** [withastro/starlight#2484]
### What version of `starlight` are you using?

0.28.3

### What version of `astro` are you using?

4.16.3

### What package manager are you using?

pnpm

### What operating system are you using?

Windows

### What browser are you using?

Chrome

### Describe the Bug

I am using  Astro Starlite theme  got two vulnerability issue when I run pnpm audit fix command on cookie npm package as below
'cookie accepts cookie name, path, and domain with out   of bounds characters ' .
I upgraded the starlite theme and astro using command  'pnpm install @astrojs/starlight@0.28.3 @astrojs/tailwind@5.1.2 
astro@4.16.3'.
Now one vulnerability is gone but still other exists in the below . 
                        │ packages/healthelink-docs-prime >                      │
│ Paths                       │ astro-page-insight@0.8.6 > lighthouse@12.2.1 >         │
│                     │ @sentry/node@6.19.7 > cookie@0.4.2 

### Link to Minimal Reproducible Example

Nil

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by delucis** [comment]
Thanks for the issue @sreejithkalarikkal !

This looks like it isn't caused by Starlight unless I have misunderstood. Upgrading to the latest Astro release like you did removes Astro's dependency on the vulnerable version of `cookie`.

Based on your comment it sounds like the vulnerable version is still being pulled in by another dependency rather than Starlight/Astro.

**Comment by sreejithkalarikkal** [comment]
Can you please explain more on it. Out of two one vulnerability is removed.

**Comment by delucis** [comment]
If I'm understanding correctly, the table you're posting shows the dependencies causing the issue. In other words, `astro-page-insights` depends on `lighthouse` which depends on `@sentry/node` which depends on the vulnerable version of `cookie`. `astro-page-insights` is not part of Starlight, and if you uninstalled it, that would remove the "vulnerable" dependency. That said, the vulnerability may not be serious if that integration is only running during dev and your site is static.

Either way, I don't think this is a Starlight issue, so hope you don't mind me closing this! (Feel free to ask further questions if you need to though.)
