### ISSUE TITLE
Slight layout shift when opening search modal due to scroll bar disappearing

### ISSUE THREAD

**Issue by corneliusroemer** [withastro/starlight#2514]
### What version of `starlight` are you using?

0.28.3 (whatever is on https://starlight.astro.build/ right now)

### What version of `astro` are you using?

whatever is used on https://starlight.astro.build/ right now

### What package manager are you using?

whatever is used on https://starlight.astro.build/ right now

### What operating system are you using?

Mac

### What browser are you using?

Chrome Beta 131

### Describe the Bug

When opening the page search modal, there's a small layout shift of the background due to the scroll bar disappearing in modal view.

It's difficult to avoid the layout shift, maybe one could reserve some width for the scrollbar in modal view as well.

![2024-10-27 10 51 49](https://github.com/user-attachments/assets/ee6a9f2a-2b39-4b5d-a17a-d53569716ec3)

To reproduce:
1. Click on the search modal
2. Observe layout shift

### Link to Minimal Reproducible Example

https://stackblitz.com/github/withastro/starlight/tree/main/examples/basics?file=README.md

### Participation

- [x] I am willing to submit a pull request for this issue.

**Comment by corneliusroemer** [comment]
Suggested fix: add the following CSS:

```css
html {
  scrollbar-gutter: stable;
}
```

**Comment by sgmustafi** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by corneliusroemer** [comment]
The above is spam

**Comment by delucis** [comment]
We’ve spent some time investigating if there are viable options to solve this but have come to the conclusion that for now, although not ideal, we don’t seem to have the right tools in browsers to solve this in a robust enough way to work consistently across the diversity of devices and sites we support.

Hopefully one day that will change and we can revisit but given this, I’m going to change this issue as something beyond our powers.

Thanks nevertheless for the issue and attempting to fix the issue in #2515 @corneliusroemer! Hopefully these are still useful reference points and people still feel able to add `scrollbar-gutter: stable` to their sites as a customization if it works in their specific context.
