### ISSUE TITLE
TOC in sidebar does not preserve markup/styling of heading

### ISSUE THREAD

**Issue by septatrix** [withastro/starlight#2527]
### Astro Info

```block
Astro                    v4.16.7
Node                     v20.17.0
System                   Linux (x64)
Package Manager          pnpm
Output                   static
Adapter                  none
Integrations             @astrojs/starlight
```

### Describe the Bug

When using markup like `~foo~`, `_foo_`, `**foo**`, `` `foo` `` in the heading these are not preserved in the sidebar.

![image](https://github.com/user-attachments/assets/a09ddb7d-5af8-46fa-805a-25d886e82162)

### What's the expected result?

The styling of the headings should be preserved in the sidebar.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-mpkxlz-kud7v5?file=src%2Fcontent%2Fdocs%2Fguides%2Fexample.md

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by delucis** [comment]
Thanks for the issue @septatrix!

This behaviour is expected. Starlight depends on Astro’s `headings` feature which extracts only the plain text values of headings, not also any HTML markup, so Starlight can’t really support this.

I think it would also be hard to support fully even if this wasn’t the case. It seems OK in this limited subset of examples, but supporting all HTML in the table of contents (which is supposed to be a quick guide to page content), feels very likely to break (e.g. what if you had a `<span class="something">word</span>` with styles? Do those styles now also apply in the TOC?)

**Comment by septatrix** [comment]
> Thanks for the issue @septatrix!
> 
> This behaviour is expected. Starlight depends on Astro’s `headings` feature which extracts only the plain text values of headings, not also any HTML markup, so Starlight can’t really support this.

Yeah that's why I opened this originally in the Astro repo. If I understand correctly it's this code: https://github.com/withastro/astro/blob/feb87c21be37e508ec8b23cfbb47056fd0971dfc/packages/markdown/remark/src/rehype-collect-headings.ts#L13

> I think it would also be hard to support fully even if this wasn’t the case. It seems OK in this limited subset of examples, but supporting all HTML in the table of contents (which is supposed to be a quick guide to page content), feels very likely to break (e.g. what if you had a `<span class="something">word</span>` with styles? Do those styles now also apply in the TOC?)

That is true and I specifically selected those example as they seem reasonable and can be easily used within markdown. One suggestion would be to expand [`getHeadings()`](https://docs.astro.build/en/guides/markdown-content/#importing-markdown) to return not only `text` but also `html` or `markdown` (not sure if `child.value` is rendered HTML at that stage or still markdown). This way users who like the additional capabilities can use them while everyone else retains the text-only headings.

**Comment by delucis** [comment]
> One suggestion would be to expand [`getHeadings()`](https://docs.astro.build/en/guides/markdown-content/#importing-markdown) to return not only `text` but also `html` or `markdown` (not sure if `child.value` is rendered HTML at that stage or still markdown).

Yeah that could be an option. You could open a roadmap discussion if you like: https://github.com/withastro/roadmap/discussions/

That would allow other users to upvote and provide feedback on the idea and help us understand if it’s a common need.

**Comment by septatrix** [comment]
> > One suggestion would be to expand [`getHeadings()`](https://docs.astro.build/en/guides/markdown-content/#importing-markdown) to return not only `text` but also `html` or `markdown` (not sure if `child.value` is rendered HTML at that stage or still markdown).
> 
> Yeah that could be an option. You could open a roadmap discussion if you like: https://github.com/withastro/roadmap/discussions/

Thanks for the hint. I opened https://github.com/withastro/roadmap/discussions/1060 now
