### ISSUE TITLE
Sidebar links include a locale not used by the site after 0.28.5

### ISSUE THREAD

**Issue by tmcw** [withastro/starlight#2553]
### What version of `starlight` are you using?

0.28.5

### What version of `astro` are you using?

4.16.8

### What package manager are you using?

pnpm

### What operating system are you using?

mac

### What browser are you using?

Chrome

### Describe the Bug

We hit an issue related to this https://github.com/withastro/starlight/pull/2548 - our [docs](https://docs.val.town/) don't use the `/en/` prefix (we have `defaultLocale: en`), and after updating, sidebar links include the `/en/` prefix and thus lead to 404s: staging deploy that replicates the issue here: https://d30789a7.val-town-docs.pages.dev/

### Link to Minimal Reproducible Example

https://d30789a7.val-town-docs.pages.dev/

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by delucis** [comment]
Thanks for the issue @tmcw! It looks like you actually have a misconfiguration that happened to work as you expected previously, but wasn’t intended to. Sorry nonetheless for the disruption!

The [`locales` config in your `astro.config.mjs`](https://github.com/val-town/val-town-docs/blob/958b9d29c645164603aecb6e9970807262094564/astro.config.mjs#L30-L34) should either look like this:

```js
      locales: {
        root: {
          label: 'English',
          lang: 'en',
        },
      },
```

(as documented in the [Starlight i18n guide](https://starlight.astro.build/guides/i18n/#monolingual-sites))

**OR** can be omitted entirely as an English root locale is also Starlight’s default.

**Comment by delucis** [comment]
Thanks again for the issue @tmcw — going to close this as I believe it has been resolved, but let me know if you have any questions or still think there’s a bug here.
