### ISSUE TITLE
`trailingSlash` is not respected for the multilingual sites selector

### ISSUE THREAD

**Issue by Aviortheking** [withastro/starlight#2609]
### What version of `starlight` are you using?

0.29.0

### What version of `astro` are you using?

4.16.13

### What package manager are you using?

npm

### What operating system are you using?

Linux

### What browser are you using?

Firefox

### Describe the Bug

when in the Astro config I have `trailingSlash: 'never'`, It seems that links for the language switch are not set to respect the same attribute as they are always ending with `/`

ex: `/fr/` instead of `/fr`

Repository: https://github.com/tcgdex/documentation

### Link to Minimal Reproducible Example

https://github.com/tcgdex/documentation

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by delucis** [comment]
Hi @Aviortheking, thanks for the issue. Is https://tcgdex.dev/ the right place to look to see this issue? Navigating there I see trailing slash correctly excluded, including in the language switcher markup:

![DevTools inspector showing a select element with value attribute of /de/sdks/java](https://github.com/user-attachments/assets/995998b8-b60d-4c79-b6b2-1d9b30f818b5)

**Comment by Aviortheking** [comment]
Thanks for the quick answer it seems to only fail on the homepage where the markup is correct but the JS behind is changing it

**Comment by delucis** [comment]
Ah, thanks for the extra detail. I can see this too. Specifically when navigating from the English base URL to another language (e.g. `/` => `/fr/` instead of `/fr`). Navigating between other languages works as expected.

**Comment by Aviortheking** [comment]
Thanks, it work perfectly !
