### ISSUE TITLE
Breaking changes when defining a custom sidebar (after perf optimizations work)

### ISSUE THREAD

**Issue by jits** [withastro/starlight#2610]
### What version of `starlight` are you using?

0.29.0

### What version of `astro` are you using?

4.16.13

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

I _think_ the changes in https://github.com/withastro/starlight/pull/2252 have broken a very specific scenario: defining a custom sidebar in a custom page that uses the `StarlightPage` component.

The entries in the custom sidebar _are_ showing up, but I'm seeing at least two breakages from before:

1. The current page is not highlighted in the sidebar.
2. The pagination links no longer show up.

See the linked Stackblitz for more info.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-d9y2ao?file=src%2Fpages%2F%5B...id%5D.astro

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by HiDeoo** [comment]
Thanks for the minimal and obvious repro, super helpful and appreciated :raised_hands:

I've opened #2614 to fix the issue.

**Comment by jits** [comment]
@HiDeoo — amazing work to so quickly find and resolve the issue. Thank you so much! 🙌🏽
