### ISSUE TITLE
Replace 'src/content/' with 'src/data/' for Astro 5

### ISSUE THREAD

**Issue by kripod** [withastro/starlight#2698]
### What version of `starlight` are you using?

0.30.1

### What version of `astro` are you using?

5.0.5

### What package manager are you using?

pnpm@9.15.0

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

As per [this changelog entry of Astro 5](https://github.com/withastro/astro/pull/12551/files#diff-968259103077c2cfef8cf4d8c7a445c252844e9c26e315cbdc83af44625eff5d):

> legacy collections (only) must continue to remain in `src/content/`, while **new collections using a loader from the Content Layer API are forbidden in that folder**

Therefore `docsLoader()` from `"@astrojs/starlight/loaders"` shall not return with a `base` referring to `${rootDir}/content/*` but `${rootDir}/data/*`. Functions like [`getCollectionPathFromRoot`](https://github.com/withastro/starlight/blob/2c3a4ad9c71f4f0bfb8c6c6d4512d173f31ac615/packages/starlight/utils/collection.ts#L42) and [`getCollectionPath`](https://github.com/withastro/starlight/blob/2c3a4ad9c71f4f0bfb8c6c6d4512d173f31ac615/packages/starlight/utils/collection.ts#L26) should also be refactored accordingly.

As a workaround, I’ve defined my docs content loader manually for now:

```tsx
// src/content.config.ts
const docs = defineCollection({
  loader:
    // TODO: Use `docsLoader()` from "@astrojs/starlight/loaders"
    glob({
      pattern: "**/[^_]*.{markdown,mdown,mkdn,mkd,mdwn,md,mdx}",
      base: "./src/data/docs",
    }),
  schema: docsSchema(),
});

export const collections = { docs };
```

### Link to Minimal Reproducible Example

N/A

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by HiDeoo** [comment]
Thanks for the report.

The quotted part is only applicable when using the `legacy.collections` configuration flag:

> When set, no changes to your existing collections are necessary, and the restrictions on storing both new and old collections continue to exist: legacy collections (only) must continue to remain in `src/content/`, while new collections using a loader from the Content Layer API are forbidden in that folder.

At the moment, Starlight only supports content in the `src/content/docs/` directory, no matter if you're using legacy collections or not. If you're using legacy collections because you are unable to make any changes to your other collections at this time, you can still use Starlight with the `legacy.collections` configuration flag set to `true` and without a loader in the `src/content/docs/` directory.
