### ISSUE TITLE
Sitemaps not deploying after updating to Astro 5 in Vercel

### ISSUE THREAD

**Issue by TeenBiscuits** [withastro/starlight#2700]
### What version of `starlight` are you using?

0.30.1

### What version of `astro` are you using?

5.0.5

### What package manager are you using?

pnpm

### What operating system are you using?

Windows

### What browser are you using?

Chrome

### Describe the Bug

When deploying to Vercel with the Vercel Adapter in static mode, the sitemap is generated in `dist/` but not in `.vercel/`.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-xypixwuq

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by TeenBiscuits** [comment]
Sorry if the issue is short it is my first time creating an issue in this repo.

**Comment by delucis** [comment]
Thanks for the issue @TeenBiscuits!

This appears to be a bug in Astro/the Vercel adapter, being tracked here:
- https://github.com/withastro/adapters/issues/445
- https://github.com/withastro/astro/issues/12663

Don’t think we can fix it directly in Starlight, so I’d recommend following those issues for a fix.
