### ISSUE TITLE
Styles missing when using `<StarlightPage />` in `.astro` page.

### ISSUE THREAD

**Issue by marcosmartini** [withastro/starlight#2712]
### What version of `starlight` are you using?

 0.30.2

### What version of `astro` are you using?

5.0.8

### What package manager are you using?

npm 

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

When adding a custom page to a Starlight project using Tailwind, if we import the `<StarlightPage />` component into it, the styles won't load. 

Sometimes the styles load at first, but break on re-load. I noticed that the built version is fine, this only seems to happen in development.

### Link to Minimal Reproducible Example

https://stackblitz.com/~/github.com/marcosmartini/grubby-gravity?file=src/content/docs/index.mdx

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by HiDeoo** [comment]
Thanks for your report 🙌 

This seems to be a duplicate issue of [this one](https://github.com/withastro/astro/issues/12754) which was initially opened in this repo and transferred to the Astro repo. I'd recommend you to follow the issue there for updates.
