### ISSUE TITLE
non-i18n data collections no longer available via the new data loader architecture

### ISSUE THREAD

**Issue by kaytwo** [withastro/starlight#2721]
### What version of `starlight` are you using?

0.30.2

### What version of `astro` are you using?

5.0.9

### What package manager are you using?

npm

### What operating system are you using?

Mac and Linux (via WSL2)

### What browser are you using?

Chrome and Brave

### Describe the Bug

in pre-5.0 Starlight, I could create data collections like so:

```js
export const collections = {
  docs: defineCollection({ schema: schema }),
  exams: defineCollection({ schema: exams, type: "data" }),
};
```

Now, however, because the type `StarlightCollection` is restricted to `i18n` and `docs`, I need to pull and slightly edit both `createGlobLoadFn` and `getCollectionPathFromRoot` into my project to successfully create my own data collection.

It would be great if Starlight did not restrict collections to those two types and instead allowed the addition of arbitrary data collections. I believe this could be done by (a) relaxing the `StarlightCollection` type to `string`, and (b) adding a dataLoader() function to loaders.ts:

```js
export function dataLoader(collection: string): Loader {
  return {
    name: `starlight-${collection}-loader`,
    load: createGlobLoadFn(collection),
  }
}
```

Slightly off topic: in stackblitz when the first content load happens, it doesn't work for the docs collection, leading to a render error. This can be worked around by editing any file in the collection which causes a reload that is successful. This error also exists on first load when creating a totally clean Starlight example: <https://astro.new/starlight-basics?on=stackblitz>

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-mty5ewmd?file=src%2Fcontent.config.ts

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by HiDeoo** [comment]
Thanks for the report.

Collections are not a Starlight feature but an Astro feature that Starlight is built on. In Astro v5, you can still have your own collections but they would need to be upgraded by following the ["Updating existing collections"](https://docs.astro.build/en/guides/upgrade-to/v5/#updating-existing-collections) section of the [Astro v5 migration guide](https://docs.astro.build/en/guides/upgrade-to/v5/).

In your specific case, I don't exactly know what your `exams` collection looks like, but if it is a collection of JSON files located in the `src/content/exams/` directory, you should be able to use the Astro [built-in `glob` loader](https://docs.astro.build/en/guides/content-collections/#built-in-loaders).

```ts
import { defineCollection, z } from 'astro:content';
import { docsLoader } from '@astrojs/starlight/loaders';
import { docsSchema } from '@astrojs/starlight/schema';
import { glob } from 'astro/loaders';

export const collections = {
  docs: defineCollection({ loader: docsLoader(), schema: docsSchema() }),
  exams: defineCollection({
    loader: glob({ pattern: '**/[^_]*.json', base: "./src/content/exams" }),
    schema: exams,
  }),
};
```

**Comment by kaytwo** [comment]
Thanks for the fast response! I had tried this approach but Astro kept telling me that it was an empty collection, so I figured that the issue was that I wasn't using the `.load()` function call like is done in Starlight's code:

https://github.com/withastro/starlight/blob/ec4b85154ea301d9144ff49f3abd009e3a929387/packages/starlight/loaders.ts#L38

In my current edit, doing the glob directly seems to work just fine without access to the build context, but I haven't exercised it too deeply. Is that call simply there to gain access to the proper glob base?

**Comment by HiDeoo** [comment]
> I figured that the issue was that I wasn't using the `.load()` function call like is done in Starlight's code

We're manually invoking the `load()` function in Starlight because the loaders we provide are just wrappers around the built-in Astro `glob()` loader and when the `load` function (the `load` property of the loader) is invoked by Astro for our loaders, we want to return the result of doing the same for the `glob()` loader.

Empty collection logs is something that has been spotted occasionally. One thing to potentially try is a “force” re-sync for the content using `npx astro sync --force` but if the issue persist, a [new issue in the Astro repo](https://github.com/withastro/astro/issues/new?assignees=&labels=&projects=&template=---01-bug-report.yml) would be super helpful.
