### ISSUE TITLE
"Unexpected Server Shutdown on Unsupported Social Platform in `astro.config.mjs`"

### ISSUE THREAD

**Issue by thagxt** [withastro/starlight#2731]
### What version of `starlight` are you using?

0.30.3

### What version of `astro` are you using?

5.0.2

### What package manager are you using?

npm

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

On a fresh install When I input a social platform into `astro.config.mjs` that's not on the supported list and save the file, the CLI throws an error, disconnects, and shuts down the server. I then have to restart it by running `npm run dev` again. Ideally, I expect it to throw the error but keep the server running.

error:
<img width="1473" alt="Screenshot 2024-12-19 at 21 53 31" src="https://github.com/user-attachments/assets/7c18024d-5c21-4c1a-a0c5-885f0528b8f7" />

config:
<img width="721" alt="Screenshot 2024-12-19 at 21 51 36" src="https://github.com/user-attachments/assets/4ae602fd-7c6e-4387-8546-b6c9a6105a62" />

### Link to Minimal Reproducible Example

https://stackblitz.com/github/withastro/starlight/tree/main/examples/basics

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by delucis** [comment]
Hi @thagxt — thanks for the issue!

This is unfortunately not possible for us to support as far as I know. Starlight is an Astro integration and we need valid user config to be able to start up. There’s no mechanism for an integration to ask Astro to keep the dev server waiting until we think user configuration is valid.

I hope at least the error message was useful enough to help you figure out what was up and how to fix it!
