### ISSUE TITLE
Syntax Highlighting Legibility: --sl-color-purple-high's low saturation value in light theme

### ISSUE THREAD

**Issue by RyanRBrown** [withastro/starlight#278]
### What version of `starlight` are you using?

0.3.1

### What version of `astro` are you using?

2.7.2

### What package manager are you using?

yarn

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

I'm not sure if this is a bug, but I was finding the default code syntax highlighting colors for the light theme to be a bit difficult to read, specifically distinguishing between the purple and black text. While looking into trying to update the theme and/or purple, I noticed the saturation value for `--sl-color-purple-high` is significantly lower than the other high color variables under the light theme. Was this intentional? No worries if it was, since I updated the color in my project, but I wanted to bring awareness to it just in case.

The variable under the light theme:
https://github.com/withastro/starlight/blob/1d3e705256fa0668db73b01c898e7e3b3b505c49/packages/starlight/style/props.css#L138

It looks like that purple might be only used in two places. One is "keyword" in the shiki theme:
https://github.com/withastro/starlight/blob/1d3e705256fa0668db73b01c898e7e3b3b505c49/packages/starlight/style/shiki.css#L7

The Configuration Reference page of the Starlight docs is a good example of the purple and black text being a bit difficult to distinguish when using the light theme:
https://starlight.astro.build/reference/configuration/#configure-the-starlight-integration

On a side note, thank you for making Starlight and Astro! It has been a joy to use both of them.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by delucis** [comment]
Thanks for the report! I think this was intentional at least in the sense that this purple was really designed for the title and links in tips:
<img width="569" alt="Tip variant of the Starlight aside component, which is purple" src="https://github.com/withastro/starlight/assets/357379/baa0b975-f95d-4123-9a74-9b2e4ca02e2f">

I kind of stole it when I was throwing together the syntax highlighting theme.

Will double check with @doodlemarks who did the designs what he thinks.

**Comment by delucis** [comment]
Confirmed that we can change this! Want to submit a PR bumping that saturation up to 90%?

**Comment by RyanRBrown** [comment]
Thanks for the quick replies and confirmation! I will try to setup a PR.
