### ISSUE TITLE
Build fails to resolve customCss with relative paths

### ISSUE THREAD

**Issue by hasparus** [withastro/starlight#285]
### What version of `starlight` are you using?

0.4.0

### What version of `astro` are you using?

2.5.0

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### What browser are you using?

Arc

### Describe the Bug

Relative paths in `astro.config.mjs` work during development, with `astro dev`, but `astro build` fails with the following error:

```
08:19:25 PM [content] "i18n" is not a collection. Check your content config for typos.
08:19:25 PM [content] Types generated 217ms
08:19:25 PM [build] output target: static
08:19:25 PM [build] Collecting build info...
08:19:25 PM [build] Completed in 389ms.
08:19:25 PM [build] Building static entrypoints...
Could not resolve "./src/styles/custom.css" from "virtual:starlight/user-css"
file: virtual:starlight/user-css
 error   Could not resolve "./src/styles/custom.css" from "virtual:starlight/user-css"
  File:
    virtual:starlight/user-css
  Stacktrace:
RollupError: Could not resolve "./src/styles/custom.css" from "virtual:starlight/user-css"
    at error (file:///Users/hasparus/workspace/sen-o-pograniczu/website/node_modules/.pnpm/rollup@3.26.0/node_modules/rollup/dist/es/shared/node-entry.js:2245:30)
    at ModuleLoader.handleInvalidResolvedId (file:///Users/hasparus/workspace/sen-o-pograniczu/website/node_modules/.pnpm/rollup@3.26.0/node_modules/rollup/dist/es/shared/node-entry.js:24632:24)
    at file:///Users/hasparus/workspace/sen-o-pograniczu/website/node_modules/.pnpm/rollup@3.26.0/node_modules/rollup/dist/es/shared/node-entry.js:24594:26
```

Changing paths to start with `/` fixed the problem, but it would be nice if the relative paths in Astro config were resolved consistently in both dev and build.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by delucis** [comment]
Thanks for the report! Absolute paths (or npm module specifiers) are the intended usage, but I had no idea relative paths worked during dev!

I'm not sure if we can support relative paths, but we should investigate, and if not, make sure there's a helpful error message when using them in dev.

**Comment by alexanderkirtzel** [comment]
Neither does the relative path nor the absolute path for `customCss` work for me.
Starlight is installed in a `docs` folder from the template.
To make sure the `/src/styles/` path is valid, I move an image to that folder and it works with `logo.src`.
As soon as I try to use `customCss` I get a `FailedToLoadModuleSSR`.

```js
export default defineConfig({
  integrations: [
    starlight({
      title: 'docs',
      customCss: ['/src/styles/custom.css'],
      logo: {
        src: '/src/styles/favicon.svg',
      },
    }),
  ],
});
```

**Could not import /src/styles/custom.css.**
```shell
Stack Trace
Error: Failed to load url /src/styles/custom.css (resolved id: /src/styles/custom.css) in virtual:starlight/user-css. Does the file exist?
    at loadAndTransform (file:///Users/.../docs/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:53376:21)
```

**custom.css**
```css
body {
  color: red;
}
```

I tried to take a deeper look at `virtual:starlight/user-css` but know too less about Asto, yet


What version of starlight are you using?
@astrojs/starlight: 0.4.1

What version of astro are you using?
astro: 2.7.0

**Comment by alexanderkirtzel** [comment]
Wow, never mind. That hurts. Everything works perfectly, once I figured out that there had been a trailing whitespace 🫠
![image](https://github.com/withastro/starlight/assets/3539781/b36a7df0-9952-40c9-b827-5cffe74da1a4)
