### ISSUE TITLE
Inline code with links UI confusion

### ISSUE THREAD

**Issue by HiDeoo** [withastro/starlight#304]
### What version of `starlight` are you using?

latest

### What version of `astro` are you using?

latest

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

I am not sure if this really categorizes as a bug, but considering I got a report for it, I thought I'd report it here in case this should be changed.

For a website containing generated code documentation with TypeScript types linked to their definitions, e.g. [`SidebarItem[]`](https://starlight.astro.build/reference/configuration/#sidebaritem), the report mentioned wrong types and even invalid TypeScript syntax.

It took me a little bit to figure out the issue, but to take an example from from the official docs, heres a potential screenshot of the issue:

![repro](https://github.com/withastro/starlight/assets/494699/80200814-3ea9-4ab0-b5aa-593faec879b7)

The reader thought the code was `SidebarItem[.].` (notice the dots in the middle and after the array brackets).

There are multiple easy solutions to fix this from a user perspective (which is what I did), e.g. changing the font for inline code, removing underline for links in inline code, adding an underline offset, etc. altho considering this is also visible in the official docs with the default theme, I thought I should still mention it here.

### Link to Minimal Reproducible Example

https://starlight.astro.build/reference/configuration/#sidebar

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by delucis** [comment]
Thanks for flagging @HiDeoo! Will take a look. One quick (although potentially ugly) fix could be to set [`text-decoration-skip-ink: none`](https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration-skip-ink) to minimize the ambiguity.

**Comment by delucis** [comment]
Proposed a fontstack fix in #308 — curious if you think this is sufficient.

My idea with the skip-ink solution seems to only work in some browsers. It requires the browser to apply `code` text-decoration styles to the underline of its parent `a`. Firefox and Chromium browsers do this in my testing, Safari does not. Could still add it as an extra layer of protection if we think it’s needed.
