### ISSUE TITLE
Search is only available in production builds.

### ISSUE THREAD

**Issue by cgfarmer4** [withastro/starlight#310]
### What version of `starlight` are you using?

0.4.1

### What version of `astro` are you using?

2.7.0

### What package manager are you using?

npm

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

I cant get the production build to work correctly with search anymore.

Run on a clean build.

```
npm create astro@latest -- --template starlight
npm run build
npm run preview
```

<img width="1700" alt="image" src="https://github.com/withastro/starlight/assets/336449/f6343bc6-88f1-401c-8381-3b4761839b84">

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by cgfarmer4** [comment]
Nevermind, my NODE_ENV was set to `development`. 🤦

**Comment by Kyjor** [comment]
@cgfarmer4 Did the search actually return anything for you? I'm trying the same thing but I don't see any results

**Comment by cgfarmer4** [comment]
In prod, yea. You have to run the prod build locally to preview it. That’s what builds the search indexes.

**Comment by Kyjor** [comment]
Thanks. For some reason, my project was pointing to the wrong directory for page find. When I manually changed the folder name, it started working.
