### ISSUE TITLE
'tableOfContents' could be all the way to the right

### ISSUE THREAD

**Issue by usrme** [withastro/starlight#321]
### What version of `starlight` are you using?

0.5.0

### What version of `astro` are you using?

2.8.0

### What package manager are you using?

npm

### What operating system are you using?

Linux

### What browser are you using?

Firefox

### Describe the Bug

I'm using Starlight (wonderful framework, by the way!) to create a simple page to host [various snippets](https://usrme.xyz/snippets/ansible/) and it's clear from both that site and the official [Starlight documentation](https://starlight.astro.build/reference/configuration/) that the table of contents on the right-hand side leaves far too much negative space on the right (see images below). I'm not sure why the width of the content is sacrificed for this.

The removal of [this](https://github.com/withastro/starlight/blob/ea20c70dd46efe8a07e4c8953354200d963e2922/packages/starlight/layout/TwoColumnContent.astro#L25-L28) somewhat alleviates the issue, but only marginally as then the main content area widens, but not the containing text etc.

### Link to Minimal Reproducible Example

![image](https://github.com/withastro/starlight/assets/5902545/4553d621-fb52-4fb3-a7b0-15efac04caf0)

---

![image](https://github.com/withastro/starlight/assets/5902545/c6cb66fe-47a0-4ff2-9b4f-20ef9e842d88)

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by delucis** [comment]
Hi @usrme! Thanks for the issue — glad you’ve been enjoying Starlight.

> I'm not sure why the width of the content is sacrificed for this.

This is a design decision to keep the length of individual lines of text at a comfortable length for reading, not really something dictated by the right sidebar.

You can customize the width of the content column by setting the `--sl-content-width` custom property in some [custom CSS](https://starlight.astro.build/guides/customization/#custom-css-styles), e.g.

```css
:root {
  --sl-content-width: 95ch;
}
```

There’s an example of a user who did just that here: https://brycerussell.github.io/qbcore-docs/guides/linux-installation/

Is that what you were looking for?

**Comment by usrme** [comment]
Thank you for explaining the rationale. That difference made a world of difference to me and there's no real need to change anything specific to Starlight itself! :tada:

![image](https://github.com/withastro/starlight/assets/5902545/c1e15340-bb6a-4b6c-b718-5da64e237fe1)
