### ISSUE TITLE
Any possibility of adding threads to the social networks?

### ISSUE THREAD

**Issue by cgfarmer4** [withastro/starlight#329]
### What version of `starlight` are you using?

1.0.0

### What version of `astro` are you using?

2.7.0

### What package manager are you using?

npm

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

Happy to write a PR for this but it looks like you guys only have support for places that Astro has profiles.

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by delucis** [comment]
Sure! I'd be happy to add this if you'd like to make a PR 🙌
