### ISSUE TITLE
Cannot find module while customizing Starlight

### ISSUE THREAD

**Issue by kpetravicius** [withastro/starlight#331]
### What version of `starlight` are you using?

0.5.0

### What version of `astro` are you using?

2.7.0

### What package manager are you using?

npm

### What operating system are you using?

Windows

### What browser are you using?

Chrome

### Describe the Bug

Some problem with path recognition. while trying to customize Starlight by adding logo.
Trying to add logo by documentation:

1.  Added logo file to `src/assets/` directory.
2.  Added path to logo inside `astro.config.mjs`.

 
![image](https://github.com/withastro/starlight/assets/25895065/11ccb22b-83f5-4438-aed9-7e8dad1bac28)

And then error occurs, saying :
`Cannot find module 'C:
epCUSTOMoctopus-docssrcassetslogo.svg' imported from 'virtual:starlight/user-images'
`

So my guess is that compiler parses path to logo incorrectly, because it has to be `C:/rep/CUSTOM/octopus-docs/src/assets/logo.svg`, but not `C:
epCUSTOMoctopus-docssrcassetslogo.svg' imported from 'virtual:starlight/user-images`

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by delucis** [comment]
Yeah looks like a Windows path parsing problem. Sorry about that!

As a quick workaround, could you try: `/src/assets/logo.svg` (without the `.` at the start)

And we'll look into how best to fix this. (I don't have a Windows machine so it's always fun debugging these things 😅)

**Comment by kpetravicius** [comment]
Oh, man.. Tried all possible variations and forgot the one you mentioned. It works 👍 🌞
