### ISSUE TITLE
Page becomes unscrollable after chaging theme in the mobilemenu

### ISSUE THREAD

**Issue by justinliu1985** [withastro/starlight#350]
### What version of `starlight` are you using?

0.5.2

### What version of `astro` are you using?

2.7.3

### What package manager are you using?

npm

### What operating system are you using?

win11

### What browser are you using?

chrome edge

### Describe the Bug

On the starlight document site, if the user chages to another theme in the mobilemenu and immediatly adjusts the window width to more than 50rem, the page will become unscrollable. 
![image](https://github.com/withastro/starlight/assets/105055890/bf624533-799b-446d-9daa-3a69eb28be9a)
![image](https://github.com/withastro/starlight/assets/105055890/5deba0c1-30ff-44b1-8de6-154af9812365)

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by delucis** [comment]
Thanks for the report @justinliu1985 — I can confirm it.

It’s actually not even dependent on changing the theme. Just opening the menu, then resizing the window is enough.
