### ISSUE TITLE
support for directory index pages

### ISSUE THREAD

**Issue by lschierer** [withastro/starlight#370]
### What version of `starlight` are you using?

2.8.5

### What is your idea?

At times it is useful to have an index page for directories other than the site root.  

currently you end up with 2 entries in the menu with the same name, one that acts as a directory, one that acts as a file.

trying to create a
guides.mdx and a guides/ (the latter a directory) does the same thing, but occasionally results in odd link generation issues that I am having trouble creating a minimal reproducible repository for. 

### Why is this feature necessary?

This might be to allow for the case where a user hand munges a url and you don't want to display a 404, or where you want to write about a category of things and then have specific instances of that category organized as leaf nodes under that root entry.  

### Do you have examples of this feature in other projects?

astro supports this without starlight by allowing the creation of index pages outside the content collection.

Hugo supports this by allowing users to create index and _index pages (the former is a traditional index page, the latter is a special category list page) at arbitrary levels of the site structure.  see https://gohugo.io/content-management/organization/

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by lschierer** [comment]
see https://github.com/lschierer/issues-370

**Comment by lschierer** [comment]
I do not want to resubmit essentially the same thing twice, but I was able to recreate a minimal repository of the bug version in 
https://github.com/lschierer/issues-370/tree/bug

**Comment by delucis** [comment]
Thanks for reporting @lschierer! Can confirm this is a bug.

**Comment by lschierer** [comment]
the introduction of the 
---
sidebar:
  order: 1
---

frontmatter added another wrinkle to this.

if I do not set slugs on the index pages, then this frontmatter will sort both the directory that the index.mdx is an index for, and the ordering of that index page within the directory.   I cannot order the location of a subdirectory within its parent without affecting the location of an index page, nor the location of an index page without putting all directories at the top of the parent directory.

**Comment by delucis** [comment]
Thanks @lschierer! Could you provide an example of the file tree and `sidebar.order` frontmatter? I’m not 100% sure I understand your description of the problem.

**Comment by lschierer** [comment]
I retract my last comment, I cannot reproduce it myself either in my test repo, or in my real repo today, despite having seen it consistently yesterday in my actual repository.  The index' frontmatter order attribute is now behaving the way I'd expect.

**Comment by lschierer** [comment]
okay, I don't fully understand the conditions when this triggers and does not yet.  I initially thought it had gone away over night on its own.  

[c7196ca](https://github.com/lschierer/issues-370/commit/c7196ca1b04a7316f9027ee05a7f52bb7277fcf7) shows a series of subdirectories under reference none of which have the order attribute.  of particular note, the index file is sorted incorrectly in otherdir as compared to workingdir (that is, workingdir has the expected behavior).

[fd90017](https://github.com/lschierer/issues-370/commit/fd900175be7356e405c8f1504fee9ce539d2b38f) shows adding the order attribute to the index file of the inconsistently sorted index file.  It didn't just move the index file however, it moved the directory as well.  If it had just moved the index file, I would be perplexed but able to adapt.  if it sorted the directory but not the index file, that would be be confused about how to deal with the weirdly sorted index, but accept that an index file _should_ affect the directory.   That it does *both* however is very odd.

**Comment by lschierer** [comment]
Using the above commit, [fd90017](https://github.com/lschierer/issues-370/commit/fd900175be7356e405c8f1504fee9ce539d2b38f), if you go to http://localhost:3001/reference/otherdir/dir1/ then you will see a normal functioning page.  If, however, you go to http://localhost:3001/reference/otherdir/dir1 (no final /) you will see the correct content but the next and previous buttons will be missing.  That commit does not show it, but if I had set the reference section to auto collapse, the missing final slash would also show the sidebar as collapsed while the same url with the final / would correctly expand that section of the sidebar.  

note this happens at every level of the tree, but I picked this example because my minimal repo actually has some text on the page so its a bit easier to see what's happening on that particular index page.

**Comment by kevinzunigacuellar** [comment]
I've been looking into this issue and noticed something interesting. It seems that in the recent versions of Starlight, there have been changes in how the auto-generated sidebar functions. Good news: Starlight doesn't crash anymore! 🌟 However, if you happen to have both a directory and a file with the same name inside an autogenerated folder, Starlight might prioritize the file over the directory when generating the file tree. In other words, it won't display the folder contents in the sidebar.

I've managed to replicate this behavior using StackBlitz. Check it out:

[Reproduction in StackBlitz](https://stackblitz.com/edit/github-exw9ku?file=src%2Fcontent%2Fdocs%2Findex.mdx)

Feel free to take a look and let me know your thoughts or if you need further details! 😊

**Comment by kevinzunigacuellar** [comment]
Related issue: when you have an index page within a folder in an autogenerated directory, it shows up in the sidebar. However, it vanishes once you create a file with the same name as the parent folder. Thought it might be helpful to note! 

[Reproduction in Stackblitz](https://stackblitz.com/edit/github-eayrqo)

Feel free to take a look and let me know your thoughts or if you need further details! 😊
