### ISSUE TITLE
Table border color tweak

### ISSUE THREAD

**Issue by HiDeoo** [withastro/starlight#390]
### What version of `starlight` are you using?

0.5.5

### What version of `astro` are you using?

2.9.2

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

When using the dark theme and rendering a table, some vertical borders are totally invisible due to the alternating row colors.

<img width="754" alt="SCR-20230724-oqrc" src="https://github.com/withastro/starlight/assets/494699/f2e8853c-030d-4abc-b936-f48624480885">

With the light theme, the borders are always visible even if it is subtle.

<img width="746" alt="SCR-20230724-orbi" src="https://github.com/withastro/starlight/assets/494699/9e212863-d27c-4c9f-9676-ab8a60c53ffb">

I think personally this makes the table a little bit harder to read on the dark theme. For comparison, here is the same table rendering on GitHub:

<img width="822" alt="SCR-20230724-orex" src="https://github.com/withastro/starlight/assets/494699/20d3b0ef-0a63-475b-9a27-907d554b44ac">

I may be the only one thinking this, so feel free to close this issue if you don't think it's worth addressing.

I tried using `--sl-color-hairline-light` instead of `--sl-color-hairline` for the border color and I think it looks better:

<img width="750" alt="SCR-20230724-orhv" src="https://github.com/withastro/starlight/assets/494699/64130e3f-633a-41f6-974c-9fe29368fd50">

With the light theme:

<img width="747" alt="SCR-20230724-orjn" src="https://github.com/withastro/starlight/assets/494699/665fe09b-78d3-4402-a1ca-d959eac7973c">

Any thoughts?

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-5jbmji?file=src%2Fcontent%2Fdocs%2Fguides%2Fexample.md

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by delucis** [comment]
Sorry I missed this last week @HiDeoo! Yes, I agree we could change that color as you proposed. Would love a PR.

**Comment by HiDeoo** [comment]
> Sorry I missed this last week @HiDeoo! Yes, I agree we could change that color as you proposed. Would love a PR.

No problem at all, I'll make a tiny PR for this tomorrow.
