### ISSUE TITLE
Ability to add arbitrary attributes to sidebar items

### ISSUE THREAD

**Issue by huijing** [withastro/starlight#395]
### What version of `starlight` are you using?

0.5.5

### What is your idea?

It would be helpful if we were able to have additional attributes to sidebar items such that we can add tags, e.g. "deprecated" tags, to individual sidebar items.

### Why is this feature necessary?

This feature is relevant for docs sites where we have multiple versions of the product and certain features have been deprecated. We do not want to remove the documentation for the deprecated features altogether, but make it clear these features are deprecated both on the markdown itself, and also in the sidebar, as a convenient visual indicator.

### Do you have examples of this feature in other projects?

- MDN reference
    ![Screenshot_2023-07-24_at_10 39 11_AM](https://github.com/withastro/starlight/assets/1461498/3807bc33-f0e2-49e0-96de-5e578d56af35)

- Docusaurus allows the `className` attribute which allows this to be done with CSS (see https://docusaurus.io/docs/sidebar/items).

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by delucis** [comment]
Thanks for the issue @huijing! Are class names enough do you think, or do we need the ability to add any attribute?

**Comment by huijing** [comment]
@delucis I think I might be influenced by my previous experience using Docusaurus, but I feel like class names seem like the best option for a feature request like this. They are versatile enough to allow us to customise the look of the label without adding too much complexity around props and children being passed around. What do you think?

**Comment by delucis** [comment]
Adding here @khendrikse’s request to be able to set a link’s `target` (e.g. if you prefer an external link to open in a new window). So that would be an argument to support a wider range of link attributes.
