### ISSUE TITLE
Support site title to appear after page title

### ISSUE THREAD

**Issue by dhruvkb** [withastro/starlight#400]
### What version of `starlight` are you using?

0.5.2

### What is your idea?

Starlight currently prints the title of a page as written in the frontmatter. I want to set it such that the site title appears after the page title. So a page called "Introduction" on my site actually renders the title "Introduction • Dhruv".

### Why is this feature necessary?

Site titles are a useful part of the title as that's visible in the tab bar. It helps to disambiguate two pages from different sites that have the same name.

### Do you have examples of this feature in other projects?

The Astro documentation prints the site title after page title using this line in the layout:

https://github.com/withastro/docs/blob/17ff293f3f753404cce925b9c6f2d62edad6ca60/src/layouts/SplashLayout.astro#L24

As a Starlight user, I don't have access to change the layout, so I must at least have a config option to specify a format for `<title>` and Starlight populatesthe site title and page title into the format automatically.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by delucis** [comment]
Thanks for the issue! I agree a template config to customise how the page title is composed would be useful.

In the meantime, it is possible to customise the title on a per-page basis with the [`head` field in frontmatter](https://starlight.astro.build/reference/frontmatter/#head) although that’s not great for the main use case of a consistent template here.

```md
---
title: About us
head:
  # Use a custom <title> tag
  - tag: title
    content: About us • My site
---
```

**Comment by andremralves** [comment]
I would like to implement this feature. I will make a proposal soon. :+1:
