### ISSUE TITLE
autogenerate sub groups don't respect collapsed

### ISSUE THREAD

**Issue by simonhyll** [withastro/starlight#408]
### What version of `starlight` are you using?

0.5.6

### What version of `astro` are you using?

2.9.3

### What package manager are you using?

pnpm

### What operating system are you using?

Windows

### What browser are you using?

Chrome

### Describe the Bug

The following config still produces the sub groups as being expanded. Note that "Core concepts" is collapsed as expected, it's just that once you expand it the sub groups are already expanded. This is different from if you enter the links manually, then the sub groups are correctly respecting the collapsed setting in sub groups.
```js
        {
          label: "Core concepts",
          collapsed: true,
          items: [
            {
              label: "Architecture",
              autogenerate: { directory: "3/core/architecture", collapsed: true },
            },
            {
              label: "Features",
              autogenerate: { directory: "3/core/features", collapsed: true },
            },
          ]
        },
````
![image](https://github.com/withastro/starlight/assets/79983560/ed043f1c-b61b-4f04-8c6b-06553903d2dd)

### Link to Minimal Reproducible Example

https://github.com/simonhyll/tauri-docs/tree/simons-starlight

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by HiDeoo** [comment]
You may be looking for something like this:

```diff
{
  label: "Core concepts",
  collapsed: true,
  items: [
    {
      label: "Architecture",
+     collapsed: true, // This collapses the architecture section
      autogenerate: {
        directory: "3/core/architecture",
        // This would collapse any auto-generated sub-sections if any.
        collapsed: true
      },
    },
    {
      label: "Features",
+    collapsed: true, // This collapses the features section.
      autogenerate: {
        directory: "3/core/features",
        // This would collapse any auto-generated sub-sections if any.
        collapsed: true
      },
    },
  ]
},
```

Basically, `autogenerate.collapsed` only applies to further directories within the autogenerated items.

**Comment by simonhyll** [comment]
@HiDeoo That was it 🤦🏻‍♂️ Thanks for the help! 😄
