### ISSUE TITLE
GitLab and Teams options in Social Links

### ISSUE THREAD

**Issue by florentcm** [withastro/starlight#410]
### What version of `starlight` are you using?

0.5.6

### What is your idea?

I suggest adding more options to the Social Links : Gitlab (alternative to Github) and Teams Channel (alternative to Discord).
https://starlight.astro.build/guides/customization/#social-links

Another option could be to provide customizable options where link and icon are editable from the configuration so that we can add any missing service.

### Why is this feature necessary?

To support more variety of services in top navigation links.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by delucis** [comment]
Thanks for the issue. Adding GitLab in the next release. Wasn’t 100% sure what “Teams Channel” means from a web search. Is it Microsoft Teams? What would the icon look like?

**Comment by florentcm** [comment]
Thanks for the answer. You guessed right with Microsoft Teams, the link would redirect to a specific Microsoft Teams channel.
I don’t have better logos than the two options you provided.
