### ISSUE TITLE
Set sidebar title and hide pages from autogenerated sidebar

### ISSUE THREAD

**Issue by lorenzolewis** [withastro/starlight#420]
### What version of `starlight` are you using?

0.5.6

### What is your idea?

Add the following frontmatter properties after https://github.com/withastro/starlight/pull/359 is merged that will help users shape sidebars autogenerated:
- `sidebar > hide` that will hide the entry from being rendered in the sidebar
- `sidebar > label` that will allow a user to specify the text they want to be used in a sidebar (can also make i18n for sidebar items much easier)

### Why is this feature necessary?

Deriving the sidebar from the filesystem can be super helpful for large collections, but right now Starlight doesn't give you much flexibility to shape the derived sidebar.

Adding `sidebar > label` could also make it easier to localise sidebar labels outside of the config. This could be coupled with https://github.com/withastro/starlight/issues/384 to help reduce the amount of page-specific data the config is required to contain and instead offload that to page-specific frontmatter.

### Do you have examples of this feature in other projects?

https://docusaurus.io/docs/sidebar/autogenerated#doc-item-metadata

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by delucis** [comment]
Thanks for the issue @lorenzolewis! Added the `label` behaviour in #424. Might provide a template for a PR for the `hide` option if you’re interested in making one? I _might_ prefer `hidden` over `hide` although not 100% convinced.

**Comment by lorenzolewis** [comment]
Absolutely, I'd be happy to take that one to wrap it up 💪
