### ISSUE TITLE
Table of contents current highlight behavior

### ISSUE THREAD

**Issue by HiDeoo** [withastro/starlight#455]
### What version of `starlight` are you using?

0.6.1

### What version of `astro` are you using?

2.9.7

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

Let's say you are visiting a page on a desktop device which contains various heading like the Starlight getting started guide for example.

On a [basic visit](https://starlight.astro.build/getting-started/) without targeting any specific anchor, the table of contents looks perfect. If you scroll or manually select a heading in the toc, everything updates as expected. Now, if you visit the page using a [link with an anchor](https://starlight.astro.build/getting-started/#deploying-your-starlight-website), the table of contents highlight on page load is a bit annoying as it jumps from the _Overview_ to the current heading.

https://github.com/withastro/starlight/assets/494699/b4d03a94-959d-464b-8a8c-c378c214f91f

If you have JavaScript disabled, a basic visit with no anchor will be fine at first. If you scroll or manually select a heading in the toc, the table of contents will still highlight the _Overview_ heading which is invalid at this point. If you visit the page using a link with an anchor, the _Overview_ heading will still be highlighted which is also invalid.

So to recap the current behavior of the table of content highlight:

| Anchor | First load with JS | First load with no JS | Scroll or selection with JS | Scroll or selection with no JS |
| ------ | ------------------ | --------------------- | --------------------------- | ------------------------------ |
| No     | Ok                 | Ok                    | Ok                          | Invalid                        |
| Yes    | Jump glitch        | Invalid               | Ok                          | Invalid                        |

These behaviors are due to the fact that when generating the table of content the first _Overview_ heading is always marked as current.

What is everyone's opinion on changing this behavior, e.g. in `generateToC()`:

```diff
if (toc.length === 0) {
- toc.push({ ...heading, children: [], current: true });
+ toc.push({ ...heading, children: [] });
} else {
```

This change would mean that when visiting a page with an anchor, the table of content highlight will no longer jump but just appears as soon as the JS is executed.

https://github.com/withastro/starlight/assets/494699/f6e0572e-6581-458e-bec8-6d7ea602433e

To recap the suggested behavior of the table of content highlight:

| Anchor | First load with JS           | First load with no JS | Scroll or selection with JS | Scroll or selection with no JS |
| ------ | ---------------------------- | --------------------- | --------------------------- | ------------------------------ |
| No     | Appears with JS without jump | None but not invalid  | Ok                          | None but not invalid           |
| Yes    | Appears with JS without jump | None but not invalid  | Ok                          | None but not invalid           |

To compare with Docusaurus for example, their behavior is similar to the suggested one with one small difference, they do not have an _Overview_ heading in their table of content so on the first page load with JS and no anchor, they have nothing to highlight.

Personally, I think this change could be a better approach as it removes a jump glitch and avoid showing invalid highlights but maybe I'm missing something. Any thoughts?

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-gmhmuw?file=src%2Fcontent%2Fdocs%2Fguides%2Fexample.md

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by delucis** [comment]
Just thought this through. I think the one drawback I see is the delayed popping in of the default highlight now being visible on each main navigation, but considering everything as laid out here, I agree it would be better to have a consistent behaviour across all kinds of page navigation and I think the jump is more visually distracting than the one-time version.

(Also ran some Lighthouse tests and this didn’t count towards any layout changes etc. in those results so doesn’t seem risky in that sense either.)
