### ISSUE TITLE
Feature request: badge for sidenav

### ISSUE THREAD

**Issue by kevinzunigacuellar** [withastro/starlight#478]
### What version of `starlight` are you using?

0.6.1

### What is your idea?

**Idea**: Add a badge to sidebar nav items.

**Example**: For UI component libraries it is very common to add a "new" badge next to a newly introduced component. 

- [*NextUI* Documentation](https://nextui.org/docs/guide/introduction)
<img width="285" alt="image" src="https://github.com/withastro/starlight/assets/46791833/fe0bf015-28c2-49e9-8a1c-0396a1afa47f">

### Why is this feature necessary?

I think it's a great addition to documentation sites to label "new" or "experimental" pages with a badge to highlight a newly introduced feature/component/utility to better capture users attention.

This could prompt users to try new/experimental features and contribute to maintainers feedback loop. Another use could be to alert that a feature/component/utility is deprecated.

[Astro docs](https://docs.astro.build/en/getting-started/) could benefit with the addition an "experimental" badge since a lot of new features are introduced as experimental.

### Do you have examples of this feature in other projects?

- [Radix UI](https://www.radix-ui.com/primitives/docs/overview/introduction) with a "deprecated" badge.
- [Next UI](https://nextui.org/docs/guide/introduction) with a "new" badge.
- [Supabase docs](https://supabase.com/docs) with a "community" badge.
- [Prisma docs](https://www.prisma.io/docs/getting-started/quickstart) with a estimated completion time. (Not my favorite use case, but valid)

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by HiDeoo** [comment]
This may be closely related to https://github.com/withastro/starlight/issues/395 which focus on adding either custom class names or all attributes to sidebar items so a similar result could be achieved using CSS.

Altho if this is super common, one could wonder if having a better API than letting the user rely on CSS to do this could be a good idea.

Maybe both discussion could be merged?

**Comment by kevinzunigacuellar** [comment]
Thanks for bringing up the other issue I completely missed it. I think the className approach could work. I think this use case its common enough to have it's own API. I was thinking something in the realm of

```js
starlight({
      title: 'My Docs',
      social: {
        github: 'https://github.com/withastro/starlight',
      },
      sidebar: [
        {
          label: 'Guides',
          items: [
            // Each item here is one entry in the navigation menu.
            { label: 'Bar', 
              link: '/guides/bar/',
              tag: 'new' // pass string
            },
            { label: 'Foo', 
              link: '/guides/foo/',
              tag: { 
                 // pass object
                 label: "deprecated",
                 color: "yellow",
              },
            },
          ],
        },
      ],
    }),
```

I am not very familiar with CSS internals in Starlight, so I am open to any suggestions.

**Comment by delucis** [comment]
Thanks for the feature request and detailed description @kevinzunigacuellar!

I think this probably could benefit from a dedicated configuration API as the alternative would be a class that uses, e.g the `::after` pseudo-element with replaced content, which would be a less accessible solution.

I’d guess people will also want a frontmatter-specified version of this API too, so that autogenerated sidebars can also include this.

**Comment by huijing** [comment]
Not sure if we want to combine the discussion with #395 but being able to indicate the tag via frontmatter would be a welcome dev experience enhancement. also noted on the point about accessibility if we are going to be adding textual tags to the sidebar items.
Does it make sense to have add both the classname config as well as this tag one?

**Comment by delucis** [comment]
Given there’s also a proposal for setting the `target` attribute in #497, it sounds like we might want any arbitrary attribute, not just class names. So I’d say these are two separate ideas, but both could be valid:
1. Dedicated API for adding badges to a sidebar item
2. A way to set any attribute you want on a sidebar item

**Comment by HiDeoo** [comment]
Small detail as I just stumble a similar website, I guess we may want to check that it's also fairly easy and does not break anything to swap the position of the label to the start. I have seen people using tags at the start to categorize rather than capture users attention, e.g.:

<img width="305" alt="image" src="https://github.com/withastro/starlight/assets/494699/1d9dcb48-6e4d-46e3-900d-d8d922bb0623">
