### ISSUE TITLE
Load js of Search component after user interaction

### ISSUE THREAD

**Issue by JosefJezek** [withastro/starlight#567]
### What version of `starlight` are you using?

0.7.3

### What is your idea?

`<Search client:interaction="pointerenter,focusin,pointerdown" />` in `packages/starlight/components/Header.astro`

Inspiration from site https://material-web.dev
```
<lit-island on:interaction="pointerenter,focusin,pointerdown" import="/js/hydration-entrypoints/menu.js">
```

### Why is this feature necessary?

We don't need js of Search component on a page in first time.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by delucis** [comment]
We already load the search component JS lazily after everything else is loaded, so I'm not sure delaying further would have a significant performance benefit while potentially worsening user experience by creating a noticeable delay at the moment they do want to search.

Have you noticed specific problems this would solve?

**Comment by delucis** [comment]
Thanks again for raising this @JosefJezek — closing for now as we haven’t had any more reports of this causing issues.
