### ISSUE TITLE
Adding CMD/CTRL+K 

### ISSUE THREAD

**Issue by ElementalCrisis** [withastro/starlight#618]
### What version of `starlight` are you using?

0.0.0

### What is your idea?

Hello,

Any plans to add CMD/CTRL+K support to the searchbar?  As its becoming more common to see on doc sites, would be a nice feature to see supported on Starlight. 

### Why is this feature necessary?

Allows the user to quickly access the search modal without using the mouse. 

### Do you have examples of this feature in other projects?

https://docusaurus.io/
https://nextra.site/

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by dreyfus92** [comment]
It is already implemented, you can use both of them.

**Comment by ElementalCrisis** [comment]
Hello,

My apologies, must have been something on my end as I just tried again and its working.
