### ISSUE TITLE
starlight fails to run with `astro@3.x.x`

### ISSUE THREAD

**Issue by vorillaz** [withastro/starlight#620]
### What version of `starlight` are you using?

0.8.0

### What version of `astro` are you using?

3.0.4

### What package manager are you using?

npm, pnpm

### What operating system are you using?

Mac

### What browser are you using?

Brave

### Describe the Bug

Hey, thanks a ton for this amazing project, kudos for your hard work.

I am currently trying to run the starlight demo project along with `astro@3.x.x`. Apparently, running the dev command or the building process fails with a really cryptic error message when trying to parse the `docs/index.mdx` file:

```
Expected ";" but found ":"
  File:
    /home/projects/github-e2wizh/src/content/docs/index.mdx:2:5
  Code:
    1 | ---
    > 2 | title: Welcome to Starlight
        |     ^
      3 | description: Get started building your docs site with Starlight.
      4 | template: splash
```
This error occurs only with `.mdx` files.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-e2wizh?file=package.json&on=stackblitz

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by HiDeoo** [comment]
> it seems that `starlight` somehow encapsulates the mdx parsing for `astro@2.x`

Indeed, Starlight is an integration acting as [a preset](https://docs.astro.build/en/reference/integrations-reference/#combine-integrations-into-presets) and combines multiple integrations into one: Starlight itself, `@astrojs/mdx`, `@astrojs/sitemap`, etc.

Support for Astro v3 for Starlight is not yet released, one important reason is that v3-compatible integrations don’t support v2 and vice versa but you can track the progress in [this PR](https://github.com/withastro/starlight/pull/615).

**Comment by vorillaz** [comment]
Thanks a ton, @HiDeoo. If you have a task list in place, I can lend a hand.
