### ISSUE TITLE
Starlight Tailwind injects incorrect colors in development

### ISSUE THREAD

**Issue by KubaJastrz** [withastro/starlight#639]
### What version of `starlight` are you using?

0.9.0

### What version of `astro` are you using?

3.0.6

### What package manager are you using?

pnpm

### What operating system are you using?

Windows

### What browser are you using?

Brave 1.57.57

### Describe the Bug

When starting a new project without Tailwind, the splash page looks the same in development and production, kinda like this: 

![image](https://github.com/withastro/starlight/assets/6443113/9d4c2b6c-ddd5-44c7-b3de-0d3c7865486e)

Repro: https://stackblitz.com/edit/github-pluqrm?on=stackblitz

----

When adding Starlight Tailwind @ 2.0.0, development changes colors: 

![image](https://github.com/withastro/starlight/assets/6443113/7636aab4-cee5-47d1-ada3-078c21143af8)

Repro: https://stackblitz.com/edit/github-pluqrm-zqmxmh?on=stackblitz

----

The colors are back to normal in production, however:

![Screenshot 2023-09-02 22 32 33 177](https://github.com/withastro/starlight/assets/6443113/e2659ebd-1413-4e0f-ba34-63a8fa94940b)

Repro: same link, just run `npm run build && npm run preview` in console

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-pluqrm-zqmxmh?on=stackblitz

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by KubaJastrz** [comment]
It seems like the colors are injected here: https://github.com/withastro/starlight/blob/%40astrojs/starlight-tailwind%402.0.0/packages/tailwind/index.ts#L63

Is this intentional?

**Comment by KubaJastrz** [comment]
Starlight theme is defined here: https://github.com/withastro/starlight/blob/%40astrojs/starlight-tailwind%402.0.0/packages/starlight/style/props.css#L1

**Comment by delucis** [comment]
Hi @KubaJastrz it looks like this reproduction is missing steps 3-5 in our guide to setting up Tailwind here: https://starlight.astro.build/guides/css-and-tailwind/#add-tailwind-to-an-existing-project

Could you try following those steps and seeing if it works as expected?

**Comment by KubaJastrz** [comment]
Creating custom tailwind.css file and disabling the default one helped (both dev&prod use colors from starlight-tailwind).

Although I'm not sure why starlight-tailwind provides custom colors to begin with.

Anyway, thanks for help. I'll close this issue for now.
