### ISSUE TITLE
Changing `--sl-nav-height` potentially breaks table of contents highlighting behavior

### ISSUE THREAD

**Issue by fk** [withastro/starlight#641]
### What version of `starlight` are you using?

latest

### What version of `astro` are you using?

latest

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

Changing the `--sl-nav-height` CSS variable (potentially) breaks the `Table of Contents` highlighting behavior.
If I understand correctly, this is because the highlighting logic hard-codes the navigation height in https://github.com/withastro/starlight/blob/88edd7ddae1b378451ba222a691e10c5b54b904c/packages/starlight/components/TableOfContents/starlight-toc.ts#L72

For the minimal reproducible example, I've modified the default `--sl-nav-height` definitions to a visibly larger value, and built the Starlight docs:

- https://github.com/fk/starlight/commit/bab3314406bfff35f4cff6872a6b7d0f67858516
- https://fk-bug-nav-height-toc-highlighting--velvety-tartufo-4cb6d0.netlify.app/getting-started/

Since https://starlight.astro.build/guides/css-and-tailwind/#custom-css-styles references https://github.com/withastro/starlight/blob/main/packages/starlight/style/props.css, which lists `--sl-nav-height`, I think it should be (as) safe (as possible) to modify it.

### Link to Minimal Reproducible Example

https://fk-bug-nav-height-toc-highlighting--velvety-tartufo-4cb6d0.netlify.app/getting-started/

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by delucis** [comment]
Could you point out particular examples in the reproduction that don’t work well? I may be being obtuse, but I’ve scrolled around it a bunch at various viewport sizes and the table of contents highlighting seems to work OK?

Agree with the issue in theory, but would love to see the thing breaking in practice!

**Comment by fk** [comment]
Here's a quick new video showing `No hash mark and fragment identifier` and `Clicking ToC links`: 

https://github.com/withastro/starlight/assets/21834/4251175b-d521-4843-8836-7c6046eeb231

**Comment by delucis** [comment]
Wonderful thanks so much for those super clear examples! Checking out your PR now.
