### ISSUE TITLE
Hard to read text in dropdown menus when using dark theme

### ISSUE THREAD

**Issue by hammadmajid** [withastro/starlight#65]
### What version of `starlight` are you using?

0.0.7

### What version of `astro` are you using?

2.4.3

### What package manager are you using?

pnpm

### What operating system are you using?

Windows

### What browser are you using?

Chrome

### Describe the Bug

**Description**

It's hard to read the text in dropdown menus when using dark theme. Also, the style of the dropdown menus should match with the rest of the site.

This behavior is same on *Microsoft Edge* and *Mozilla Firefox*.

**Screenshots**

![image](https://github.com/withastro/starlight/assets/67387019/04b163dc-e288-4cba-8b69-53ebedb27130)
---
![image](https://github.com/withastro/starlight/assets/67387019/632ce954-226c-4aa1-9113-67ec07e429e9)

**Additional context**

[G18: Ensuring that a contrast ratio of at least 4.5:1 exists between text (and images of text) and background behind the text](https://www.w3.org/TR/WCAG20-TECHS/G18.html#:~:text=If%20the%20background%20is%20a,contrast%20ratio%20with%20the%20background.)

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by dreyfus92** [comment]
Yeah I also think that the focus state should be removed, I was trying to look if the astro.build website had this same behavior but they don't

**Comment by delucis** [comment]
Ah, interesting! Might be Windows-specific. Here’s what it looks like in Firefox for me:

![dropdown screenshot showing correct colour scheme is used](https://github.com/withastro/starlight/assets/357379/49de8d3f-8cba-4e61-85d7-d8a29e888386)

Also doesn’t set the focus state when I click (only when navigating with a keyboard).

**Comment by delucis** [comment]
@hammadmajid @dreyfus92 Could you check @TheOtterlord’s proposed fix in #67 and let us know if it fixes this for you?

Preview URL is here: https://deploy-preview-67--astro-starlight.netlify.app/

**Comment by hammadmajid** [comment]
@delucis @TheOtterlord It's fixed on chrome for me now, but the issue still persists on Firefox and Edge. I'm running Windows 10 (22H2).

Firefox 113.0.1
![image](https://github.com/withastro/starlight/assets/67387019/bf6bb57e-5601-4e4c-af8c-744a6a1ec1bb)


Edge 113.0.1774.42
![image](https://github.com/withastro/starlight/assets/67387019/48faf50e-78b7-4e45-a39a-098178ef5dec)

**Comment by hammadmajid** [comment]
It looks fine on all browsers now.
