### ISSUE TITLE
Pagefind incorrect urls when built

### ISSUE THREAD

**Issue by Tanhe** [withastro/starlight#674]
### What version of `starlight` are you using?

0.9.0

### What version of `astro` are you using?

3.0.6

### What package manager are you using?

npm

### What operating system are you using?

Windows

### What browser are you using?

Chromium (Edge)

### Describe the Bug

Starting from a brand new project. 

`npm run build`

`npm run preview`

When you select the search box the page fails to load the pagefind scripts as it's looking for `_pagefind/` but the dist folder has `pagefind/`.

![image](https://github.com/withastro/starlight/assets/5613534/2bc6f70c-83e1-426f-9f56-ae7e737a5c83)

![image](https://github.com/withastro/starlight/assets/5613534/b5cafafc-6c8e-491c-9d11-b871bcb7bc3c)

Looking at this it might be this hardcoded bundlePath in `Search.astro`:

![image](https://github.com/withastro/starlight/assets/5613534/ae99e518-fb7c-4bf9-87f3-8a42cecb2dbf)

As a separate note, the build issues this warning:

![image](https://github.com/withastro/starlight/assets/5613534/fbe07c7f-b525-410e-bb5c-dc359d665d74)

There is a required change necessary here in index.ts:

![image](https://github.com/withastro/starlight/assets/5613534/2b80e31a-185f-405e-81e9-819e32e7075e)
^^ --source changed to --site makes the warning go away

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by delucis** [comment]
Closed in #676!
