### ISSUE TITLE
default 14px is too small for landing page text

### ISSUE THREAD

**Issue by fatihpense** [withastro/starlight#690]
### What version of `starlight` are you using?

0.9.1

### What is your idea?

First of all, thank you for the library. I saw it yesterday and used it today with pure joy!

One of my documentation readers commented that now the text on the landing page is hard to read on mobile.

I think it is customizable, but with great defaults and taste in other aspects, I think it would make starlight even more awesome to set default body text 16px.

Related line:
```
font-size: clamp(var(--sl-text-sm),calc(.5rem + 1vw),var(--sl-text-body));
```
Custom fix: add below variable to `custom.css` explained in the documentation
```
:root {
	--sl-text-sm: 1rem;
}
```

### Why is this feature necessary?

A reader of my documentation website cared enough to tell me the text is less visible than before.

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by delucis** [comment]
Thanks for sharing the feedback @fatihpense — really helpful to hear! In general our default body text is 16px, it’s only the card designs that scale slightly differently on small screens given the way they’re designed to highlight the headlines.

I think this is a case where I’ll defer to our designer who set the original defaults and leave this as something for people to override to their personal taste. But still appreciate you raising it!

**Comment by fatihpense** [comment]
Thank you for considering. I respect your decision. 

By the way, I'm still enjoying the clutter free, professional, minimalist documentation website. I sometimes visit my page just to look at it!

Thank you for your efforts. Looking forward to see new updates.
Best,
Fatih
