### ISSUE TITLE
Bug: Divider / Page Content not centered when `tableOfContents` disabled

### ISSUE THREAD

**Issue by Faf4a** [withastro/starlight#691]
### What version of `starlight` are you using?

0.9.1

### What version of `astro` are you using?

3.0.10

### What package manager are you using?

npm

### What operating system are you using?

Windows

### What browser are you using?

Chrome, Firefox

### Describe the Bug

When the tableOfContents option is disabled via the frontmatter in an MDX file, as shown below:

```mdx
---
title: Title of the Page
description: Description of the Page
tableOfContents: false
---
```

*Referring to [Discord (message)](https://discord.com/channels/830184174198718474/1070481941863878697/1149746360405459096)*

The resulting website exhibits a formatting issue where the divider and content are not properly centered on the page. This misalignment disrupts the visual presentation of the content.

*First time using stackblitz, so hopefully it's correct. The two examples are given in the two pre-made files.*

---

![img](https://media.discordapp.net/attachments/1070481941863878697/1149740836565815296/image.png?width=1199&height=426) *Basically nothing is centered.*

*Smaller screens / How it's supposed to be:*
![img](https://i.imgur.com/Lb6lXgp.png)

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-7maapr

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by delucis** [comment]
Thanks for the report @Faf4a! I can confirm this is a bug. If anyone wants to try fixing it, we'd love a PR!
