### ISSUE TITLE
Sidebar titles are not being updated when switching locales.

### ISSUE THREAD

**Issue by dreyfus92** [withastro/starlight#70]
### What version of `starlight` are you using?

0.0.7

### What version of `astro` are you using?

2.4.3

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

Titles on the sidebar are not being updated properly when you switch between locales. 

<img width="1475" alt="image" src="https://github.com/withastro/starlight/assets/85648028/1211da30-9e5a-4810-954f-48e046ab3e65">

<img width="1476" alt="image" src="https://github.com/withastro/starlight/assets/85648028/f883ad4c-6f54-45ea-9399-81400e4a1670">

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by delucis** [comment]
Oops! This definitely worked before but I probably broke it in #55. Thanks for reporting!

**Comment by dreyfus92** [comment]
@delucis I will take a look to that PR later.

**Comment by delucis** [comment]
Oh wait, I remember now. Titles are translated for “autogenerated” sidebars currently (see the Reference section for example), but not yet for explicit entries in the sidebar.

So here’s the current sidebar config:

https://github.com/withastro/starlight/blob/c4731c5829ef23d43499856fc1fd5e8c36ef6f24/docs/astro.config.mjs#L42-L63

We’ll need to set up a way to translate the “Start Here” items. I was delaying this while figuring out other “string” translations (like `ui.ts` in the Astro docs). Might end up suggesting a format something like:

```js
{
  label: 'Welcome, world',
  link: '/',
  translations: {
    de: 'Wilkommen, Welt',
  },
}
```
