### ISSUE TITLE
Can starlight autogenerate entire content directory items to sidebar navigation?

### ISSUE THREAD

**Issue by 100gle** [withastro/starlight#701]
### What version of `starlight` are you using?

latest

### What is your idea?

I am surprised by the [Autogenerated groups](https://starlight.astro.build/guides/sidebar/#autogenerated-groups) feature provided by Starlight. It's a great feature that generates items in the Sidebar navigation as much as possible by convention rather than configuration. However, it seems that this only applies to subdirectories under the content directory, and cannot be directly applied to content.

```ts
starlight({
	sidebar: [
	    {
		    label: 'My Astro Crash Courses',
		    autogenerate: { directory: 'content' },
	    },
	],
});
```

For example, my tutorial documents are arranged in the following way:

```
src
└── content
  ├── astro-concepts
  │   ├── bar.md
  │   └── foo.md
  ├── how-to-use-astro.md
  └── index.md
```

So, I would like to be able to directly generate all corresponding Sidebar navigation based on the content directory.

If there are files that need to be ignored, we can name them with `_` at the beginning of the file, similar to Astro, to prevent them from being generated. 

```
src
└── content
  ├── astro-concepts
  │   ├── bar.md
  │   └── _foo.md  # ignore this doc!
  ├── how-to-use-astro.md
  └── index.md
```

As for some attributes in the `sidebar` configuration, such as `label`, we can set them directly in the frontmatter. In this way, we can minimize the amount of configuration code we have to write.

```md
<!-- how-to-use-astro.md -->
---
label: 'Astro setup'  # manually overwrite the label by autogenerated.
---
# Hello, world!
...
```

### Why is this feature necessary?

Because Starlight is built on Astro and uses a file-based routing design, I believe that by using a file naming convention similar to SSR with frontmatter, it is possible to minimize the need for manual configuration in the Sidebar navigation as much as possible.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by delucis** [comment]
Hi @100gle, yes! If you don’t set `sidebar` in your config file, this is exactly what Starlight will do. Here’s the docs on this behaviour: https://starlight.astro.build/guides/sidebar/#default-sidebar

**Comment by delucis** [comment]
I’ll close this as I think this feature is already available, but please feel free to let me know if I misunderstood and should re-open!
