### ISSUE TITLE
relative links does not use current file's directory

### ISSUE THREAD

**Issue by scarf005** [withastro/starlight#702]
### What version of `starlight` are you using?

0.9.1

### What version of `astro` are you using?

3.0.6

### What package manager are you using?

pnpm

### What operating system are you using?

Linux

### What browser are you using?

Firefox

### Describe the Bug

given following structure:
```
.
└── src
    └── content
        └── docs
            └── guides
                ├── a.md
                └── b.md
```

https://github.com/withastro/starlight/assets/54838975/ddd6dfd4-1c6f-40c1-98b1-baff0f224ed9

```md
[b](b)

[./b](./b)
```
both links are resolved to `/guides/a/b`, whereas expected path is `/guide/b`. is this intended behavior?

## Other cases

https://github.com/withastro/starlight/assets/54838975/11129d82-684d-4c5f-95b9-2fb59e0505ee

vscode resolves relative markdown links using current file's directory.

[docusaurus resolves relative markdown links using current file's directory.](https://docusaurus.io/docs/next/markdown-features/links)

[html resolves relative links using current file's directory.](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#linking_to_relative_urls)

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-asbwyq-xpyz1g?file=src%2Fcontent%2Fdocs%2Fguides%2Fa.md

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by scarf005** [comment]
After some investigation I've found out that astro/starlight didn't modify markdown links. It's just that links like `/foo/bar` is actually `/foo/bar/index.html`, therefore links like `./baz` resolved to `/foo/bar/baz`. I wrote a simple remark plugin that resolves the link:

```ts
import { isAbsolute, join } from "node:path"

import type { Root } from "mdast"
import { visit } from "unist-util-visit"

// starts with ./ or ../
const relativePath = new RegExp(`^\\.\\.?/`)

export const fixRelativeLinks = () => (tree: Root) => {
  visit(tree, "link", (node) => {
    if (isAbsolute(node.url)) {
      return
    }
    if (!relativePath.test(node.url)) {
      return
    }
    // const prev = node.url
    node.url = join("..", node.url)
    // console.log(`${prev} -> ${node.url}`)
  })
}
```

**Comment by delucis** [comment]
Thanks for the issue. I think this is expected behaviour for now although depending on your usage it may not always be what you want. I wonder if you’d be interested in wrapping up your remark plugin into a published package? If so, we could add it to the plugins section of our showcase page for others who want the same behaviour.

**Comment by delucis** [comment]
Closing for now as something that can be fixed with a user plugin. Would still love to see this published or a blog post explaining how to set this up if someone is interested.
