### ISSUE TITLE
Document how skip homepage and go directly to docs

### ISSUE THREAD

**Issue by Plorenzo** [withastro/starlight#703]
### What version of `starlight` are you using?

0.9.1

### What is your idea?

Creating issue as requested here https://discord.com/channels/830184174198718474/1070481941863878697/1150449309674909876

Currently the theme main page is a homepage, a common use case will be to remove it to make the docs directly the main home page. 

So instad of this being the homepage [https://starlight.astro.build](https://starlight.astro.build), it would be directly this [https://starlight.astro.build/getting-started/](https://starlight.astro.build/getting-started/)

### Why is this feature necessary?

Not all projects need homepage for the docs, also makes it easier to integrate to other website in the same domain.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by mrVladimirN** [comment]
You can use in the defineConfig the redirects, something like this:

`import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';

// https://astro.build/config
export default defineConfig({
	redirects:{
		'/': '/guides/example'
	},
	integrations: [
	
		starlight({
			title: 'My Docs',
			social: {
				github: 'https://github.com/withastro/starlight',
			},
			sidebar: [
				{
					label: 'Guides',
					items: [
						// Each item here is one entry in the navigation menu.
						{ label: 'Example Guide', link: '/guides/example/' },
					],
				},
				{
					label: 'Reference',
					autogenerate: { directory: 'reference' },
				},
			],
		}),
	],
});
`

**Comment by boilemmashem** [comment]
The redirect solution didn't work for me. I'd also like to see a configuration option for no landing page, is there another solution to set that up?

**Comment by delucis** [comment]
Thanks for this issue @Plorenzo!

As @boilemmashem mentioned, the appearance of `src/content/docs/index.mdx` as a “homepage” with different styling is based on the `template: splash` frontmatter property. We document this here: https://starlight.astro.build/guides/customization/#page-layout

I’d be open to hear ideas for how to document this better, but at the moment I’m not sure of what specific changes would have made this clearer, so will close this issue. If there are places you would have looked or additional context that could have helped, please do let me know!
