### ISSUE TITLE
remark/rehype plugins doesn't work in MDX

### ISSUE THREAD

**Issue by stereobooster** [withastro/starlight#704]
### What version of `starlight` are you using?

0.9.1

### What version of `astro` are you using?

3.0.12

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### What browser are you using?

Safari

### Describe the Bug

```
pnpm build

> parsing@0.0.1 build /Users/vvysokinski/code/parsing
> astro build

[MDX] remark-math not applied.
To inherit Markdown plugins in MDX, please use explicit imports in your config instead of "strings." See Markdown docs: https://docs.astro.build/en/guides/markdown-content/#markdown-plugins
[MDX] rehype-katex not applied.
```

My config looks like this:

```js
  markdown: {
    remarkPlugins: ["remark-math"],
    rehypePlugins: ["rehype-katex"],
  }
```

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by HiDeoo** [comment]
Did you try importing the plugins as suggested in the error message? Do you get a similar error?

In your case, it would look something like this example:

```js
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';
import remarkMath from 'remark-math';
import rehypeKatex from 'rehype-katex';

export default defineConfig({
  // ...
  markdown: {
    remarkPlugins: [remarkMath],
    rehypePlugins: [rehypeKatex],
  },
});
```

**Comment by stereobooster** [comment]
Ah that what this message means. I didn't understand it. Yes it works that way. Thank you
