### ISSUE TITLE
Product Hunters banner should sit outside <main>

### ISSUE THREAD

**Issue by freaksauce** [withastro/starlight#706]
### What version of `starlight` are you using?

1.0.0

### What version of `astro` are you using?

3.0.6

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

The Product Hunters banner has a `role="banner"` however it is inside the `<main>` which raises the accessibility issue "The banner landmark is contained in another landmark." 

More information about why this is a problem is available in the Deque docs - https://dequeuniversity.com/rules/axe/4.7/landmark-banner-is-top-level

I think it would be possible to elevate this element in the DOM to above `<main>` without any rendering issues.

### Link to Minimal Reproducible Example

https://starlight.astro.build/

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by HiDeoo** [comment]
Thanks for the report 🙌 

To add a bit more context, we actually discussed not even using the `banner` role in the implementation PR (https://github.com/withastro/starlight/pull/564#issuecomment-1694180014 and https://github.com/withastro/starlight/pull/564#issuecomment-1693496140) but I guess it made it in.

**Comment by freaksauce** [comment]
Thanks had a read and realised what I suggested makes no sense because you already have a `<header>` which has the role of `banner` set implicitly and you should only have a single instance as it apparently can confuse assistive devices. I have probably spent way too much time thinking about this mind you :)

**Comment by delucis** [comment]
Oh, yeah, that’s my bad! Meant to remove this before merging #564 and forgot. Thank you for flagging @freaksauce! Would love a PR removing `role="banner"` from `Banner.astro` if anyone would like to make one?

**Comment by delucis** [comment]
Fixed in #781!
