### ISSUE TITLE
`editLink` doesn't respect astro's `srcDir`

### ISSUE THREAD

**Issue by roll** [withastro/starlight#718]
### What version of `starlight` are you using?

0.9.1

### What version of `astro` are you using?

3.0.13

### What package manager are you using?

npm

### What operating system are you using?

Linux

### What browser are you using?

Chrome

### Describe the Bug

Consider this config:

```js
import starlight from "@astrojs/starlight"
import { defineConfig } from "astro/config"

// https://astro.build/config
export default defineConfig({
  srcDir: ".",
  integrations: [
    starlight({
      editLink: {
        baseUrl: "https://github.com/user/repo/edit/main/",
      },
    }),
  ],
})
```

The generated `Edit page` button will be:
- https://github.com/user/repo/edit/main/SRC/...

PS.
Thanks for the great documentation engine!

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by delucis** [comment]
Thanks for the issue. Would love a PR fixing this if someone would like to try!

We already expose some of the Astro config [via a `virtual:starlight/project-context` module](https://github.com/withastro/starlight/blob/760e24b316a8b82545d7661c1630a77fac825674/packages/starlight/integrations/virtual-user-config.ts#L21). Could add `srcDir` there and then import it when working out the edit link.

**Comment by kevinzunigacuellar** [comment]
I would like to give it a shot 💜

**Comment by roll** [comment]
Thanks a lot for working on it!
