### ISSUE TITLE
Cannot read properties of undefined (reading 'some')

### ISSUE THREAD

**Issue by devilankur18** [withastro/starlight#723]
### What version of `starlight` are you using?

0.10.0

### What version of `astro` are you using?

3.0.13

### What package manager are you using?

npm

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

Check this bug bellow

<img width="1318" alt="image" src="https://github.com/withastro/starlight/assets/431165/fb7592ff-59ce-4326-b297-26a8c431e7be">
<img width="955" alt="image" src="https://github.com/withastro/starlight/assets/431165/a5a773ad-c24b-4d2b-b26e-082d88758e2a">

### Participation

- [X] I am willing to submit a pull request for this issue.
```[tasklist]
### Tasks
- [ ] https://github.com/withastro/starlight/pull/724
```

**Comment by delucis** [comment]
Could you share a minimal reproduction? This shouldn’t be possible I don’t think if you have Starlight’s docs schema configured correctly in `src/content/config.ts`.

**Comment by delucis** [comment]
Closing for now as we don’t have a reproduction. Please do update us if you can provide more information!
