### ISSUE TITLE
Add Facebook and Email Icons

### ISSUE THREAD

**Issue by EpicPizza** [withastro/starlight#727]
### What version of `starlight` are you using?

0.10.0

### What is your idea?

Add Facebook and Email icons so they can be used in socials.

### Why is this feature necessary?

Adding Facebook and Email icons would be a nice to have for anyone looking to add those to their starlight project.

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by delucis** [comment]
Thanks for the issue @EpicPizza — would be happy to receive a PR adding these.

We use the [Unicons icon library](https://iconscout.com/unicons/explore/line), so I’d suggest grabbing icons from there.

I’ll also note that #709 will soon unlock adding any custom markup to the icons component, which could help for use cases like this where a custom icon is desired.
