### ISSUE TITLE
feature request: built-in codegen for sidebar

### ISSUE THREAD

**Issue by naranyala** [withastro/starlight#728]
### What version of `starlight` are you using?

0.10.0

### What is your idea?

While I think this simple script can improve the development workflow, the script itself needs to be improved

```js
// update-sidebar.js

import fs from 'fs/promises';
import chokidar from 'chokidar';

const configFile = './astro.config.mjs';
const docsDirectory = 'src/content/docs';

// Function to update the configuration file based on the contents of the "docs" directory
async function updateConfig() {
  try {
    const docs = await fs.readdir(docsDirectory);
    const sidebarEntries = docs.map((doc) => ({
      label: doc,
      autogenerate: { directory: doc },
    }));

    let config = await fs.readFile(configFile, 'utf8');
    config = config.replace(
      /sidebar:\s*\[[^\]]*\]/,
      `sidebar: [${sidebarEntries.map((entry) => JSON.stringify(entry)).join(', ')}]`
    );

    await fs.writeFile(configFile, config, 'utf8');
    console.log('Updated astro.config.js based on "docs" directory.');
  } catch (err) {
    console.error(`Error: ${err}`);
  }
}

// Watch the "docs" directory for changes
const watcher = chokidar.watch(docsDirectory, { persistent: true });

// When a file is added or removed in the "docs" directory, update the config
watcher.on('add', updateConfig).on('unlink', updateConfig);

// Initial configuration update
updateConfig();

```

### Why is this feature necessary?

improve development workflow to write more docs

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by delucis** [comment]
Starlight already supports [auto-generating sidebar groups](https://starlight.astro.build/guides/sidebar/#autogenerated-groups) for you and the [default behaviour](https://starlight.astro.build/guides/sidebar/#default-sidebar) without `sidebar` config is to generate this based on your full `docs/` directory content. I think this covers everything this script would do without the dangers of trying to reliably update a JavaScript file?

**Comment by naranyala** [comment]
first try starlight I was hoping to always set manually to add a sidebar, that's the default behavior that I didn't realize, I need to dive deeper into the docs, thanks

**Comment by naranyala** [comment]
first try starlight I was hoping to always set manually to add a sidebar, that's the default behavior that I didn't realize, I need to dive deeper into the docs, thanks
