### ISSUE TITLE
Custom language definition for syntax highlighter

### ISSUE THREAD

**Issue by danielvaughn** [withastro/starlight#749]
### What version of `starlight` are you using?

0.10.0

### What is your idea?

As a user, I would like to provide my own language definition for syntax highlighting.

### Why is this feature necessary?

I admit this is an edge case - I'm developing a language and would like to provide syntax highlighting for it in my code examples. It would prevent me from having to implement a component from scratch for syntax highlighting.

(side note - I love Starlight, much thanks to the team for building this amazing tool)

### Do you have examples of this feature in other projects?

- No similar tool exists (to my knowledge)

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by HiDeoo** [comment]
There is an [ongoing effort](https://github.com/withastro/starlight/pull/742) to add Expressive Code to Starlight which would use [`astro-expressive-code`](https://github.com/expressive-code/expressive-code/blob/main/packages/astro-expressive-code/README.md) to render code blocks.

I think it uses [`@expressive-code/plugin-shiki`](https://github.com/expressive-code/expressive-code/blob/main/packages/@expressive-code/plugin-shiki/README.md#expressive-codeplugin-shiki) to perform syntax highlighting using [`shiki`](https://github.com/shikijs/shiki) which does [support](https://github.com/shikijs/shiki/blob/main/docs/languages.md#supporting-your-own-languages-with-shiki) adding your own language (using TextMate grammar files). 

Altho, I don't know how accessible this skiki API is through Expressive Code but maybe @hippotastic may have more informations regarding that part.

**Comment by danielvaughn** [comment]
fantastic, thanks so much for the quick response!

**Comment by hippotastic** [comment]
The `loadLanguage` API is not accessible through `plugin-shiki` yet, but I can definitely add this.

Once you have a `.tmLanguage` file and code snippet in your language ready, please share a link to it here and we'll give it a try!

**Comment by danielvaughn** [comment]
Thank you! If it's a matter of making a change to the codebase itself, I don't mind making my own PR.

**Comment by delucis** [comment]
Thanks for the issue and discussion! Sounds like this would need to be addressed in upstream libraries rather than Starlight directly, so will close the issue here if that’s OK — we can always revisit later if it turns out there’s some work needed on our end to expose new API options to users.
