### ISSUE TITLE
custom markdown headings not working

### ISSUE THREAD

**Issue by ahmadkakarr** [withastro/starlight#751]
### What version of `starlight` are you using?

0.10.1

### What version of `astro` are you using?

3.1.2

### What package manager are you using?

npm

### What operating system are you using?

windows

### What browser are you using?

chrome

### Describe the Bug

custom headings are not working
https://starlight.astro.build/guides/authoring-content/#other-common-markdown-features
like this
https://www.markdownguide.org/extended-syntax/#heading-ids

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by HiDeoo** [comment]
As specified in the [Markdown Cheat Sheet from The Markdown Guide](https://www.markdownguide.org/cheat-sheet/) linked in the documentation, custom heading IDs are part of the extended syntax which is not supported out of the box by all Markdown applications. This is the case for Starlight but Starlight and Astro supports adding 3rd-party plugins for Markdown & MDX.

In this case, you would need to install a plugin like [`remark-custom-heading-id`](https://www.npmjs.com/package/remark-custom-heading-id) and add it to your configuration:

```ts
import { defineConfig } from "astro/config";
import starlight from "@astrojs/starlight";
import { remarkHeadingId } from "remark-custom-heading-id";

export default defineConfig({
  integrations: [starlight({ title: "My Docs" })],
  markdown: {
    remarkPlugins: [remarkHeadingId],
  },
});
```

After that, a syntax like `## My Title {#custom-id}` should work as expected like in this [small example](https://stackblitz.com/edit/github-thg87x?file=astro.config.mjs) I made.

You can also find more details in this guide: https://docs.astro.build/en/guides/markdown-content/#markdown-plugins

**Comment by delucis** [comment]
Thanks for answering this @HiDeoo! Yes, this is not supported by default, but that solution should work for people who want to add this functionality.
