### ISSUE TITLE
bug(minor): Sidebar Labels breaking / not properly displaying

### ISSUE THREAD

**Issue by Faf4a** [withastro/starlight#754]
### What version of `starlight` are you using?

0.10.1

### What version of `astro` are you using?

3.1.2

### What package manager are you using?

npm, yarn

### What operating system are you using?

Windows

### What browser are you using?

Chrome, Firefox

### Describe the Bug

The Sidebar labels do not wrap when the given word is too long, however this works completely fine for longer sentences.

This is rather a minor issue.

Explanation with pictures:

| ❌ Long Words | ✅ Long Sentences|
| :-----------: | :-----------: |
| The word does not wrap as long sentences do | The word/sentence wraps as it should |
| ![image](https://github.com/withastro/starlight/assets/87046111/0ef50d15-fb7a-43d9-8af0-6c822eb3f596) | ![image](https://github.com/withastro/starlight/assets/87046111/d77733b0-fed5-4c1f-8321-ba17e7252f58)  |

### Link to Minimal Reproducible Example

https://stackblitz.com/github-7maapr

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by delucis** [comment]
Thank you for reporting! And I think @HiDeoo’s comment with all these examples is one of my favourites I’ve ever seen 😂
