### ISSUE TITLE
How can highlight specific lines in code blocks?

### ISSUE THREAD

**Issue by 100gle** [withastro/starlight#755]
### What version of `starlight` are you using?

latest

### What is your idea?

The current version of Starlight doesn't seem to highlight specific lines in a code block as the Astro documentation does. For example:
````
```json title="package.json" del={2} ins={3} ins="astro check && tsc --noEmit && "
  "scripts": {
    "build": "astro build",
    "build": "astro check && tsc --noEmit && astro build",
  },
```
````

Is this because we are waiting for the integration of `expressive-code` into Starlight? #742 

### Why is this feature necessary?

I wanna to make my documentation be more readable.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by HiDeoo** [comment]
> Is this because we are waiting for the integration of `expressive-code` into Starlight? #742

Yes, the Astro documentation is already using Expressive Code which supports markers through [`@expressive-code/plugin-text-markers`](https://github.com/expressive-code/expressive-code/tree/main/packages/%40expressive-code/plugin-text-markers).

You can even preview it yourself already in the deploy preview of #742, e.g. [this page](https://deploy-preview-742--astro-starlight.netlify.app/manual-setup/#configure-the-integration).
