### ISSUE TITLE
Missing "./layout" specifier in "@astrojs/starlight" package

### ISSUE THREAD

**Issue by f4ez** [withastro/starlight#779]
### What version of `starlight` are you using?

0.10.2

### What version of `astro` are you using?

3.1.4

### What package manager are you using?

yarn

### What operating system are you using?

windows

### What browser are you using?

chrome

### Describe the Bug

$ yarn build
yarn run v1.22.19
$ astro build
[astro] Unable to load your Astro config

 error   Missing "./layout" specifier in "@astrojs/starlight" package

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by HiDeoo** [comment]
I noticed you also opened https://github.com/HiDeoo/starlight-openapi/issues/5. Do you get this error with `starlight-openapi` installed/configured or not?

If yes, could you try removing it and see if you still get this error? I suspect the issue to be related to the one you opened in `starlight-openapi`.

**Comment by HiDeoo** [comment]
Confirmed that the issue was related to `starlight-openapi` so unrelated to Starlight itself.
