### ISSUE TITLE
Multiple languages generate wrong language directory

### ISSUE THREAD

**Issue by LuHugo** [withastro/starlight#784]
### What version of `starlight` are you using?

0.10.2

### What version of `astro` are you using?

3.0.6

### What package manager are you using?

yarn

### What operating system are you using?

Mac

### What browser are you using?

Edge

### Describe the Bug

When multiple languages are configured, the built directory ignores uppercase letters and changes them all to lowercase letters, which results in routing to the 404 page.

```js
...
locales: {
  root: {
	  label: 'English',
	  lang: 'en-US'
  },
  'zh-CN': {
	  label: '简体中文',
	  lang: 'zh-CN'
  }
},
defaultLocale: 'root'
...
```
### build logs
```tree 
  generating static routes 
The collection **i18n** does not exist or is empty. Ensure a collection directory with this name exists.
▶ node_modules/@astrojs/starlight/404.astro
  └─ /404.html (+241ms)
▶ node_modules/@astrojs/starlight/index.astro
  ├─ /guides/example/index.html (+62ms)
  ├─ index.html (+140ms)
  ├─ /reference/example/index.html (+16ms)
  ├─ /zh-cn/guides/example/index.html (+39ms)
  ├─ /zh-cn/index.html (+52ms)
  ├─ /zh-cn/reference/example/index.html (+35ms)
  ├─ /zh-CN/guides/example/index.html (+17ms)
  ├─ /zh-CN/index.html (+10ms)
  ├─ /zh-CN/reference/example/index.html (+14ms)
  ├─ /zh-CN/zh-cn/guides/example/index.html (+17ms)
  ├─ /zh-CN/zh-cn/index.html (+8ms)
  └─ /zh-CN/zh-cn/reference/example/index.html (+9ms)

 generating optimized images 
  ▶ /_astro/houston.1bcfcd2a_2v3t3T.webp (before: 96kB, after: 27kB) (+1.23s) (1/1)
Completed in 1.94s.
```

<img width="350" alt="image" src="https://github.com/withastro/starlight/assets/7897415/dbfc9d7d-fc71-4118-857f-17934f77b3e7">

In the built folder `dist`, the `zh-cn` directory will be generated, and the correct one should be the `zh-CN` directory.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by jsparkdev** [comment]
```js
'zh-CN': {
  label: '简体中文',
  lang: 'zh-CN'
}
```

Change the above code to the code below.

```js
'zh': {
  label: '简体中文',
  lang: 'zh-CN'
}
```

And change the folder name to `zh`.

**Comment by LuHugo** [comment]
> ```js
> 'zh-CN': {
>   label: '简体中文',
>   lang: 'zh-CN'
> }
> ```
> 
> Change the above code to the code below.
> 
> ```js
> 'zh': {
>   label: '简体中文',
>   lang: 'zh-CN'
> }
> ```
> 
> And change the folder name to `zh`.
> 
> For more information, see https://starlight.astro.build/guides/i18n/#configure-i18n.

@jsparkdev 
I know this is completely feasible, but how to define `en-US`, `en-CA`, `en-UK` at the same time and what the routing should be. Is it possible to do routing like: `http://localhost:4321/en-US/docs/` and `http://localhost:4321/en-UK/docs/`. Some examples I have seen : `https://developer.mozilla.org/en-US/docs/Web`, `https://www.microsoft.com/en-us/`.
Ideally, this function should support keys such as `en-US`. I don't know if it is intentionally designed like this or if it is a bug.

**Comment by HiDeoo** [comment]
If I am not missing anything, this is the expected behavior. 

Each route segments in a content collection [are slugified](https://github.com/withastro/astro/blob/78adbc4433208458291e36713909762e148e1e5d/packages/astro/src/content/utils.ts#L226) using [`github-slugger`](https://github.com/Flet/github-slugger). This change was introduced in https://github.com/withastro/astro/pull/5666 and the [`maintainCase` option](https://github.com/Flet/github-slugger/blob/3461c4350868329c8530904d170358bca1d31448/index.js#L29-L30), which defaults to `false`, is not used meaning that every character is lowercased.

To handle `en-US`, `en-CA`, `en-UK` you can use the same pattern used in the Starlight documentation for `pt-BR`:

- `pt-br` [locale key](https://github.com/withastro/starlight/blob/afd26b7b00f26ac49636dce0419622632b79c9c5/docs/astro.config.mjs#L13) with a `pt-BR` label
- `pt-br` [folder](https://github.com/withastro/starlight/tree/afd26b7b00f26ac49636dce0419622632b79c9c5/docs/src/content/docs/pt-br)

The generated URLs will be `https://starlight.astro.build/pt-br/guides/i18n/` for example with `pt-br` avoiding the `enus` or `enuk` like you mentioned.

**Comment by LuHugo** [comment]
> If I am not missing anything, this is the expected behavior.
> 
> Each route segments in a content collection [are slugified](https://github.com/withastro/astro/blob/78adbc4433208458291e36713909762e148e1e5d/packages/astro/src/content/utils.ts#L226) using [`github-slugger`](https://github.com/Flet/github-slugger). This change was introduced in [withastro/astro#5666](https://github.com/withastro/astro/pull/5666) and the [`maintainCase` option](https://github.com/Flet/github-slugger/blob/3461c4350868329c8530904d170358bca1d31448/index.js#L29-L30), which defaults to `false`, is not used meaning that every character is lowercased.
> 
> To handle `en-US`, `en-CA`, `en-UK` you can use the same pattern used in the Starlight documentation for `pt-BR`:
> 
> * `pt-br` [locale key](https://github.com/withastro/starlight/blob/afd26b7b00f26ac49636dce0419622632b79c9c5/docs/astro.config.mjs#L13) with a `pt-BR` label
> * `pt-br` [folder](https://github.com/withastro/starlight/tree/afd26b7b00f26ac49636dce0419622632b79c9c5/docs/src/content/docs/pt-br)
> 
> The generated URLs will be `https://starlight.astro.build/pt-br/guides/i18n/` for example with `pt-br` avoiding the `enus` or `enuk` like you mentioned.

@HiDeoo  Thank you, this is very good. I noticed the `maintainCase` parameter you mentioned, can it be reconfigured to true by the user?

**Comment by HiDeoo** [comment]
> Can it be reconfigured to true by the user?

At the moment, this parameter is not something used or exposed in Astro and this is where this change would need to happen I guess. Altho, I guess a good first step would be to open an issue in the Astro repo to discuss this, not sure if this is something that would be accepted or not, maybe there is a good reason why this is done this way and not configurable I don't know. etc.

**Comment by LuHugo** [comment]
Got it, I think it would be a good idea to allow users to keep the original folder naming.
