### ISSUE TITLE
Sidebar h2 should be a span

### ISSUE THREAD

**Issue by JaneOri** [withastro/starlight#808]
### Describe the Bug

https://github.com/withastro/starlight/blob/main/packages/starlight/components/SidebarSublist.astro#L38

That `h2` should be a `span`

A few reasons:
1) these h2 are before the h1 in the document (shouldn't happen)
2) hx tags are meant to communicate the structure of the content, nav items aren't typically content
3) Sectioning roots (details, nav) do not _require_ hx tags within (in case that was the reason h2 was used there)
4) This component is recursively nested, specifying the same content heading at each layer is further confusing

ily, ty

**Comment by delucis** [comment]
Yes, I think that checks out! Thanks for reporting. Would you be up for PRing a fix?

**Comment by JaneOri** [comment]
No worries. :)

No thank you, but only because it'll take just 2 seconds for someone who already has it set up

**Comment by delucis** [comment]
Fair! Marking this as a good first issue for someone to pick up.

**Comment by hasham-qaiser** [comment]
hey guys i decided to pick this up and just submitted a PR for it. https://github.com/withastro/starlight/pull/810

**Comment by JaneOri** [comment]
PR was merged with the fix and released, thanks all! 💜
