### ISSUE TITLE
Optionally persist "open" state in Sidebar menu on page change

### ISSUE THREAD

**Issue by pReya** [withastro/starlight#853]
### What version of `starlight` are you using?

0.11.0

### What is your idea?

Currently, the menu categories/accordions are built with native `<details>` and `<summary>` elements. However, the state of the individual items (opened or closed) is not persisted across page changes/navigation.

So, when navigating to another page, the menu items are always reset to their default state.

It'd be nice to use `localStorage` to persist the menu state even when navigating around.

### Why is this feature necessary?

It's confusing and not understandable to users why this happens. There are many similar applications which keep their menu state. The user expects this to "just work".

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by HiDeoo** [comment]
This is possibly a duplicate of #307 talking about scroll position and sidebar state restoration.

No built-in solution has been implemented yet while the various possible solutions are being discussed but the linked issue contains a few workarounds if you want to try them out.

**Comment by pReya** [comment]
Thanks for pointing me to the other issue. Indeed, it's a duplicate, so I'm closing this one and will participate in the other discussion.
