### ISSUE TITLE
Support different `head` configs depending on build type

### ISSUE THREAD

**Issue by thibaultamartin** [withastro/starlight#857]
### What version of `starlight` are you using?

0.11.0

### What is your idea?

The astro config file supports a [`head`](https://starlight.astro.build/reference/configuration/#head) property, which can be used to add analytics among others.

It would be very useful to be able to add the analytics scripts only in production builds. In regular astro it's possible to use the following snippet in a BaseLayout to achieve the desired behaviour

```
    {
      import.meta.env.PROD && (
        <script
          async
          src="https://example.com"
          data-website-id="aUuidGeneratedByYourProvider"
        />
      )
    }
```

### Why is this feature necessary?

This feature is useful to be able to fiddle around in a dev environment without messing with page views, bouncing rates etc.

### Do you have examples of this feature in other projects?

A quick search shows that Docusaurus seems to rely on plugins for analytics

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by HiDeoo** [comment]
Thanks for your feedback.

The value of `import.meta.env.PROD` should be correct in your Astro config `astro.config.mjs` file, `true` when running `pnpm build` and `false` when running `pnpm dev`. This means you can conditionally use it with the [`head`](https://starlight.astro.build/reference/configuration/#head) you linked to in your issue:

```ts
starlight({
  // …
  head: [
    import.meta.env.PROD && {
      tag: "script",
      attrs: {
        src: "https://cdn.usefathom.com/script.js",
        "data-site": "MY-FATHOM-ID",
        defer: true,
      },
    },
  ].filter(Boolean),
}),
```

If you're not happy with the inline conditional/filtering, you should be able to do something like this:

```ts
const head: StarlightConfig['head'] = [];

if (import.meta.env.PROD) {
  head.push({
    tag: "script",
    attrs: {
      src: "https://cdn.usefathom.com/script.js",
      "data-site": "MY-FATHOM-ID",
      defer: true,
    },
  });
}

export default defineConfig({
  integrations: [
    starlight({
      // …
      head,
    }),
  ],
});
```

**Comment by HiDeoo** [comment]
> I’m not 100% sure if `import.meta.env` is available in `astro.config.mjs`

It seems to work as expected:

<img width="464" alt="image" src="https://github.com/withastro/starlight/assets/494699/0e1f8933-d689-4949-a704-2e988292842e">

**Comment by thibaultamartin** [comment]
Sorry for not getting back to you sooner, I tested and it indeed works as intended for me. Thanks for being this reactive and keep up the good work 💚
