### ISSUE TITLE
Support file names in code blocks

### ISSUE THREAD

**Issue by thibaultamartin** [withastro/starlight#858]
### What version of `starlight` are you using?

0.11.0

### What is your idea?

When writing documentation, it's often useful to show a file snippet to give readers a good idea of what they need to achieve and where (e.g. when updating a configuration file).

Being very explicit about which file is modified is useful to reduce the user confusion. For this, adding the file path and/or name right on top of the snippet is useful.

### Why is this feature necessary?

This feature is useful to help user understand what file they need to edit when reading the docs.

### Do you have examples of this feature in other projects?

Docusaurus uses a `title` property for code blocks: https://docusaurus.io/docs/markdown-features/code-blocks#code-title

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by HiDeoo** [comment]
There is an [ongoing effort](https://github.com/withastro/starlight/pull/742) to migrate Starlight code blocks to [Expressive Code](https://github.com/expressive-code/expressive-code) which [supports this feature](https://github.com/expressive-code/expressive-code/blob/main/packages/@expressive-code/plugin-frames/README.md#adding-titles-open-file-tab-or-terminal-window-title).

````md
```js title="my-test-file.js"
console.log('Hello World!')
```
````

or even with:

````md
```js
// my-test-file.js
console.log('Hello World!')
```
````

You can check a live preview [here](https://deploy-preview-742--astro-starlight.netlify.app/manual-setup/#configure-the-integration).

<img width="749" alt="image" src="https://github.com/withastro/starlight/assets/494699/e18db28d-0e60-4b13-8b84-7c1bacfd665d">
