### ISSUE TITLE
ESM errors when building.

### ISSUE THREAD

**Issue by ZeldOcarina** [withastro/starlight#887]
### What version of `starlight` are you using?

0.11.0

### What version of `astro` are you using?

3.3.0

### What package manager are you using?

yarn

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

When I try to build with `astro build` I get:
```
dist/_astro/MagnifingImage.astro_astro_type_script_index_0_lang.42c36336.js   0.12 kB │ gzip:  0.13 kB
dist/_astro/Tabs.astro_astro_type_script_index_0_lang.ea48f09d.js             0.99 kB │ gzip:  0.49 kB
dist/_astro/hoisted.dbfb2330.js                                               6.03 kB │ gzip:  2.43 kB
dist/_astro/ui-core.42dfa298.js                                              51.45 kB │ gzip: 16.83 kB
✓ built in 648ms
Completed in 664ms.


 generating static routes 
 error   Named export 'execaSync' not found. The requested module 'execa' is a CommonJS module, which may not support all module.exports as named exports.
  CommonJS modules can always be imported via the default export, for example using:
  
  import pkg from 'execa';
  const { execaSync } = pkg;
  
file:///Volumes/Mattia%20SSD/web-development.nosync/monarchy-projects/astro-air/packages/documentation/dist/chunks/pages/404_2ceafa5d.mjs:8
import { execaSync } from 'execa';
         ^^^^^^^^^
SyntaxError: Named export 'execaSync' not found. The requested module 'execa' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'execa';
const { execaSync } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:190:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
package.json:
```
{
  "name": "documentation",
  "type": "module",
  "version": "0.0.1",
  "scripts": {
    "dev": "astro dev",
    "start": "astro dev",
    "build": "astro build",
    "preview": "astro preview",
    "astro": "astro"
  },
  "dependencies": {
    "@astrojs/starlight": "^0.11.0",
    "astro": "^3.3.0",
    "sharp": "^0.32.6"
  },
  "devDependencies": {
    "typescript": "^5.2.2"
  }
}
```

tsconfig is standard.

I cannot give a repro repo right now.

It builds cleanly with bun. Yarn gives this issue, any clues?

### Link to Minimal Reproducible Example

https://google.com

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by HiDeoo** [comment]
This [comment](https://github.com/withastro/astro/issues/8297#issuecomment-1734652560) seems to contain a possible workaround for Starlight, would you be able to try it?

**Comment by ZeldOcarina** [comment]
Thank you!!
The workaround works! I would keep the issue open though as it's still.. an issue imo

**Comment by delucis** [comment]
Agreed. From what I’ve seen it’s specific to Yarn, but I’m not sure why exactly. For some reason the module is being understood as CJS? But `execa` does not ship CJS and the `package.json` specifies `"type": "module"`, so it’s a weird one. Is it possible another project dependency is pulling an old version of `execa` in and that one is being resolved or something? 🤔

**Comment by delucis** [comment]
One thing I could try is to see if upgrading to `execa@8` helps at all. The only breaking change there was dropping Node 14 support and Astro doesn’t even support Node 16, so should be safe — https://github.com/sindresorhus/execa/releases/tag/v8.0.0

v8 also switched the `exports` style in execa’s package.json, so might help?

<img width="253" alt="diff showing package.json exports field switching from single index.js value to an object with types and default properties" src="https://github.com/withastro/starlight/assets/357379/b7880259-9520-4d75-9cdf-20003e305f96">

**Comment by delucis** [comment]
@ZeldOcarina Any chance you could provide a reproduction? I’ve tried a few things, but haven’t been able to trigger this error, which makes it more or less impossible to test or fix.

**Comment by ZeldOcarina** [comment]
I've extracted the repo from the monorepo I was in and it builds without the workaround..
I really hope Bun becomes stable soon, these modules quirks are just a nightmare to work with..

**Comment by delucis** [comment]
Going to close this for now as we can’t do much without a reproduction unfortunately. Maybe we’re lucky and the `execa` update released in Starlight v0.11.1 was enough to fix this 🤞

**Comment by caiquecamargo** [comment]
I have the same issue here and just add execa as a dependency direct on the repo can solve the issue

```json
{
    ...
    "dependencies": {
        "@astrojs/starlight": "^0.11.0",
        "execa": "^8.0.0",
        "astro": "^3.3.0",
        "sharp": "^0.32.6"
    },
    ...
}
```

Maybe an another version o execa in another repo of this monorepo could be causing this

**Comment by delucis** [comment]
@caiquecamargo Were you also using Yarn?

**Comment by caiquecamargo** [comment]
> @caiquecamargo Were you also using Yarn?

Yes

**Comment by boneskull** [comment]
Same thing with `npm`.  I have a CJS version of `execa` elsewhere in my monorepo; adding a newer version to the astro workspace fixes the issue.
