### ISSUE TITLE
Support extending frontmatter schema

### ISSUE THREAD

**Issue by tomalaforge** [withastro/starlight#893]
### What version of `starlight` are you using?

0.11.0

### What is your idea?

I don't know if that's possible or if it's an astro feature, but how can we override props. 

Since the new version, we can override components and that's amazingly useful. But how can we add new props to the frontmatter reference. 

If that's possible, I think adding the tutorial inside the document can be very useful. 

### Why is this feature necessary?

increase possibility of customization

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by HiDeoo** [comment]
The frontmatter fields are validated using [Zod](https://github.com/colinhacks/zod) based on a specific [schema](https://starlight.astro.build/reference/frontmatter/).

If you want to add custom fields to the frontmatter, you will need to add them to the schema in your `src/content/config.ts` file:

```ts
import { defineCollection, z } from "astro:content";
import { docsSchema, i18nSchema } from "@astrojs/starlight/schema";

export const collections = {
  docs: defineCollection({
    schema: (ctx) =>
      docsSchema()(ctx).extend({
        // Add a new optional field to the schema.
        custom: z.string().optional(),
      }),
  }),
  i18n: defineCollection({ type: "data", schema: i18nSchema() }),
};
```

For reference, you can also check this [Discord thread](https://discord.com/channels/830184174198718474/1160202560028823562) discussing how extending the built-in schema could potentially be improved.

**Comment by tomalaforge** [comment]
Thanks a lot for your answer. 

It would be a great addon to the documentation.

**Comment by delucis** [comment]
We haven’t documented this yet, because the plan was to make the API a little nicer — especially to avoid the double function invocation `docsSchema()(ctx)`. I have an old branch I’ve been meaning to dust off with the intention to support a use more like:

```js
docsSchema({
  extend: z.object({
    custom: z.string().optional(),
  }),
})
```

We also need this for [migrating Astro’s docs to Starlight](https://github.com/withastro/docs/pull/3945), so should get to it soon hopefully.

**Comment by tomalaforge** [comment]
Ok make sense, The current API is quite easy to understand 😅

Thanks for your answer

**Comment by tomalaforge** [comment]
Ok make sense, The current API is quite easy to understand 😅

Thanks for your answer
