### ISSUE TITLE
Download Block (Component)

### ISSUE THREAD

**Issue by trueberryless** [withastro/starlight#906]
### What version of `starlight` are you using?

0.11.0

### What is your idea?

If you want to provide your users with files which are maybe not intended to be viewed but just used locally, a beautiful download button would be nice to have. I'm thinking of somethink like this:

![Download Component](https://github.com/withastro/starlight/assets/99918022/78585db2-0530-4589-bc24-4dc02cd40258)

To be more precise, it has the same dimensions as a code block, but as a content it has just the file name and a download button. Therefore, it doesn't have to look as ugly as this:

![image](https://github.com/withastro/starlight/assets/99918022/f423e22f-e824-4488-81ae-c7690cab81be)

I am willing to submit a PR for this issue if someone explains to me (or provides links for me) how I can build a component. However, first we should discuss how the markdown behind this beautiful piece of art should look like or if we can combine this feature with other useful features...

### Why is this feature necessary?

Make the UI more attractive...

### Do you have examples of this feature in other projects?

If the code blocks look beautiful, why not make everything beautiful?

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by HiDeoo** [comment]
Thanks for your suggestion.

Just to clarify and make sure I understand correctly, is there any specific reason why this would need to be built-in in Starlight vs being a community package that users could install and use in their Markdown or MDX files, e.g.:

```mdx
<DownloadLink href="link_to_something_to_download" />
```

Or not specifically but you think this is a common enough use case that it would be worth having it built-in?

**Comment by trueberryless** [comment]
Thank you for your quick response!

There is no specific reason why this needs to be built-in. I personally didn't know that there are community packages until now (although it makes a lot of sense), so maybe it's a better solution to ask the community.

I mean, it would be more convenient for me because I would use this feature commonly, but I guess that's not enough to get a built-in component... xD

Is there any specific website for community packages like crates.io for Rust crates? And where can I suggest this feature for the community? Just on [discord](https://discord.com/invite/grF4GTXXYm) or somewhere else?

**Comment by HiDeoo** [comment]
I see, thanks for the details. I'm only speaking for myself of course, but I think this could be a great use-case for a third-party/community package.

> Is there any specific website for community packages like crates.io for Rust crates? 

Technically, this would be the [npm registry](https://www.npmjs.com/) just like Starlight itself. This means that any component can be installed using npm or your favorite package manager (e.g. `npm i my-super-cool-component`), imported in an MDX file (e.g. `import SuperCoolComponent from 'my-super-cool-component'`) and used like the example I shared above.

> And where can I suggest this feature for the community? Just on discord or somewhere else?

Anyone can publish a package to npm, so you can publish your own components and share them with the community if you want or just build and use them in your own projects.

If you are interested, for an example of a Starlight specific component shared as a package through npm, you can check out [this one](https://starlight-package-managers.vercel.app/) ([repo](https://github.com/HiDeoo/starlight-package-managers)) I made.

**Comment by delucis** [comment]
Thanks for the issue @trueberryless!

I think I agree with @HiDeoo that this is a good candidate for a community package — maybe even one you build yourself! We could then link to it in the [Starlight Showcase](https://starlight.astro.build/showcase/#community-plugins).

One good way to start is probably to create a component you’re happy with in your own project. Then, once you’ve used it for a bit and feel it works well, you could extract it to a separate package and publish it to npm as explained by @HiDeoo.

Hope it’s OK if I close this issue as something we probably won’t add ourselves, but still happy to help explain more of these concepts or answer any questions you might have here.

**Comment by trueberryless** [comment]
Looking at old me is so funny right now. 😅

@delucis @HiDeoo I created a component now: https://github.com/trueberryless-org/starlight-download-link

But I would need help before I publish 0.1: You can set the `download` attribute on an `<a>` tag, but in Firefox the docs say: 
> If the HTTP header [Content-Disposition:](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition) gives a different filename than this attribute, the HTTP header takes priority over this attribute.
> If `Content-Disposition:` is set to `inline`, Firefox prioritizes Content-Disposition, like the filename case, while Chrome prioritizes the download attribute.

So I [try to set the header with `Astro.responde`](https://github.com/trueberryless-org/starlight-download-link/blob/29f45b94acbceb110e5482af7bb35289357635eb/packages/starlight-download-link/components/DownloadLink.astro#L5) but it doesnt work.

Please let me know if opening a new Discord thread is better than writing about the issue here. I just thought I can continue cause the context is already here...

**Comment by HiDeoo** [comment]
> So I [try to set the header with `Astro.responde`](https://github.com/trueberryless-org/starlight-download-link/blob/29f45b94acbceb110e5482af7bb35289357635eb/packages/starlight-download-link/components/DownloadLink.astro#L5) but it doesnt work.

Not quite sure I entirely understand what you mean :thinking: The `Content-Disposition` header can be set by a server when responding to a request for the linked resource and it could be any server so I'm not sure how it would be related to a download link component. I mean the browser would use this header in combination to a filename specified using the `download` attribute on an anchor tag if specified, but that's up to the browser to decide how to handle it and a component rendering a link wouldn't have control over that, even more if the downloaded file is on a different server.

Or maybe it's too early in the morning and I'm totally missing something (which is highly likely) :sweat_smile:

**Comment by trueberryless** [comment]
Hmmm, since it was very late when I wrote that component, I might as well have been completely lost, but there is one thing I noticed: I tested the component in Chrome and Firefox. And while in Chrome the download executes in the background without opening the PDF in a web view, Firefox didn't download anything, but open the PDF in a web view.

So I'm no expert in this case, I have no idea if it is good practice to enforce something (auto downloading in this case) for every Browser. So I think you're very likely right, I should leave it up to the browser... 

Would you also agree that just adding the download attribute would be enough declaration for the DownloadLink component? If the browser "wants" to download it then, it knows that it could or should, but we don't compel it. Because if you agree, I would say, I can publish the component without setting any headers (which doesn't work as I tried with Postman...).

**Comment by HiDeoo** [comment]
> So I'm no expert in this case, I have no idea if it is good practice to enforce something (auto downloading in this case) for every Browser. So I think you're very likely right, I should leave it up to the browser...

I don't think you can enforce anything in this case considering the browser will have the final word and its decision is based on the link attributes and the server response for a request and a component like yours would only control 1 part of the equation.

**Comment by trueberryless** [comment]
Perfect, then I just need to contact the npm registry, so they allow me to publish a package with "download" in it... 😅

**Comment by trueberryless** [comment]
Okay, finally found a name I'm happy with: https://starlight-save-file-component.trueberryless.org/ 🙌
