### ISSUE TITLE
The mobile table of contents experiences a scrolling penetration issue

### ISSUE THREAD

**Issue by justinliu1985** [withastro/starlight#976]
### What version of `starlight` are you using?

0.11.1

### What version of `astro` are you using?

3.3.2

### What package manager are you using?

npm

### What operating system are you using?

win11

### What browser are you using?

chrome

### Describe the Bug

Wherein scrolling the mouse within the dropdown menu does not affect the toc content but instead causes the underlying document to scroll.

### Link to Minimal Reproducible Example

https://github.com/withastro/starlight/assets/105055890/07b3e5e4-e090-4c80-83b7-0e4f2d3212b3

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by delucis** [comment]
Thanks for the issue @justinliu1985! This should be fixable by setting `overscroll-behavior: contain;` on the scroll element:

https://github.com/withastro/starlight/blob/c7112f90664f92e631853695dbb8413125ca04ce/packages/starlight/components/MobileTableOfContents.astro#L23-L25

Officially our browser support includes some older versions of Safari that don’t support `overscroll-behavior` (15.4–15.6 desktop, and 15.4–15.7 on mobile), but that’s a small percentage of supported users and this feels like a good candidate for progressive enhancement where the current behaviour impacting a few people would be acceptable.

Happy to receive a PR if someone would like to make one!
