### ISSUE TITLE
Edit page link fallback not working

### ISSUE THREAD

**Issue by trueberryless** [withastro/starlight#981]
### What version of `starlight` are you using?

0.11.0

### What version of `astro` are you using?

3.0.6

### What package manager are you using?

pnpm

### What operating system are you using?

Windows

### What browser are you using?

Brave

### Describe the Bug

When clicking "Edit page" at the bottom of the page (when enabled) but the page is not available in the current language (the fallback page is currently shown instead), then the link does not use a link to GitHub to the fallback page but to a page that does not exists, therefore leading to this page:

![image](https://github.com/withastro/starlight/assets/99918022/1dda4299-24a2-4c05-87ac-ff6b975cc981)

I at least encountered this problem, when English is not the default local...

### Link to Minimal Reproducible Example

https://starlight.astro.build/de/guides/overriding-components/

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by delucis** [comment]
Ah, good point! I wonder what the correct behaviour is.

- Link to edit the default locale file being used for fallback content
- Link to create a new file for the current language
- Hide the edit link on pages using fallback content

**Comment by HiDeoo** [comment]
> Link to create a new file for the current language

This is something I did in a project by overriding the `<EditLink/>` component when `isFallback` is `true` and I changed the sentence to "Translate this page" and the link uses the `filename` query parameter to specify which file to create (the `value` one is not really usable to pre-fill the file content).

I personally like that behavior a lot.

**Comment by delucis** [comment]
Yes, I think I agree that would also be the ideal behaviour although it would require some more config for a create-page base URL, and a new string in our translation dictionaries.

Given the increasing config complexity, it may also be nice to provide some presets for common hosts to avoid everyone having to figure out the base URLs when it can be done based on repo + branch etc.

**Comment by trueberryless** [comment]
I personally only thought about behaviour 1 (Link to edit the default locale file being used for fallback content)...
Therefore, I would say, this should be the default behaviour, but maybe the behaviour could also be chosen by the developer in `astro.config.mjx`...

Maybe there could even be multiple buttons on the bottom: "Edit this page", "Create page in this language"...

**Comment by delucis** [comment]
Maybe it would be smart to split this into two steps:

1. Fix the current behaviour to point to the existing file

2. Treat support for a "Translate this page" link as a feature request
